;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	CE44AA7A114237C6B3CD67EEA9C0225A

; File Name   :	th03/MAINL.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-10CF0h Loaded length: F72Ch
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'E'

include ReC98.inc
include th03/th03.inc
include th01/hardware/grppsafx.inc
include th03/sprites/regi.inc
include th03/formats/scoredat.inc

	extern SCOPY@:proc
	extern _execl:proc

group_01 group CFG_LRES_TEXT, MAINL_SC_TEXT, CUTSCENE_TEXT, SCOREDAT_TEXT, REGIST_TEXT, STAFF_TEXT, mainl_03_TEXT

; ===========================================================================

; Segment type:	Pure code
_TEXT		segment	word public 'CODE' use16
		assume cs:_TEXT
		assume es:nothing, ds:_DATA, fs:nothing, gs:nothing

include libs/master.lib/bfnt_entry_pat.asm
include libs/master.lib/bfnt_extend_header_skip.asm
include libs/master.lib/bfnt_header_read.asm
include libs/master.lib/bfnt_header_analysis.asm
include libs/master.lib/bcloser.asm
include libs/master.lib/bfill.asm
include libs/master.lib/bfnt_palette_set.asm
include libs/master.lib/bgetc.asm
include libs/master.lib/palette_black_in.asm
include libs/master.lib/palette_black_out.asm
include libs/master.lib/bopenr.asm
include libs/master.lib/bread.asm
include libs/master.lib/bseek.asm
include libs/master.lib/bseek_.asm
include libs/master.lib/dos_axdx.asm
include libs/master.lib/dos_filesize.asm
include libs/master.lib/dos_keyclear.asm
include libs/master.lib/dos_setvect.asm
include libs/master.lib/egc.asm
include libs/master.lib/file_append.asm
include libs/master.lib/file_close.asm
include libs/master.lib/file_create.asm
include libs/master.lib/file_exist.asm
include libs/master.lib/file_read.asm
include libs/master.lib/file_ropen.asm
include libs/master.lib/file_seek.asm
include libs/master.lib/file_size.asm
include libs/master.lib/file_write.asm
include libs/master.lib/dos_close.asm
include libs/master.lib/dos_ropen.asm
include libs/master.lib/grcg_boxfill.asm
include libs/master.lib/grcg_byteboxfill_x.asm
include libs/master.lib/grcg_setcolor.asm
include libs/master.lib/gdc_outpw.asm
		db 0
include libs/master.lib/gaiji_backup.asm
include libs/master.lib/gaiji_entry_bfnt.asm
include libs/master.lib/gaiji_read.asm
include libs/master.lib/gaiji_write.asm
include libs/master.lib/graph_400line.asm
include libs/master.lib/graph_clear.asm
include libs/master.lib/graph_copy_page.asm
include libs/master.lib/graph_extmode.asm
include libs/master.lib/graph_gaiji_putc.asm
include libs/master.lib/graph_pi_free.asm
include libs/master.lib/graph_pi_load_pack.asm
include libs/master.lib/graph_pack_put_8.asm
include libs/master.lib/graph_scrollup.asm
include libs/master.lib/graph_show.asm
include libs/master.lib/iatan2.asm
include libs/master.lib/js_end.asm
include libs/master.lib/palette_show.asm
include libs/master.lib/pfclose.asm
include libs/master.lib/pfgetc.asm
include libs/master.lib/pfread.asm
include libs/master.lib/pfrewind.asm
include libs/master.lib/pfseek.asm
include libs/master.lib/random.asm
include libs/master.lib/palette_entry_rgb.asm
include libs/master.lib/rottbl.asm
include libs/master.lib/smem_release.asm
include libs/master.lib/smem_wget.asm
include libs/master.lib/soundio.asm
include libs/master.lib/text_clear.asm
include libs/master.lib/text_fillca.asm
include libs/master.lib/vsync.asm
include libs/master.lib/vsync_wait.asm
include libs/master.lib/palette_white_in.asm
include libs/master.lib/palette_white_out.asm
include libs/master.lib/hmem_lallocate.asm
include libs/master.lib/mem_assign_dos.asm
include libs/master.lib/mem_assign.asm
include libs/master.lib/memheap.asm
include libs/master.lib/mem_unassign.asm
include libs/master.lib/super_free.asm
include libs/master.lib/super_entry_pat.asm
include libs/master.lib/super_entry_at.asm
include libs/master.lib/super_entry_bfnt.asm
include libs/master.lib/super_cancel_pat.asm
include libs/master.lib/super_put.asm
include libs/master.lib/respal_exist.asm
include libs/master.lib/respal_set_palettes.asm
include libs/master.lib/pfint21.asm
		db 0
include libs/master.lib/js_start.asm
include libs/master.lib/js_sense.asm
		db 0
include th03/formats/pfopen.asm
include libs/master.lib/pf_str_ieq.asm
include libs/master.lib/graph_pack_put_8_noclip.asm
_TEXT		ends

; ===========================================================================

CFG_LRES_TEXT	segment	byte public 'CODE' use16
	@cfg_load_resident_ptr$qv procdesc near
CFG_LRES_TEXT	ends

MAINL_SC_TEXT segment byte public 'CODE' use16
	@win_load$qv procdesc pascal near
	@win_text_put$qv procdesc pascal near
MAINL_SC_TEXT ends

; Segment type:	Pure code
CUTSCENE_TEXT segment byte public 'CODE' use16
		assume cs:group_01
		;org 3
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

	CDG_FREE_ALL procdesc near
	@win_animate_and_wait$qv procdesc near
	@sub_9887$qv procdesc near
	@stage_splash_load$qv procdesc near
	@stage_splash_show_and_wait$qv procdesc near
	@STAGE_SPLASH_SIDE_SHOT_PUT$QINC procdesc near
	@STAGE_SPLASH_SIDE_SHOTS_PUT$QI procdesc near
	@continue_menu$qv procdesc near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_978D equ <@win_animate_and_wait$qv>


sub_9887 equ <@sub_9887$qv>


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_990C equ <@stage_splash_load$qv>


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9A2C equ <@stage_splash_show_and_wait$qv>

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_9CB1 equ <@STAGE_SPLASH_SIDE_SHOT_PUT$QINC>


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_9D20 equ <@STAGE_SPLASH_SIDE_SHOTS_PUT$QI>


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __cdecl main(int argc, const char	**argv,	const char **envp)
public _main
_main		proc far

var_2		= byte ptr -2
var_1		= byte ptr -1
_argc		= word ptr  6
_argv		= dword	ptr  8
_envp		= dword	ptr  0Ch

		enter	2, 0
		call	@cfg_load_resident_ptr$qv
		or	ax, ax
		jz	@@ret
		call	@game_init_main$qnxuc pascal, ds, offset aCOul
		call	respal_exist
		mov	_snd_midi_active, 0
		les	bx, _resident
		cmp	es:[bx+resident_t.bgm_mode], SND_BGM_OFF
		jz	short loc_9DAD
		call	_snd_determine_mode

loc_9DAD:
		call	gaiji_backup
		push	ds
		push	offset aMikoft_bft ; "MIKOFT.bft"
		call	gaiji_entry_bfnt
		call	_snd_load c, offset aYume_efc, ds, SND_LOAD_SE
		call	_snd_se_reset
		call	_hflip_lut_generate
		les	bx, _resident
		cmp	es:[bx+resident_t.show_score_menu], 0
		jz	short loc_9E04
		call	@regist_menu$qv
		call	text_clear
		call	gaiji_restore
		call	@game_exit$qv
		pushd	0
		push	ds
		push	offset path	; "op"
		push	ds
		push	offset path	; "op"
		call	_execl
		add	sp, 0Ch

loc_9E04:
		les	bx, _resident
		mov	al, es:[bx+resident_t.RESIDENT_playchar_paletted][0]
		add	al, -1
		mov	_playchar[0], al
		mov	al, es:[bx+resident_t.RESIDENT_playchar_paletted][1]
		add	al, -1
		mov	_playchar[1], al
		cmp	es:[bx+resident_t.story_stage], 0
		jz	loc_9F85
		cmp	es:[bx+resident_t.game_mode], GM_STORY
		jnz	short loc_9E3F
		call	sub_9887
		mov	[bp+var_1], al
		cmp	[bp+var_1], 4
		jz	short loc_9E89
		cmp	[bp+var_1], 5
		jnz	short loc_9E3F
		call	sub_B972

loc_9E3F:
		call	_snd_load c,  offset aWin_m, ds, SND_LOAD_SONG
		call	@win_load$qv
		call	sub_978D
		kajacall	KAJA_SONG_STOP
		les	bx, _resident
		cmp	es:[bx+resident_t.game_mode], GM_STORY
		jnz	loc_9F58
		call	sub_9887
		mov	[bp+var_1], al
		cmp	[bp+var_1], 0
		jnz	short loc_9E7B

loc_9E75:
		call	sub_9A2C
		jmp	loc_9F1E
; ---------------------------------------------------------------------------

loc_9E7B:
		cmp	[bp+var_1], 3
		jz	short loc_9E89
		cmp	[bp+var_1], 4
		jnz	loc_9F38

loc_9E89:
		call	cdg_free_all
		freePISlotLarge	0
		mov	al, _playchar[0]
		mov	ah, 0
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	[bp+var_2], al
		cmp	[bp+var_2], 10
		jb	short loc_9EDC
		les	bx, off_E4B6
		mov	al, es:[bx+1]
		mov	dl, [bp+var_2]
		mov	dh, 0
		mov	bx, 10
		push	ax
		mov	ax, dx
		cwd
		idiv	bx
		pop	dx
		add	dl, al
		mov	bx, word ptr off_E4B6
		mov	es:[bx+1], dl
		mov	al, [bp+var_2]
		mov	ah, 0
		mov	bx, 10
		cwd
		idiv	bx
		mov	[bp+var_2], dl

loc_9EDC:
		les	bx, off_E4B6
		mov	al, [bp+var_2]
		add	es:[bx+2], al
		cmp	[bp+var_1], 4
		jnz	short loc_9EF1
		inc	byte ptr es:[bx+5]

loc_9EF1:
		graph_accesspage 0
		graph_showpage al
		call	graph_clear
		call	graph_show
		call	@cutscene_script_load$qnxc pascal, [off_E4B6]
		call	@cutscene_animate$qv
		call	@cutscene_script_free$qv
		call	sub_990C
		call	sub_9A2C
		call	gaiji_restore

loc_9F1E:
		call	@game_exit_from_mainl_to_main$qv
		pushd	0
		push	ds
		push	offset aMain	; "main"
		push	ds
		push	offset aMain	; "main"

loc_9F2E:
		call	_execl
		add	sp, 0Ch
		leave
		retf
; ---------------------------------------------------------------------------

loc_9F38:
		call	cdg_free_all
		freePISlotLarge	0
		call	@regist_menu$qv
		call	sub_9F8D
		or	ax, ax
		jnz	short loc_9F85
		call	sub_B92E
		jmp	short loc_9F69
; ---------------------------------------------------------------------------

loc_9F58:
		call	cdg_free_all
		freePISlotLarge	0

loc_9F69:
		call	text_clear
		call	gaiji_restore
		call	@game_exit$qv
		pushd	0
		push	ds
		push	offset path	; "op"
		push	ds
		push	offset path	; "op"
		jmp	short loc_9F2E
; ---------------------------------------------------------------------------

loc_9F85:
		call	sub_990C
		jmp	loc_9E75
; ---------------------------------------------------------------------------

@@ret:
		leave
		retf
_main		endp


sub_9F8D equ <@continue_menu$qv>

	@CUTSCENE_SCRIPT_LOAD$QNXC procdesc pascal near \
		fn:dword
	@cutscene_script_free$qv procdesc near
	@cutscene_animate$qv procdesc pascal near
CUTSCENE_TEXT ends

SCOREDAT_TEXT segment byte public 'CODE' use16
SCOREDAT_TEXT ends

REGIST_TEXT segment byte public 'CODE' use16
	@regist_menu$qv procdesc near
REGIST_TEXT ends

STAFF_TEXT segment byte public 'CODE' use16

sub_B92E equ <@gameover_bgm_play_and_fade$qv>
sub_B972 equ <@ending_staff_and_regist$qv>

	@gameover_bgm_play_and_fade$qv procdesc near
	@ending_staff_and_regist$qv procdesc near
	@FLAKE_PUT$QIII procdesc pascal near \
		left:word, top:word, cel:word
STAFF_TEXT ends

mainl_03_TEXT segment byte public 'CODE' use16
	extern CDG_UNPUT_FOR_UPWARDS_MOTION_E_8:proc
	extern CDG_PUT_DISSOLVE_E_8:proc

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BB51 equ <@staffroll_blue_plane_clear$qv>

	@staffroll_blue_plane_clear$qv procdesc near

FLAKE_W = 8
FLAKE_H = 8
FLAKE_CELS = 4

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@flakes_reset$qv procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BB80 equ <@flakes_spawn$qv>

	@flakes_spawn$qv procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BC29 equ <@flakes_update$qv>
	@flakes_update$qv procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BC6F equ <@flakes_render$qv>
	@flakes_render$qv procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BCA5 equ <@STAFFROLL_PHASE_DONE$QUII>
	@STAFFROLL_PHASE_DONE$QUII procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BCD5 equ <@staffroll_flakes_tick$qv>
	@staffroll_flakes_tick$qv procdesc near

; cdg_put_dissolve_e_8 is linked from th03/mainl/cdg_put_dissolve.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BDF4 equ <@STAFFROLL_CDG_SLIDE_UP$QI>
	@STAFFROLL_CDG_SLIDE_UP$QI procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BEC7 equ <@STAFFROLL_CDG_SLIDE_OUT$QI>
	@STAFFROLL_CDG_SLIDE_OUT$QI procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BF7E equ <@STAFFROLL_CDG_DISSOLVE_IN$QIII>
	@STAFFROLL_CDG_DISSOLVE_IN$QIII procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_BFB2 equ <@STAFFROLL_CDG_SLIDE_CYCLE$QIII>
	@STAFFROLL_CDG_SLIDE_CYCLE$QIII procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_C097 equ <@STAFFROLL_CDG_OVERLAY$QIII>
	@STAFFROLL_CDG_OVERLAY$QIII procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_C1FD equ <@STAFFROLL_CDG_SETUP_Y$QIII>
	@STAFFROLL_CDG_SETUP_Y$QIII procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_C288 equ <@staffroll_verdict_overlay_put$qv>
	@staffroll_verdict_overlay_put$qv procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_C40D equ <@staffroll_and_verdict_animate$qv>
	@staffroll_and_verdict_animate$qv procdesc near
mainl_03_TEXT	ends

; ===========================================================================

SHARED	segment	word public 'CODE' use16
include th02/snd/snd.inc
	extern _snd_determine_mode:proc
	extern _snd_delay_until_volume:proc
	extern _snd_load:proc
	extern VECTOR2:proc
	extern @game_exit$qv:proc
	extern CDG_PUT_8:proc
	extern CDG_PUT_HFLIP_8:proc
	extern @FRAME_DELAY$QI:proc
	extern @PI_PALETTE_APPLY$QI:proc
	extern @PI_PUT_8$QIII:proc
	extern @PI_PUT_INTERLACE_8$QIII:proc
	extern _snd_se_reset:proc
	extern SND_KAJA_INTERRUPT:proc
	extern @GAME_INIT_MAIN$QNXUC:proc
	extern CDG_LOAD_SINGLE:proc
	extern CDG_LOAD_SINGLE_NOALPHA:proc
	extern CDG_LOAD_ALL_NOALPHA:proc
	extern CDG_FREE:proc
	extern @game_exit_from_mainl_to_main$qv:proc
	extern @GRAPH_PUTSA_FX$QIIINXUC:proc
	extern SND_DELAY_UNTIL_MEASURE:proc
	extern @PI_LOAD$QINXC:proc
	extern @INPUT_MODE_INTERFACE$QV:proc
	extern CDG_PUT_NOALPHA_8:proc
	extern _hflip_lut_generate:proc
SHARED	ends

	.data

public _PIC_FN
_PIC_FN label word
		dw offset a00sl_cd2
		dw offset a02sl_cd2
		dw offset a04sl_cd2
		dw offset a06sl_cd2
		dw offset a08sl_cd2
		dw offset a10sl_cd2
		dw offset a12sl_cd2
		dw offset a14sl_cd2
		dw offset a16sl_cd2

public _WIN_MESSAGE_FN
_WIN_MESSAGE_FN label word
		dd a@00tx_txt		; "@00TX.TXT"
		dd a@01tx_txt		; "@01TX.TXT"
		dd a@02tx_txt		; "@02TX.TXT"
		dd a@03tx_txt		; "@03TX.TXT"
		dd a@04tx_txt		; "@04TX.TXT"
		dd a@05tx_txt		; "@05TX.TXT"
		dd a@06tx_txt		; "@06TX.TXT"
		dd a@07tx_txt		; "@07TX.TXT"
		dd a@08tx_txt		; "@08TX.TXT"

off_E4B6	dd a@00dm0_txt
					; "@00DM0.TXT"
public _CHAR_TITLE, _CHAR_NAME
_CHAR_TITLE label dword
CHAR_TITLE		dd TITLE_REIMU		; "   夢と伝統を保守する巫女   "
_CHAR_NAME label dword
CHAR_NAME		dd NAME_REIMU		; "   博麗　靈夢"
		dd TITLE_MIMA		; " 久遠の夢に運命を任せる精神 "
		dd NAME_MIMA		; "	魅 魔"
		dd TITLE_MARISA	; "   魔法と紅夢からなる存在   "
		dd NAME_MARISA		; "  霧雨　魔理沙 "
		dd TITLE_ELLEN		; "はたらきもので恋を夢見る魔女"
		dd NAME_ELLEN		; "　　エレン"
		dd TITLE_KOTOHIME		; "	弾幕に美を夢みる姫     "
		dd NAME_KOTOHIME		; "    小兎姫"
		dd TITLE_KANA			; "	夢を失った少女騒霊     "
		dd NAME_KANA	; "カナ・アナベラル"
		dd TITLE_RIKAKO		; "  　　　夢を探す科学	       "
		dd NAME_RIKAKO	; "　朝倉　理香子"
		dd TITLE_CHIYURI		; "　  時をかける夢幻の住人    "
		dd NAME_CHIYURI	; " 北白河　ちゆり"
		dd TITLE_YUMEMI	; "　  　　　夢幻伝説　　　    "
		dd NAME_YUMEMI		; " 　岡崎　夢美"
public _stage_number_cdg_fn, _stage_splash_bg_fn
_stage_number_cdg_fn	dw offset _stage_number_cdg_fn_s
_stage_splash_bg_fn	dw offset _stage_splash_bg_pi_fn
public _SHOT_FN
_SHOT_FN db '0016.pi', 0, 0, 0, 0, 0
SHOT_FN_SIZE = ($ - _SHOT_FN)
a00sl_cd2	db '00sl.cd2',0
a02sl_cd2	db '02sl.cd2',0
a04sl_cd2	db '04sl.cd2',0
a06sl_cd2	db '06sl.cd2',0
a08sl_cd2	db '08sl.cd2',0
a10sl_cd2	db '10sl.cd2',0
a12sl_cd2	db '12sl.cd2',0
a14sl_cd2	db '14sl.cd2',0
a16sl_cd2	db '16sl.cd2',0
a@00tx_txt	db '@00TX.TXT',0
a@01tx_txt	db '@01TX.TXT',0
a@02tx_txt	db '@02TX.TXT',0
a@03tx_txt	db '@03TX.TXT',0
a@04tx_txt	db '@04TX.TXT',0
a@05tx_txt	db '@05TX.TXT',0
a@06tx_txt	db '@06TX.TXT',0
a@07tx_txt	db '@07TX.TXT',0
a@08tx_txt	db '@08TX.TXT',0
a@00dm0_txt	db '@00DM0.TXT',0
TITLE_REIMU		db '   夢と伝統を保守する巫女   ',0
NAME_REIMU	db '   博麗　靈夢',0
TITLE_MIMA	db ' 久遠の夢に運命を任せる精神 ',0
NAME_MIMA		db '     魅 魔',0
TITLE_MARISA	db '   魔法と紅夢からなる存在   ',0
NAME_MARISA	db '  霧雨　魔理沙 ',0
TITLE_ELLEN	db 'はたらきもので恋を夢見る魔女',0
NAME_ELLEN	db '　　エレン',0
TITLE_KOTOHIME		db '     弾幕に美を夢みる姫     ',0
NAME_KOTOHIME		db '    小兎姫',0
TITLE_KANA		db '     夢を失った少女騒霊     ',0
NAME_KANA	db 'カナ・アナベラル',0
TITLE_RIKAKO	db '  　　　夢を探す科学        ',0
NAME_RIKAKO	db '　朝倉　理香子',0
TITLE_CHIYURI		db '　  時をかける夢幻の住人    ',0
NAME_CHIYURI	db ' 北白河　ちゆり',0
TITLE_YUMEMI	db '　  　　　夢幻伝説　　　    ',0
NAME_YUMEMI	db ' 　岡崎　夢美',0
include th03/formats/cfg_lres[data].asm
public _logo0_rgb, _logo_cd2, _logo5_cdg, _logo1_rgb
_logo0_rgb	db 'logo0.rgb',0
_logo_cd2 	db 'logo.cd2',0
_logo5_cdg	db 'logo5.cdg',0
_logo1_rgb	db 'logo1.rgb',0
public _stage_splash_base_pi_fn
_stage_number_cdg_fn_s	db 'st.cd2',0
_stage_splash_bg_pi_fn	db 'stnx1.pi',0
_stage_splash_base_pi_fn	db 'stnx0.pi',0
public _PLAYCHAR_BGM_FN
public _stage_splash_dec_bgm_fn, _stage_splash_enemy_center_pi_fn
public _stage_splash_enemy00_pi_fn, _stage_splash_enemy01_pi_fn
public _stage_splash_enemy02_pi_fn, _stage_splash_enemy03_pi_fn
public _stage_splash_enemy04_pi_fn, _stage_splash_yume_efc_fn
_PLAYCHAR_BGM_FN	db '00mm.m',0
_stage_splash_dec_bgm_fn label byte
aDec_m		db 'dec.m',0
_stage_splash_enemy_center_pi_fn label byte
aEn2_pi		db 'EN2.pi',0
_stage_splash_enemy00_pi_fn label byte
aEnemy00_pi	db 'ENEMY00.pi',0
_stage_splash_enemy01_pi_fn label byte
aEnemy01_pi	db 'ENEMY01.pi',0
_stage_splash_enemy02_pi_fn label byte
aEnemy02_pi	db 'ENEMY02.pi',0
_stage_splash_enemy03_pi_fn label byte
aEnemy03_pi	db 'ENEMY03.pi',0
_stage_splash_enemy04_pi_fn label byte
aEnemy04_pi	db 'ENEMY04.pi',0
_stage_splash_yume_efc_fn label byte
aYume_efc	db 'YUME.EFC',0
aCOul		db '夢時空1.dat',0
aMikoft_bft	db 'MIKOFT.bft',0
; char path[]
path		db 'op',0
aWin_m		db 'win.m',0
; char aMain[]
aMain		db 'main',0
include libs/master.lib/atan8[data].asm
include libs/master.lib/bfnt_id[data].asm
include libs/master.lib/clip[data].asm
include libs/master.lib/edges[data].asm
include libs/master.lib/fil[data].asm
include libs/master.lib/dos_ropen[data].asm
include libs/master.lib/gaiji_backup[data].asm
include libs/master.lib/gaiji_entry_bfnt[data].asm
include libs/master.lib/grp[data].asm
include libs/master.lib/js[data].asm
include libs/master.lib/pal[data].asm
include libs/master.lib/pf[data].asm
include libs/master.lib/rand[data].asm
include libs/master.lib/sin8[data].asm
include libs/master.lib/tx[data].asm
include libs/master.lib/vs[data].asm
include libs/master.lib/wordmask[data].asm
include libs/master.lib/mem[data].asm
include libs/master.lib/super_entry_bfnt[data].asm
include libs/master.lib/superpa[data].asm
public _snd_active
_snd_active	db 0
		db 0
include libs/master.lib/respal_exist[data].asm
include th03/snd/se_state[data].asm
include th02/formats/pfopen[data].asm
include th03/formats/cdg[data].asm
include th03/snd/se_priority[data].asm
public _continue_count_str, _continue_gameover_bg_pi_fn
_continue_count_str label byte
a0		db  '0',0
_continue_gameover_bg_pi_fn label byte
aOver_pi	db 'over.pi',0
include th03/formats/pi_put_masked[data].asm
public _CUTSCENE_KANJI
_CUTSCENE_KANJI	db  '  ', 0
	even
public _REGIST_PLAYCHARS
_REGIST_PLAYCHARS label dword
		dd aNoEntry		; "  No	Entry! "
		dd aB@b@sCB@b@		; "　　靈夢　　"
		dd aB@b@cgcvb@b@	; "　　魅魔　　"
		dd aB@cvcanB@		; " 　魔理沙　 "
		dd aB@gggmgub@		; " 　エレン　 "
		dd aB@pmuexpb@		; " 　小兎姫　 "
		dd aB@Gjgi		; " 　 カナ    "
		dd aB@canboq		; " 　理香子   "
		dd aB@vVfvsb@		; " 　ちゆり　 "
		dd aB@CF		; " 　 夢美　  "
public _REGI_PLAYCHAR
_REGI_PLAYCHAR label byte
	db REGI_R, REGI_E, REGI_I, REGI_M, REGI_U, regi_sp, regi_sp, regi_sp
	db REGI_M, REGI_I, REGI_M, REGI_A, regi_sp, regi_sp, regi_sp, regi_sp
	db REGI_M, REGI_A, REGI_R, REGI_I, REGI_S, REGI_A, regi_sp, regi_sp
	db REGI_E, REGI_L, REGI_E, REGI_N, regi_sp, regi_sp, regi_sp, regi_sp
	db REGI_K, REGI_O, REGI_T, REGI_O, REGI_H, REGI_I, REGI_M, REGI_E
	db REGI_K, REGI_A, REGI_N, REGI_A, regi_sp, regi_sp, regi_sp, regi_sp
	db REGI_R, REGI_I, REGI_K, REGI_A, REGI_K, REGI_O, regi_sp, regi_sp
	db REGI_C, REGI_H, REGI_I, REGI_Y, REGI_U, REGI_R, REGI_I, regi_sp
	db REGI_Y, REGI_U, REGI_M, REGI_E, REGI_M, REGI_I, regi_sp, regi_sp
public _SCOREDAT_FN_PTR
_SCOREDAT_FN_PTR	dw offset aYume_nem
public _rank_image_fn, _REGIST_INPUT_HOLD_INIT
_rank_image_fn	dw offset aRft0_cdg
_REGIST_INPUT_HOLD_INIT	dw 4 dup(0)
aNoEntry	db '  No Entry! ',0
aB@b@sCB@b@	db '　　靈夢　　',0
aB@b@cgcvb@b@	db '　　魅魔　　',0
aB@cvcanB@	db ' 　魔理沙　 ',0
aB@gggmgub@	db ' 　エレン　 ',0
aB@pmuexpb@	db ' 　小兎姫　 ',0
aB@Gjgi		db ' 　 カナ    ',0
aB@canboq	db ' 　理香子   ',0
aB@vVfvsb@	db ' 　ちゆり　 ',0
aB@CF		db ' 　 夢美　  ',0
aYume_nem	db 'YUME.NEM',0
aRft0_cdg	db 'rft0.cdg',0
public _regib_pi, _regi2_bft, _regi1_bft, _score_m, _conti_pi, _conti_cd2
public _GAMEOVER_BG_FN, _gameover_bgm_fn, _ending_script_fn
public _extra_ending_script_fn, _binary_op_fn
_regib_pi 	db 'regib.pi',0
_regi2_bft	db 'regi2.bft',0
_regi1_bft	db 'regi1.bft',0
_score_m	db 'score.m',0
_conti_pi	db 'conti.pi',0
_conti_cd2	db 'conti.cd2',0
_GAMEOVER_BG_FN	db 'over.pi',0
_gameover_bgm_fn label byte
aOver_m		db 'over.m',0
		db 0
_ending_script_fn label dword
off_EE4E	dd a@00ed_txt
					; "@00ED.TXT"
include th03/sprites/flake.asp
include th03/formats/cdg_put_dissolve[data].asm

public _VERDICT_PLAYCHARS, _VERDICT_RANKS, _VERDICT_NUMBERS, _VERDICT_POINT
_VERDICT_PLAYCHARS label dword
aVERDICT_PLAYCHARS label dword
		dd aFocab@sC_0		; "   博麗　靈夢"
		dd aCgCv_0		; "	魅 魔"
		dd aCIjb@cvcan_0	; "  霧雨　魔理沙 "
		dd aB@b@gggmgu_0	; "　　エレン"
		dd aPmuexp_0		; "    小兎姫"
		dd aGjgibegagigx_0	; "カナ・アナベラル"
		dd aB@tisqb@canb_0	; "　朝倉　理香子"
		dd aCkftiB@vVfvs_0	; " 北白河　ちゆり"
		dd aB@iknsb@cF_0	; " 　岡崎　夢美"
_VERDICT_RANKS label dword
aVERDICT_RANKS label dword
		dd aVdvbvuvs		; "   Ｅａｓｙ"
		dd aVmvpvtvnvbvm	; " Ｎｏｒｍａｌ"
		dd aVgvbvtvd		; "   Ｈａｒｄ"
		dd aVkvxvovbvfvivg	; "Ｌｕｎａｔｉｃ"
_VERDICT_NUMBERS label dword
aVERDICT_NUMBERS label dword
		dd aVo			; "０"
		dd aVp			; "１"
		dd aVq			; "２"
		dd aVr			; "３"
		dd aVs			; "４"
		dd aVt			; "５"
		dd aVu			; "６"
		dd aVv			; "７"
		dd aVw			; "８"
		dd aVx			; "９"
a@00ed_txt	db '@00ED.TXT',0
_extra_ending_script_fn label byte
a@99ed_txt	db '@99ED.TXT',0
; char aOp_0[]
_binary_op_fn label byte
aOp_0		db 'op',0
aFocab@sC_0	db '   博麗　靈夢',0
aCgCv_0		db '     魅 魔',0
aCIjb@cvcan_0	db '  霧雨　魔理沙 ',0
aB@b@gggmgu_0	db '　　エレン',0
aPmuexp_0	db '    小兎姫',0
aGjgibegagigx_0	db 'カナ・アナベラル',0
aB@tisqb@canb_0	db '　朝倉　理香子',0
aCkftiB@vVfvs_0	db ' 北白河　ちゆり',0
aB@iknsb@cF_0	db ' 　岡崎　夢美',0
aVdvbvuvs	db '   Ｅａｓｙ',0
aVmvpvtvnvbvm	db ' Ｎｏｒｍａｌ',0
aVgvbvtvd	db '   Ｈａｒｄ',0
aVkvxvovbvfvivg	db 'Ｌｕｎａｔｉｃ',0
aVo		db '０',0
aVp		db '１',0
aVq		db '２',0
aVr		db '３',0
aVs		db '４',0
aVt		db '５',0
aVu		db '６',0
aVv		db '７',0
aVw		db '８',0
aVx		db '９',0
_VERDICT_POINT label byte
aU_		db '点',0
public _staffroll_bgm_fn, _staffroll_bg_palette_fn
public _staffroll_cdg_fn_0, _staffroll_cdg_fn_1, _staffroll_cdg_fn_2
public _staffroll_cdg_fn_3, _staffroll_cdg_fn_4, _staffroll_cdg_fn_5
public _staffroll_cdg_fn_6, _staffroll_cdg_fn_7, _staffroll_cdg_fn_8
public _staffroll_cdg_fn_9, _staffroll_cdg_fn_10, _staffroll_cdg_fn_11
_staffroll_bgm_fn label byte
aEd_m		db 'ed.m',0
_staffroll_bg_palette_fn label byte
aEdbk1_rgb	db 'edbk1.rgb',0
_staffroll_cdg_fn_0 label byte
aStf1_cdg	db 'stf1.cdg',0
_staffroll_cdg_fn_1 label byte
aStf11_cdg	db 'stf11.cdg',0
_staffroll_cdg_fn_2 label byte
aStf3_cdg	db 'stf3.cdg',0
_staffroll_cdg_fn_3 label byte
aStf4_cdg	db 'stf4.cdg',0
_staffroll_cdg_fn_4 label byte
aStf5_cdg	db 'stf5.cdg',0
_staffroll_cdg_fn_5 label byte
aStf6_cdg	db 'stf6.cdg',0
_staffroll_cdg_fn_6 label byte
aStf7_cdg	db 'stf7.cdg',0
_staffroll_cdg_fn_7 label byte
aStf8_cdg	db 'stf8.cdg',0
_staffroll_cdg_fn_8 label byte
aStf9_cdg	db 'stf9.cdg',0
_staffroll_cdg_fn_9 label byte
aStf10_cdg	db 'stf10.cdg',0
_staffroll_cdg_fn_10 label byte
aStf2_cdg	db 'stf2.cdg',0
_staffroll_cdg_fn_11 label byte
aStf12_cdg	db 'stf12.cdg',0

	.data?

	extern _playchar:byte:PLAYCHAR_COUNT
	extern _do_not_show_stage_number:byte

include libs/master.lib/clip[bss].asm
include libs/master.lib/fil[bss].asm
include libs/master.lib/js[bss].asm
include libs/master.lib/pal[bss].asm
include libs/master.lib/vs[bss].asm
include libs/master.lib/vsync[bss].asm
include libs/master.lib/mem[bss].asm
include libs/master.lib/superpa[bss].asm
include th01/hardware/vram_planes[bss].asm
include th02/snd/snd[bss].asm
include th02/snd/load[bss].asm
include libs/master.lib/pfint21[bss].asm
include th03/hardware/input[bss].asm
include th03/formats/cdg[bss].asm
include th02/formats/pi_slots[bss].asm
include th03/formats/hfliplut[bss].asm
include th03/cutscene/cutscene[bss].asm
public _resident
_resident	dd ?
public _hi
_hi	scoredat_section_t <?>
include th03/hiscore/regist[bss].asm
		db 2 dup(?)
_staffroll_flake_count label byte
byte_106B0	db ?
	evendata

flake_t struc
	FLAKE_alive   	db ?
	              	db ?
	FLAKE_left    	dw ?
	FLAKE_top     	dw ?
	FLAKE_velocity	Point <?>
	FLAKE_cel     	dw ?
		db 4 dup(?)
flake_t ends

FLAKE_COUNT = 80

public _flakes, _page_back, _stf_center_y_on_page, _score
public _continues_used, _rank, _skill, _staffroll_verdict_playchar
public _staffroll_flake_count, _staffroll_frame
public _staffroll_cdg_put_alpha, _staffroll_flake_reset_pending
public _staffroll_cdg_speed, _staffroll_cdg_frames, _staffroll_cdg_y_stop
public _staffroll_cdg_y_start_off, _staffroll_cdg_overlay_y
public _staffroll_cdg_aux_slot, _staffroll_cdg_alpha
_flakes	flake_t FLAKE_COUNT dup(<?>)

_staffroll_frame label word
word_10BB2	dw ?
_page_back	db ?
_staffroll_cdg_put_alpha label byte
byte_10BB5	db ?
_staffroll_flake_reset_pending label byte
byte_10BB6	db ?
		db 5 dup(?)
_staffroll_cdg_speed label word
word_10BBC	dw ?
_staffroll_cdg_frames label word
word_10BBE	dw ?
_staffroll_cdg_y_stop label word
word_10BC0	dw ?
_staffroll_cdg_overlay_y label word
word_10BC2	dw ?
_staffroll_cdg_y_start_off label word
word_10BC4	dw ?
_staffroll_cdg_aux_slot label byte
byte_10BC6	db ?
_staffroll_cdg_alpha label byte
byte_10BC7	db ?
_stf_center_y_on_page dw 2 dup(?)
_continues_used label byte
continues_used label byte
_score db (1 + SCORE_DIGITS) dup(?)
	evendata
_rank	db ?
_staffroll_verdict_playchar label byte
playchar_10BD7	db ?
_skill	db ?
		db    ?	;

		end
