;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	43EE91A800F1F0FE35A87149C90B037D

; File Name   :	th03/MAIN.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-26470h Loaded length: 1E6E2h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'M'

include ReC98.inc
include th02/gaiji/boldfont.inc
include th03/arg_bx.inc
include th03/th03.inc
include th03/main/playfld.inc
include th03/main/collmap.inc
include th03/sprites/main_s16.inc
include th03/sprite16.inc
include libs/sprite16/sprite16.inc
include th03/main/support_format[decl].inc

GBA_GAUGE_LEVEL_MIN = 1
GBA_GAUGE_LEVEL_MAX = 16
GBA_BOSS_LEVEL_MAX = 16

	extern _execl:proc
	_collmap_reset procdesc near
	@randring_fill$qv procdesc near
	extern gba_boss_update_reimu:proc
	extern gba_boss_update_marisa:proc
	extern gba_boss_update_mima:proc
	extern gba_boss_update_yumemi:proc
	extern gba_boss_update_ellen:proc
	extern gba_boss_update_kotohime:proc

; Support/resident BSS prefix moved to th03/main/support_resident_bss.asm.
	extern Palettes:byte:48
	extern trapez_a:word:4
	extern trapez_b:word:4
	extern file_Pointer:dword
	extern file_Buffer:dword
	extern file_BufferPos:dword
	extern file_BufPtr:word
	extern file_InReadBuf:word
	extern file_Eof:word
	extern file_ErrorStat:word
	extern gc_circl_cx_:word
	extern gc_circl_cy_:word
	extern ylen:word
	extern js_stat:word:2
	extern vsync_Count1:word
	extern vsync_Count2:word
	extern vsync_OldVect:dword
	extern vsync_delay_count:word
	extern mem_OutSeg:word
	extern mem_TopHeap:word
	extern mem_FirstHole:word
	extern mem_EndMark:word
	extern super_patdata:word:MAXPAT
	extern super_patsize:word:MAXPAT
	extern _VRAM_PLANE_B:dword
	extern _VRAM_PLANE_R:dword
	extern _VRAM_PLANE_G:dword
	extern _VRAM_PLANE_E:dword
	extern _snd_fm_possible:byte
	extern _snd_midi_active:byte
	extern _snd_interrupt_if_midi:byte
	extern _snd_midi_possible:byte
	extern parfilename:byte:128
	extern pfint21_pf:word
	extern pfint21_handle:word
	extern pfint21_entries:word
	extern _input_mp_p1:word
	extern _input_mp_p2:word
	extern _input_sp:word
	extern _pi_buffers:dword:6
	extern _pi_headers:byte:(size PiHeader * 6)
	extern _hflip_lut:byte:256
	extern _mrs_images:dword:8
	extern _sprite16_clip_left:word
	extern _sprite16_clip_right:word
	extern _sprite16_put_h:word
	extern _sprite16_put_w:byte
	extern _playfield_clip_negative_radius:word:2
	extern _resident:dword
main_01 group PLAYFLD_TEXT, CFG_LRES_TEXT, HITCIRC_TEXT, HUD_STAT_TEXT, PLAYER_M_TEXT, main_010_TEXT, P_SHOT_TEXT
main_04 group main_04_TEXT, COLLMAP_TEXT, ENEMY_PUT, E_EXPL_TEXT, PELLET_PUT, E_ENEMY_TEXT, HITBOX_TEXT, P_COMBO_TEXT, P_GAUGE_TEXT, ENEMY_2_TEXT, BULLET_TEXT, E_FIREB_TEXT
main_06 group P_EXATT_TEXT, main_06_TEXT

; ===========================================================================

; Segment type:	Pure code
_TEXT		segment	word public 'CODE' use16
		assume cs:_TEXT
		assume es:nothing, ds:_DATA, fs:nothing, gs:nothing

include libs/master.lib/bfnt_entry_pat.asm
include libs/master.lib/bfnt_extend_header_skip.asm
include libs/master.lib/bfnt_header_read.asm
include libs/master.lib/bfnt_header_analysis.asm
include libs/master.lib/bcloser.asm
include libs/master.lib/bfill.asm
include libs/master.lib/bfnt_palette_set.asm
include libs/master.lib/bgetc.asm
include libs/master.lib/palette_black_out.asm
include libs/master.lib/bopenr.asm
include libs/master.lib/bread.asm
include libs/master.lib/bseek.asm
include libs/master.lib/bseek_.asm
include libs/master.lib/cutline.asm
include libs/master.lib/dos_keyclear.asm
include libs/master.lib/dos_setvect.asm
include libs/master.lib/egc.asm
include libs/master.lib/file_close.asm
include libs/master.lib/file_read.asm
include libs/master.lib/file_ropen.asm
include libs/master.lib/dos_close.asm
include libs/master.lib/dos_ropen.asm
include libs/master.lib/grcg_boxfill.asm
include libs/master.lib/grcg_circle.asm
include libs/master.lib/grcg_circle_x.asm
include libs/master.lib/grc_setclip.asm
include libs/master.lib/grcg_fill.asm
include libs/master.lib/grcg_hline.asm
include libs/master.lib/grcg_line.asm
include libs/master.lib/grcg_setcolor.asm
include libs/master.lib/grcg_settile_1line.asm
include libs/master.lib/grcg_triangle.asm
include libs/master.lib/grcg_vline.asm
include libs/master.lib/grcg_trapezoid.asm
include libs/master.lib/gaiji_backup.asm
include libs/master.lib/gaiji_entry_bfnt.asm
include libs/master.lib/gaiji_putca.asm
include libs/master.lib/gaiji_putsa.asm
include libs/master.lib/gaiji_read.asm
include libs/master.lib/gaiji_write.asm
include libs/master.lib/graph_200line.asm
include libs/master.lib/graph_400line.asm
include libs/master.lib/graph_clear.asm
include libs/master.lib/graph_copy_page.asm
include libs/master.lib/graph_extmode.asm
include libs/master.lib/graph_hide.asm
include libs/master.lib/graph_pi_free.asm
include libs/master.lib/graph_pi_load_pack.asm
include libs/master.lib/iatan2.asm
include libs/master.lib/js_end.asm
include libs/master.lib/make_linework.asm
include libs/master.lib/palette_show.asm
include libs/master.lib/pfclose.asm
include libs/master.lib/pfgetc.asm
include libs/master.lib/pfread.asm
include libs/master.lib/pfrewind.asm
include libs/master.lib/pfseek.asm
include libs/master.lib/random.asm
include libs/master.lib/smem_release.asm
include libs/master.lib/smem_wget.asm
include libs/master.lib/soundio.asm
include libs/master.lib/text_boxfilla.asm
include libs/master.lib/text_clear.asm
include libs/master.lib/text_fillca.asm
include libs/master.lib/text_puts.asm
include libs/master.lib/text_putsa.asm
include libs/master.lib/vsync.asm
include libs/master.lib/vsync_wait.asm
include libs/master.lib/hmem_lallocate.asm
include libs/master.lib/mem_assign_dos.asm
include libs/master.lib/mem_assign.asm
include libs/master.lib/memheap.asm
include libs/master.lib/mem_unassign.asm
include libs/master.lib/super_free.asm
include libs/master.lib/super_entry_pat.asm
include libs/master.lib/super_entry_at.asm
include libs/master.lib/super_entry_bfnt.asm
include libs/master.lib/super_cancel_pat.asm
include libs/master.lib/super_put.asm
include libs/master.lib/respal_exist.asm
include libs/master.lib/respal_get_palettes.asm
include libs/master.lib/pfint21.asm
		db 0
include libs/master.lib/js_start.asm
include libs/master.lib/js_sense.asm
		db 0
include th03/hardware/sprite16_copy.asm
include libs/master.lib/draw_trapezoid.asm
include th03/formats/pfopen.asm
include libs/master.lib/pf_str_ieq.asm
_TEXT		ends

; ===========================================================================

; Segment type:	Pure code
PLAYFLD_TEXT segment byte public 'CODE' use16
		assume cs:main_01
		;org 5
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; int __cdecl main(int argc, const char	**argv,	const char **envp)
extrn _main_entry:far
alias <_main> = <_main_entry>


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_9778 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_demo_round_update procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_round_mode_update_none procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ROUND_STARTUP procdesc near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_9EBF procdesc near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_A21F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_A289 equ <@RESIDENT_SCORE_LAST_UPDATE$QI>
	@RESIDENT_SCORE_LAST_UPDATE$QI procdesc near

	extern @PLAYFIELD_FG_X_TO_SCREEN$QII:proc
	extern @SCREEN_X_TO_PLAYFIELD$QII:proc
	extern @PLAYFIELD_CLIP$Q20%SUBPIXELBASE$TI$TI%T1:proc
PLAYFLD_TEXT	ends

CFG_LRES_TEXT	segment	byte public 'CODE' use16
	@cfg_load_resident_ptr$qv procdesc near
CFG_LRES_TEXT	ends

HITCIRC_TEXT	segment	word public 'CODE' use16


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_REIMU procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_MIMA procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_MARISA procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_ELLEN procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_KOTOHIME procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_KANA procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
SET_CALLBACKS_RIKAKO procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_CHIYURI procdesc pascal near \
		pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SET_CALLBACKS_YUMEMI procdesc pascal near \
		pid:word

	SUB_A378 procdesc far
	SUB_A38E procdesc far
	SUB_A3A8 procdesc far
	_SUB_A3D2 procdesc far
	SUB_A4A1 procdesc near
	SUB_A4C3 procdesc near


; =============== S U B	R O U T	I N E =======================================

	PLAYFIELD_ROWS_FILL_288 procdesc near

; =============== S U B	R O U T	I N E =======================================

	PLAYFIELD_BOTTOM_ROWS_FILL_288 procdesc near


; =============== S U B	R O U T	I N E =======================================


	_sub_B39E procdesc far



; =============== S U B	R O U T	I N E =======================================


	SUB_B3A2 procdesc near

; ---------------------------------------------------------------------------

; =============== S U B	R O U T	I N E =======================================


	SUB_B3F6 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@GAMEEXECL$QNXC procdesc pascal far \
		binary_fn:dword



; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_B4A3 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

TRAPEZOID_HMASK_ODD = 05555h

	SUB_B4A8 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_B60A procdesc near

	extern @HITCIRCLES_ENEMY_ADD$QIII:proc
	extern @HITCIRCLES_PLAYER_ADD$QIII:proc
	@hitcircles_update$qv procdesc near
	@hitcircles_render$qv procdesc near
HITCIRC_TEXT ends

HUD_STAT_TEXT segment byte public 'CODE' use16
	extern @hud_wipe$qv:proc
	extern @HUD_STATIC_HALFHEARTS_PUT$QUC:proc
	extern @HUD_STATIC_BOMBS_PUT$QUC:proc
	@HUD_STATIC_ROUNDS_WON_PUT$QUC procdesc pascal near \
		pid:word
	@hud_static_story_lives_put$qv procdesc near
	extern @HUD_STATIC_GAUGE_LEVELS_PUT$QI:proc
	extern @hud_static_put$qv:proc
HUD_STAT_TEXT ends

PLAYER_M_TEXT	segment	byte public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_BB12 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_BDC2 procdesc pascal near \
	 slot:word, patnum:word, y:word, x:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_BE2A procdesc pascal near \
	 x:word, y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_BE5D procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	SUB_C0D8 procdesc pascal near \
		player:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	SUB_C1E6 procdesc pascal near \
		angle_for_cos:word, angle_for_sin:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	SUB_C248 procdesc pascal near \
		player:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_C2F9 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_C370 procdesc pascal near \
		arg_0:word, arg_2:word, arg_4:word

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_C433 procdesc pascal near \
		player:word

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	SUB_C54A procdesc pascal near \
		player:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	SUB_C568 procdesc pascal near \
		player:word

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_C7A5 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_sub_C830 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_sub_C8C4 procdesc near

WARNING_FLASH_RED_FRAMES = 30

WF_NONE = 0
WF_PORTRAIT = 1
WF_FLASH_WHITE = 2
WF_FLASH_RED = 3
WF_FLASH_RED_END = (WF_FLASH_RED + WARNING_FLASH_RED_FRAMES)

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_C9FE procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CA3C procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame




; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CB81 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CDBD procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CE0C procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CE5B procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CEB2 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_CEE0 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_D031 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D05D procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D092 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_D0FA procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D135 procdesc far
; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D1E7 procdesc far
; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D2E8 procdesc far

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D340 procdesc far

; =============== S U B	R O U T	I N E =======================================

	SUB_D3F9 procdesc far


; =============== S U B	R O U T	I N E =======================================


	SUB_D50E procdesc near


; =============== S U B	R O U T	I N E =======================================

	_sub_D52E procdesc near

; ---------------------------------------------------------------------------

; =============== S U B	R O U T	I N E =======================================

	SUB_D5A2 procdesc far

	@SCORE_ADD$QUIUC procdesc pascal far \
		score:word, pid:byte

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@HUD_DYNAMIC_5_DIGIT_POINTS_PUT$QIIUIUC procdesc pascal far \
		left:word, top:word, points:word, col:byte

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_D668 procdesc pascal far \
		left:word, top:word, points:word, col:byte


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SCORE_CONTINUES_USED_DIGIT_UPDAT procdesc pascal far \
		credits_left_arg:byte

MOVE_INVALID = 0
MOVE_VALID = 1
MOVE_NOINPUT = 2

	@PLAYER_POS_UPDATE_AND_CLAMP$QR7SPPOINT procdesc pascal near \
		center:word
	@PLAYER_MOVE$QUI procdesc pascal near \
		input:word
PLAYER_M_TEXT	ends

main_010_TEXT	segment	word public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	HYPER_STANDBY procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	HYPER_REIMU procdesc pascal near

	HYPER_MIMA procdesc pascal near

	HYPER_MARISA procdesc pascal near

	HYPER_ELLEN procdesc pascal near

	HYPER_KOTOHIME procdesc pascal near

	HYPER_CHIYURI procdesc pascal near

	HYPER_YUMEMI procdesc pascal near

	HYPER_KANA procdesc pascal near

	HYPER_RIKAKO procdesc pascal near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame



; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	PLAYER_UPDATE procdesc pascal near \
		input:word, player:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	PLAYER_RENDER procdesc pascal near \
		player:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	PLAYER_OVERLAY_RENDER procdesc pascal near \
		player:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	PLAYER_KNOCKBACK_UPDATE procdesc pascal near \
		player:word


	PLAYER_BOMB procdesc pascal near \
		player:word

	@PLAYER_HITTEST$QI procdesc pascal near \
		hitbox_size:word
	@PLAYERS_HIT_DAMAGE_UPDATE$QR14PLAYER_STUFF_T procdesc pascal near \
		player_hit:word
	@story_skill_decrement$qv procdesc near
main_010_TEXT	ends

P_SHOT_TEXT segment byte public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_E266 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_E313 procdesc near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_E35B procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_E3F2 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	@shots_add$qv procdesc near
	@shots_update$qv procdesc near
	@shots_render$qv procdesc near
P_SHOT_TEXT ends

; ===========================================================================

SHARED	segment	word public 'CODE' use16
	extern _snd_determine_mode:proc
	extern VECTOR2:proc
	extern VECTOR2_BETWEEN_PLUS:proc
	extern @game_exit$qv:proc
	extern @polar$qiii:proc
	extern @FRAME_DELAY$QI:proc
	extern @input_reset_sense_key_held$qv:proc
	extern _snd_se_reset:proc
	extern SND_SE_PLAY:proc
	extern _snd_se_update:proc
	extern SND_KAJA_INTERRUPT:proc
	extern @GAME_INIT_MAIN$QNXUC:proc
	extern @INPUT_MODE_KEY_VS_KEY$QV:proc
	extern @INPUT_MODE_JOY_VS_KEY$QV:proc
	extern @INPUT_MODE_KEY_VS_JOY$QV:proc
	extern @INPUT_MODE_1P_VS_CPU$QV:proc
	extern @INPUT_MODE_CPU_VS_1P$QV:proc
	extern @INPUT_MODE_CPU_VS_CPU$QV:proc
	extern @INPUT_MODE_ATTRACT$QV:proc
	extern _hflip_lut_generate:proc
	extern @MRS_LOAD$QINXC:proc
	extern @MRS_FREE$QI:proc
	extern @MRS_PUT_8$QIUII:proc
	extern @MRS_PUT_NOALPHA_8$QIUIIUC:proc
	extern @MRS_HFLIP$QI:proc
	SPRITE16_SPRITES_COMMIT procdesc pascal far
	SPRITE16_PUT procdesc pascal far \
		left:word, screen_top:word, sprite_offset:word
	SPRITE16_PUTX procdesc pascal far \
		left:word, screen_top:word, sprite_offset:word, func:word
	SPRITE16_PUT_NOCLIP procdesc pascal far \
		left:word, screen_top:word, sprite_offset:word
SHARED	ends

; ===========================================================================

; Segment type:	Pure code
main_03_TEXT	segment	byte public 'CODE' use16
		assume cs:main_03_TEXT
		;org 0Ah
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

	sub_F1FA procdesc near
	sub_F356 procdesc near
	sub_F3A9 procdesc near
	sub_F402 procdesc near
	sub_F4B4 procdesc far

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_F512 procdesc near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_F52D procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_F58C procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_F5AF procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_F5FE procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_F685 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_F72D procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_F7BD procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
; dispatcher/table extracted to th03/main/main_03_dispatch.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_F9A6 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_FA71 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_MARISA procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_FB46 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_FB95 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_FC6B procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_FD71 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_FE2B procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
; dispatcher/table extracted to th03/main/main_03_mima_update.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_10053 procdesc near

	MIMA_10184 procdesc near


	GBA_BOSS_RENDER_MIMA procdesc far


	YUMEMI_102C8 procdesc far


	YUMEMI_10324 procdesc near


	YUMEMI_10405 procdesc near


	YUMEMI_1050F procdesc near


	YUMEMI_105B5 procdesc near


	YUMEMI_10669 procdesc near


; dispatcher/table extracted to th03/main/main_03_yumemi_update.asm

	YUMEMI_108CA procdesc near


	YUMEMI_10A17 procdesc near


	GBA_BOSS_RENDER_YUMEMI procdesc far


	REIMU_10BFE procdesc far


	REIMU_10C4D procdesc near


	REIMU_10DA0 procdesc near


	REIMU_10E16 procdesc near


	REIMU_10FD1 procdesc near


; dispatcher/table extracted to th03/main/main_03_reimu_update.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_111A3 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_112A6 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_REIMU procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_113E2 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_11439 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_11547 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_11620 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
; dispatcher/table extracted to th03/main/main_03_ellen_update.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_11814 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_11885 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_1190A procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_ELLEN procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KOTOHIME_11A6D procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_11AC1 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_11B51 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_11BC6 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_11C5F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_11D1A procdesc near


; dispatcher/table extracted to th03/main/main_03_kotohime_update.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KOTOHIME_11FE4 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KOTOHIME_120A0 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KOTOHIME_12103 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_KOTOHIME procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_1219D procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_121F5 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_12355 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_12425 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_12498 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_UPDATE_CHIYURI procdesc far

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_1295E procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_12A10 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_12ADD procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	CHIYURI_12B38 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_CHIYURI procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_12BFB procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_12C4F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_12D37 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_12E78 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_12F06 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_UPDATE_KANA procdesc far

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_13174 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_13223 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_KANA procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	RIKAKO_1334D procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	RIKAKO_133A5 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	RIKAKO_134AA procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	RIKAKO_135A4 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_UPDATE_RIKAKO procdesc far

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	RIKAKO_137CF procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	RIKAKO_138B3 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_BOSS_RENDER_RIKAKO procdesc far

main_03_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
main_04_TEXT	segment	byte public 'CODE' use16
		assume cs:main_04
		;org 0Ah
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

main_04_TEXT	ends

COLLMAP_TEXT	segment byte public 'CODE' use16
	extern @collmap_set_rect_striped$qv:proc
	extern @collmap_set_slope_striped$qv:proc
COLLMAP_TEXT	ends

ENEMY_2_TEXT segment byte public 'CODE' use16
ENEMY_2_TEXT ends

HITBOX_TEXT segment byte public 'CODE' use16
	extern @enemy_formations_update$qv:proc
	extern @enemy_formations_load$qv:proc
	extern @enemy_formations_randomize$qv:proc
	extern @enemy_formations_free$qv:proc

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_142D0 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_MARISA procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MARISA_HYPER_14340 procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_MARISA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_marisa$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_MARISA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	@gauge_pattern_marisa$quc procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_PELLET_MARISA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_BULLET_MARISA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

MARISA_BOMB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_14A76 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_REIMU procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_14B0A procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_REIMU procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_CHARGESHOT_14C8C procdesc pascal near \
		center_x:word, top:word, phase:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_reimu$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_REIMU procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

@gauge_pattern_reimu$quc procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_PELLET_REIMU procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_BULLET_REIMU procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_1501E procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_1508C procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_BOMB_1515D procdesc pascal near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_BOMB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_153BB procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_MIMA procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	MIMA_CHARGESHOT_1546C procdesc pascal near \
		pid:word, record_id:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_MIMA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_mima$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

MIMA_CHARGESHOT_1561C procdesc pascal near \
	center_x:word, center_y:word, sprite_offset:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_MIMA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

@gauge_pattern_mima$quc procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_PELLET_MIMA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_BULLET_MIMA procdesc pascal far

	extern @hitbox_hittest$qv:proc
HITBOX_TEXT ends

P_COMBO_TEXT segment byte public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

YUMEMI_BOMB procdesc pascal far

	extern @combos_update_and_render$qv:proc
P_COMBO_TEXT ends

P_GAUGE_TEXT segment byte public 'CODE' use16
P_GAUGE_TEXT ends

E_ENEMY_TEXT segment byte public 'CODE' use16
E_ENEMY_TEXT ends

ENEMY_PUT segment byte public 'CODE' use16
	extern @enemies_update$qv:proc
	extern @enemies_render$qv:proc
ENEMY_PUT ends

E_EXPL_TEXT segment byte public 'CODE' use16
E_EXPL_TEXT ends

PELLET_PUT segment byte public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	extrn SUB_16983:proc


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_16A55 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_YUMEMI procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
CHARGESHOT_UPDATE_YUMEMI procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@chargeshot_hittest_yumemi$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
YUMEMI_CHARGESHOT_16BB5 procdesc pascal near \
	sprite_offset:word, length:word, angle:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
CHARGESHOT_RENDER_YUMEMI procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@GAUGE_PATTERN_YUMEMI$QUC procdesc near

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_PELLET_YUMEMI procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_BULLET_YUMEMI procdesc pascal far

	@grcg_pellet_put$qiuii procdesc near
PELLET_PUT ends

BULLET_TEXT segment byte public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

MIMA_17043 procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

MIMA_BOMB_1714F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

MIMA_BOMB procdesc pascal far

BG_1 = 0
BG_1_AIMED = 1
BG_2_SPREAD_NARROW = 2
BG_2_SPREAD_NARROW_AIMED = 5
BG_3_SPREAD_NARROW = 8
BG_3_SPREAD_NARROW_AIMED = 11
BG_4_SPREAD_NARROW = 14
BG_4_SPREAD_MEDIUM = 15
BG_4_SPREAD_WIDE = 16
BG_4_SPREAD_NARROW_AIMED = 17
BG_4_SPREAD_MEDIUM_AIMED = 18
BG_5_SPREAD_NARROW = 20
BG_5_SPREAD_MEDIUM = 21
BG_5_SPREAD_WIDE = 22
BG_5_SPREAD_NARROW_AIMED = 23
BG_5_SPREAD_MEDIUM_AIMED = 24
BG_RANDOM_ANGLE_AND_SPEED = 28
BG_RANDOM_CONSTRAINED_ANGLE_AIMED = 29
BG_2_RING = 33
BG_4_RING = 32
BG_8_RING = 35
BG_16_RING = 36
BG_32_RING = 37
BG_RING = 38
BG_RING_AIMED = 44
BG_2_SPREAD_HORIZONTALLY_SYMMETRIC = 34

BT_PELLET = 1
BT_BULLET16_DEFAULT = 2
BT_PELLET_CLOUD = 4
BT_BULLET16_DEFAULT_WITH_ACCEL = 7
BT_BULLET16_CUSTOM_WITH_ACCEL = 8
BAT_Y = 80h

	extern @bullets_reset$qv:proc
	extern @bullets_add$qv:proc
	extern @bullet_template_reset_stuff$qv:proc
	extern @bullets_update$qv:proc
	extern @bullets_render$qv:proc
BULLET_TEXT ends

E_FIREB_TEXT segment byte public 'CODE' use16
	extern @fireballs_update$qv:proc
	extern @fireballs_hittest_and_render$qv:proc
E_FIREB_TEXT ends

; ===========================================================================

; Segment type:	Pure code
main_05_TEXT	segment	byte public 'CODE' use16
		assume cs:main_05_TEXT
		;org 1
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

CHIYURI_BOMB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

ELLEN_185AB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

ELLEN_BOMB_186C3 procdesc pascal near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

ELLEN_BOMB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KANA_BOMB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_BOMB procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

RIKAKO_BOMB procdesc pascal far
main_05_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
P_EXATT_TEXT segment byte public 'CODE' use16
		assume cs:main_06
		;org 0Ah
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	EXATT_ADD_CHIYURI procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_chiyuri_1905A procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@exatt_update_chiyuri$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@exatt_render_chiyuri$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_193BC procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	EXATT_ADD_ELLEN procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_194A9 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_ellen_19510 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_ellen$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_ellen$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	EXATT_ADD_KANA procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	KANA_19896 procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_kana_198DD procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_kana$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_kana$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
EXATT_ADD_MARISA procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

MARISA_19B06 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_marisa_19B4F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_marisa$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_marisa$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
EXATT_ADD_KOTOHIME procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

KOTOHIME_19DD3 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_kotohime_19E2A procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	_kotohime_19EF9 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	_kotohime_19F1F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	_kotohime_19F87 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@exatt_update_kotohime$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@exatt_render_kotohime$qv procdesc far
P_EXATT_TEXT ends

main_06_TEXT segment byte public 'CODE' use16

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_sub_1A1A7 procdesc near
	sub_1A1A7 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	SUB_1A1ED procdesc pascal near \
		x:word, y1:word, target_x:word, target_y:word, pid:word, velocity_base:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	EXATT_ADD_REIMU procdesc pascal far \
		center_x:word, center_y:word, pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	REIMU_1A2CE procdesc pascal far \
		x:word, y:word, angle:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_1A32A procdesc pascal near \
	left:word, top:word, frame:word
sub_1A32A procdesc pascal near \
	left:word, top:word, frame:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_1A377 procdesc pascal near \
	left:word, top:word, frame:word
sub_1A377 procdesc pascal near \
	left:word, top:word, frame:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_reimu_1A3C4 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

SUB_1A491 procdesc pascal near \
	center_x:word, center_y:word
sub_1A491 procdesc pascal near \
	center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_reimu$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_reimu$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	EXATT_ADD_MIMA procdesc pascal far \
		center_x:word, center_y:word, pid:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_mima_1A684 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_mima$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_mima$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@EXATT_ADD_YUMEMI$QIIUC procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

YUMEMI_1A95F procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_yumemi_1A9B0 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_yumemi$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_yumemi$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
EXATT_ADD_RIKAKO procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

RIKAKO_1B006 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_rikako_1B05A procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_update_rikako$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
@exatt_render_rikako$qv procdesc far

main_06_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
main_07_TEXT	segment	byte public 'CODE' use16
		assume cs:main_07_TEXT
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

		_sub_1B260 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_CHIYURI procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_CHIYURI procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_chiyuri_chargeshot_1B35F procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_chiyuri$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_CHIYURI procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

@GAUGE_PATTERN_CHIYURI$QUC procdesc pascal near \
		type:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_PELLET_CHIYURI procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_BULLET_CHIYURI procdesc pascal far

main_07_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
main_08_TEXT	segment	byte public 'CODE' use16
		assume cs:main_08_TEXT
		;org 3
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_sub_1B653 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_ELLEN procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_HYPER_1B6CA procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_ELLEN procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	ELLEN_CHARGESHOT_1B8A6 procdesc pascal near \
		x:word, y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_ellen$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_ELLEN procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

@GAUGE_PATTERN_ELLEN$QUC procdesc pascal near \
		 type:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_PELLET_ELLEN procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	GBA_GAUGE_PATTERN_BULLET_ELLEN procdesc pascal far

main_08_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
main_09_TEXT	segment	byte public 'CODE' use16
		assume cs:main_09_TEXT
		;org 0Dh
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_sub_1BC4D procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_KANA procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_KANA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_kana_chargeshot_1BDF8 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_kana$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_KANA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

@GAUGE_PATTERN_KANA$QUC procdesc pascal near \
		 type:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_PELLET_KANA procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_BULLET_KANA procdesc pascal far

main_09_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
main_10_TEXT	segment	byte public 'CODE' use16
		assume cs:main_10_TEXT
		;org 8
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

_sub_1C158 procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_KOTOHIME procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_KOTOHIME procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_kotohime_chargeshot_1C1E9 procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_kotohime$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_KOTOHIME procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	@GAUGE_PATTERN_KOTOHIME$QUC procdesc pascal near \
		type:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_PELLET_KOTOHIM procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_BULLET_KOTOHIM procdesc pascal far

main_10_TEXT	ends

; ===========================================================================

; Segment type:	Pure code
main_11_TEXT	segment	byte public 'CODE' use16
		assume cs:main_11_TEXT
		;org 0Ah
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

_sub_1C40A procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_ADD_RIKAKO procdesc pascal far \
		center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

RIKAKO_1C497 procdesc pascal far \
	center_x:word, center_y:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

RIKAKO_HYPER_1C4B4 procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_UPDATE_RIKAKO procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

	_rikako_chargeshot_1C62A procdesc near


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	@chargeshot_hittest_rikako$qv procdesc far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
	CHARGESHOT_RENDER_RIKAKO procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

@GAUGE_PATTERN_RIKAKO$QUC procdesc pascal near \
		type:word


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_PELLET_RIKAKO procdesc pascal far


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
GBA_GAUGE_PATTERN_BULLET_RIKAKO procdesc pascal far

main_11_TEXT	ends

	.data

PID_NONE = -1

; Story CPU safety, play-character speed, and startup filename data moved to th03/main/story_startup[data].asm.
; Support/format data moved to th03/main/support_format[data].asm.
; GBA launch, hit-circle mask, and enemy filename data moved to th03/main/gba_hitc_enemy[data].asm.
; Player/boss pattern-table data moved to th03/main/pbpat[data].asm.
; Warning flag and text data moved to th03/main/warn[data].asm.
include th03/main/player/combo[data].asm
	evendata

EXPLOSION_CELS = 4

public _SO_ENEMIES, _SO_EXPLOSIONS
label _SO_ENEMIES word
	dw ((104 * ROW_SIZE) + ( 48 / BYTE_DOTS))	; 16x16
	dw ((112 * ROW_SIZE) + ( 96 / BYTE_DOTS))	; 32x32
	dw ((104 * ROW_SIZE) + (272 / BYTE_DOTS))	; 48x48
	dw ((128 * ROW_SIZE) + (192 / BYTE_DOTS))	; 64x64
label _SO_EXPLOSIONS word
label _SO_EXPLOSION_32X32 word
	dw ((128 * ROW_SIZE) + (256 / BYTE_DOTS))
	dw ((128 * ROW_SIZE) + (288 / BYTE_DOTS))
	dw ((144 * ROW_SIZE) + (256 / BYTE_DOTS))
	dw ((144 * ROW_SIZE) + (288 / BYTE_DOTS))
label _SO_EXPLOSION_48X48 word
	dw ((104 * ROW_SIZE) + (320 / BYTE_DOTS))
	dw ((128 * ROW_SIZE) + (320 / BYTE_DOTS))
	dw ((152 * ROW_SIZE) + (320 / BYTE_DOTS))
	dw ((168 * ROW_SIZE) + (368 / BYTE_DOTS))
label _SO_EXPLOSION_64X64 word
	dw ((104 * ROW_SIZE) + (368 / BYTE_DOTS))
	dw ((136 * ROW_SIZE) + (368 / BYTE_DOTS))
	dw ((104 * ROW_SIZE) + (432 / BYTE_DOTS))
	dw ((136 * ROW_SIZE) + (432 / BYTE_DOTS))
label _SO_EXPLOSION_80X80 word
	dw ((160 * ROW_SIZE) + (  0 / BYTE_DOTS))
	dw ((160 * ROW_SIZE) + ( 80 / BYTE_DOTS))
	dw ((160 * ROW_SIZE) + (160 / BYTE_DOTS))
	dw ((160 * ROW_SIZE) + (240 / BYTE_DOTS))

public _chain_ring_p
_chain_ring_p	db	PLAYER_COUNT dup(0)

include th03/sprites/score.asp
include th03/main/5_powers_of_10[data].asm
public _word_1DE12, word_1DE12, _word_1DE24, word_1DE24
_word_1DE12 label word
word_1DE12 label word
	dw 108, 96, 80, 64, 48, 32, 16, 8, 4
_word_1DE24 label word
word_1DE24 label word
	dw 2, 8, 16, 16, 16, 16, 16, 8, 2
public _word_1DE36, word_1DE36, _word_1DE38, word_1DE38
_word_1DE36 label word
word_1DE36 dw (48 shl 4)
_word_1DE38 label word
word_1DE38 dw (112 shl 4)
	dw (96 shl 4), (96 shl 4)
	dw (144 shl 4), (80 shl 4)
	dw (192 shl 4), (96 shl 4)
	dw (240 shl 4), (112 shl 4)
public _aMAX_COMBO
_aMAX_COMBO label byte
aMAX_COMBO	db 'ÇlÇ`ÇwÅ@ÇbÇèÇçÇÇÇèÅ@Å@Å@Å~',0
public _aGAUGE_ATTACK_TIMES
_aGAUGE_ATTACK_TIMES label byte
aGAUGE_ATTACK_TIMES	db 'ÉQÅ[ÉWÉAÉ^ÉbÉNâÒêîÅ@Å@Å@Å~',0
public _aBOSS_ATTACK_TIMES
_aBOSS_ATTACK_TIMES label byte
aBOSS_ATTACK_TIMES	db 'É{ÉXÉAÉ^ÉbÉNâÒêîÅ@Å@Å@Å@Å~',0
public _aBOSS_REVERSAL_TIMES
_aBOSS_REVERSAL_TIMES label byte
aBOSS_REVERSAL_TIMES	db 'É{ÉXÉäÉoÅ[ÉTÉãâÒêîÅ@Å@Å@Å~',0
public _aBOSS_PANIC_TIMES
_aBOSS_PANIC_TIMES label byte
aBOSS_PANIC_TIMES	db 'É{ÉXÉpÉjÉbÉNâÒêîÅ@Å@Å@Å@Å~',0
public _aTOTAL
_aTOTAL label byte
aTOTAL	db 'Å@Å@Å@ÇsÇnÇsÇ`ÇkÅ@Å@Å@Å@Å@',0
public _aWINNER_BONUS
_aWINNER_BONUS label byte
aWINNER_BONUS	db 'Å@Å@ÇvÇhÇmÇmÇdÇqÅ@ÇaÇnÇmÇtÇrÅ@Å@',0
public _aALL_CLEAR
_aALL_CLEAR label byte
aALL_CLEAR	db 'Å@Å@Å@Ç`ÇkÇkÅ@ÇbÇkÇdÇ`ÇqÅIÅIÅ@Å@',0
public _aPLAYER_REM
_aPLAYER_REM label byte
aPLAYER_REM	db 'écÇËêlêîÅ@Å@Å@Å@Å@Å@Å@Å@Å~',0
	evendata
include th03/sprites/pellet.asp
		db    1
		db    0

	.data?

; Input/demo/round gate BSS prefix moved to th03/main/round_gate_bss.asm.
; Support/resident BSS prefix moved to th03/main/support_resident_bss.asm.
; Palette/GBA BSS prefix moved to th03/main/palette_gba_bss.asm.
; Generic Boss Attack core/tuning BSS prefix moved to th03/main/gba_boss_bss.asm.
; Shared random-ring BSS prefix moved to th03/main/randring_bss.asm.
; Chiyuri gauge/charge-shot BSS moved to th03/main/chiyuri_bss.asm.
; Enemy formation/ENEDAT BSS moved to th03/main/enemy_formation_bss.asm.
; Ellen BSS moved to th03/main/ellen_bss.asm.
; Kana BSS moved to th03/main/kana_bss.asm.

; Hitcircle BSS moved to th03/main/hitcircle_bss.asm.
; Shot/support and Kotohime BSS moved to th03/main/shot_kotohime_bss.asm.

; External attack BSS moved to th03/main/exatt_bss.asm.

; Charge-shot/GBA callback BSS moved to th03/main/chargeshot_gba_bss.asm.
; GBA/exattack/bomb work BSS moved to th03/main/gba_exatt_bomb_bss.asm.

HSF_DONE = 0
HSF_INIT = 1
HSF_ACTIVE = 2

; HUD-start/player GBA BSS moved to th03/main/hud_player_gba_bss.asm.

; Hitbox/defeat/Rikako BSS moved to th03/main/hitbox_defeat_rikako_bss.asm.
; GBA/combo/PLAYER_M buffer BSS moved to th03/main/gba_combo_playerm_bss.asm.

EFF_FREE = 0
EFF_EXPLOSION_IGNORING_ENEMIES = 9
EFF_EXPLOSION_HITTING_ENEMIES = 10

efe_t struct
	EFE_flag                         	db ?
	EFE_frame                        	db ?
	EFE_center                       	Point <?>
	EFE_explosion_max_enemy_hits_half	db ?
		db ?
	EFE_pid                          	db ?
	EFE_size_pixels                  	db ?
		db 18 dup (?)
	EFE_chain_slot                   	db ?
		db 19 dup(?)
efe_t ends

EF_RUNNING_SPAWNED = 1

enemy_t struct
	ENEMY_flag           	db ?
	ENEMY_frame          	db ?
	ENEMY_center         	Point <?>
	ENEMY_size_words     	db ?
	ENEMY_hp             	db ?
	ENEMY_pid            	db ?
	ENEMY_size_pixels    	db ?
	ENEMY_script_ip      	dw ?
	ENEMY_script_op_frame	dw ?
	ENEMY_script_base    	dw ?
	ENEMY_velocity       	Point <?>
		db 4 dup (?)
	ENEMY_angle_wide label word
	ENEMY_angle_fine     	db ?
	ENEMY_angle_coarse   	db ?
	ENEMY_angle_speed    	db ?
		db ?
	ENEMY_chain_slot     	db ?
	ENEMY_formation_type 	db ?
	ENEMY_formation_i    	db ?
	ENEMY_speed          	db ?
	ENEMY_loop_i         	db ?
	ENEMY_pos_type       	db ?
		db 14 dup(?)
enemy_t ends

EFE_COUNT = 64
ENEMY_COUNT = 40

; Enemy/explosion/score/extend BSS moved to th03/main/enemy_explosion_score_bss.asm.
; Yumemi/Rikako small-state BSS moved to th03/main/yumemi_rikako_small_bss.asm.
; Collision-map BSS moved to th03/main/collmap_bss.asm.
BOMB_FRAMES = 180

BF_INACTIVE = 0
BF_PREPARING = 1
BF_ACTIVE = 2

include th03/main/chars/speeds.inc

; Bomb/player/PID BSS moved to th03/main/bomb_player_pid_bss.asm.
ROUND_SPEED_MAX = ((8 shl 4) - 1)

; Round/frame BSS moved to th03/main/round_frame_bss.asm.
; Player/shot/result tail BSS moved to th03/main/player_shot_result_tail_bss.asm.

bullet_template_t struc
	BT_center       	Point <?>
	BT_speed        	db ?
	BT_angle        	db ?
	BT_pid          	db ?
	BT_group        	db ?
	BT_accel_type   	db ?
	BT_count        	db ?
	BT_velocity_tmp 	Point <?>
	BT_sprite_offset	dw ?
	BT_type         	db ?
	BT_is_collidable	db ?
	BT_is_animated  	db ?
	BT_has_trail    	db ?
bullet_template_t ends

	extern _bullet_base_speed:byte
	extern _bullet_template:bullet_template_t
	extern _ef_onehit:byte

		end
