;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	661F4F8FFAF1F3274F503D154133DEF0

; File Name   :	th03/OP.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-FD80h Loaded length: E97Ah
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

	.386
	.model use16 large _TEXT

include ReC98.inc
include th03/opsf[decl].inc
include th03/opb[decl].inc

; Text moved to th03/op[text].asm.

	.data

; Data moved to th03/opsf[data].asm.

	.data?

; BSS moved to th03/op[bss].asm.

	end
