;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input MD5   : 9466D867385BD4CC0A6FD3E3D4E9FB01

; File Name   : th04/ZUN.COM:MEMCHK (-M)
; Format      : MS-DOS COM-file
; Base Address: 0h Range: 100h-10E2h Loaded length: FE2h
; OS type   :  MS DOS
; Application type:  Executable 16bit

		.286

DGROUP	group _TEXT, _DATA

_TEXT		segment byte 'CODE' use16
		assume cs:_TEXT

; `main()` was the first thing this contribution emitted and is now
; th04/memchka.cpp, listed ahead of this dump in Tupfile.lua's `memchk`
; link so TLINK still lays it down first. Both `_DATA` string literals went
; with it, which is why the segment at the bottom of this file is empty.
; The `db 0` below is the original pad between main() and dos_puts2() and
; belongs to THIS contribution -- it is what keeps dos_puts2 at 0x38E.
		db 0

; =============== S U B R O U T I N E =======================================


; void near pascal dos_puts2(const char near *string);
;
; Byte-for-byte master.lib's dos_puts2() (libs/master.lib/dos_puts2.asm)
; assembled in the near model, pasted into this .COM rather than linked --
; `memchk` does not pull masters.lib, so the name cannot collide here.
; Hand-written: `mov bx, sp` for a frame and SI saved in CX rather than
; pushed, which is upstream's own undecompilable shape.
public DOS_PUTS2
DOS_PUTS2  proc near
		mov	bx, sp
		mov	cx, si
		mov	si, ss:[bx+2]
		lodsb
		or	al, al
		jz	short loc_3B0
		mov	ah, 2

loc_39D:
		cmp	al, 0Ah
		jnz	short loc_3A7
		mov	dl, 0Dh
		int	21h		; DOS - DISPLAY OUTPUT
					; DL = character to send to standard output
		mov	al, 0Ah

loc_3A7:
		mov	dl, al
		int	21h		; DOS - DISPLAY OUTPUT
					; DL = character to send to standard output
		lodsb
		or	al, al
		jnz	short loc_39D

loc_3B0:
		mov	si, cx
		retn	2
DOS_PUTS2  endp
		nop

; =============== S U B R O U T I N E =======================================


; unsigned near pascal main_memory_free_paragraphs(void);
;
; Asks DOS for an impossible 0FFFFh paragraphs purely to read back the
; largest block it reports as available. Returns 0 if DOS failed with
; anything other than error 8, and the same success in CF -- which no C++
; declaration can express, so this one stays in ASM.
public MAIN_MEMORY_FREE_PARAGRAPHS
MAIN_MEMORY_FREE_PARAGRAPHS  proc near
		mov	ah, 48h
		mov	bx, 0FFFFh
		int	21h		; DOS - 2+ - ALLOCATE MEMORY
					; BX = number of 16-byte paragraphs desired
		cmp	ax, 8
		jnz	short loc_3C6
		mov	ax, bx
		clc
		retn
; ---------------------------------------------------------------------------

loc_3C6:
		xor	ax, ax
		stc
		retn
MAIN_MEMORY_FREE_PARAGRAPHS  endp
_TEXT	ends

_DATA	segment byte 'DATA' use16
; Both string literals moved to th04/memchka.cpp with main(), their only reader.
_DATA	ends

		end
