;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	50C37C4BDDEC04B753524F5D3B030A96

; File Name   :	th04/MAINE.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-126D0h Loaded length: 10062h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'E'

include ReC98.inc
include th04/th04.inc
include th04/hardware/grppsafx.inc

group_01 group maine_01_TEXT, SCORE_TEXT

; ===========================================================================

; Segment type:	Pure code
_TEXT segment word public 'CODE' use16
	extern PALETTE_BLACK_IN:proc
	extern PALETTE_BLACK_OUT:proc
	extern EGC_OFF:proc
	extern FILE_APPEND:proc
	extern FILE_CLOSE:proc
	extern FILE_READ:proc
	extern FILE_ROPEN:proc
	extern FILE_SEEK:proc
	extern FILE_WRITE:proc
	extern GRCG_SETCOLOR:proc
	extern GAIJI_PUTCA:proc
	extern GAIJI_PUTSA:proc
	extern GRAPH_COPY_PAGE:proc
	extern GRAPH_PI_FREE:proc
	extern PALETTE_SHOW:proc
	extern IRAND:proc
	extern TEXT_CLEAR:proc
	extern SUPER_FREE:proc
	extern SUPER_ENTRY_BFNT:proc
	extern SUPER_PUT:proc
	extern GRAPH_GAIJI_PUTS:proc
	extern GRAPH_GAIJI_PUTC:proc
_TEXT ends

; ===========================================================================

maine_01_TEXT segment byte public 'CODE' use16
		assume cs:group_01
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_AED0	proc near

var_2		= word ptr -2
arg_0		= word ptr  4
@@top		= word ptr  6
@@left		= word ptr  8

		enter	2, 0
		push	si
		push	di
		mov	si, [bp+arg_0]
		or	si, si
		jnz	short loc_AEF1
		push	[bp+@@left]
		push	[bp+@@top]
		mov	al, _cdg_slot
		mov	ah, 0
		push	ax
		call	cdg_put_8
		jmp	loc_B027
; ---------------------------------------------------------------------------

loc_AEF1:
		call	grcg_setcolor pascal, (GC_RMW shl 16) + V_WHITE
		mov	bx, 4
		mov	ax, si
		cwd
		idiv	bx
		mov	si, ax
		push	[bp+@@left]
		push	ax
		mov	al, _radial_angle
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_CosTable8[bx]
		call	@polar$qiii
		mov	di, ax
		push	[bp+@@top]
		push	si
		mov	al, _radial_angle
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_SinTable8[bx]
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	0
		call	cdg_put_plane
		mov	al, _radial_angle
		add	al, 40h
		mov	_radial_angle, al
		push	[bp+@@left]
		push	si
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_CosTable8[bx]
		call	@polar$qiii
		mov	di, ax
		push	[bp+@@top]
		push	si
		mov	al, _radial_angle
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_SinTable8[bx]
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	1
		call	cdg_put_plane
		mov	al, _radial_angle
		add	al, 40h
		mov	_radial_angle, al
		push	[bp+@@left]
		push	si
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_CosTable8[bx]
		call	@polar$qiii
		mov	di, ax
		push	[bp+@@top]
		push	si
		mov	al, _radial_angle
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_SinTable8[bx]
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	2
		call	cdg_put_plane
		mov	al, _radial_angle
		add	al, 40h
		mov	_radial_angle, al
		push	[bp+@@left]
		push	si
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_CosTable8[bx]
		call	@polar$qiii
		mov	di, ax
		push	[bp+@@top]
		push	si
		mov	al, _radial_angle
		mov	ah, 0
		add	ax, ax
		mov	bx, ax
		push	_SinTable8[bx]
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	3
		call	cdg_put_plane
		mov	al, _radial_angle
		add	al, 40h
		mov	_radial_angle, al
		GRCG_OFF_CLOBBERING dx

loc_B027:
		pop	di
		pop	si
		leave
		retn	6
sub_AED0	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B02D	proc near

var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8

		enter	2, 0
		push	si
		push	di
		mov	si, [bp+arg_0]
		or	si, si
		jnz	short loc_B04E
		push	[bp+arg_4]
		push	[bp+arg_2]
		mov	al, _cdg_slot
		mov	ah, 0
		push	ax
		call	cdg_put_8
		jmp	loc_B13E
; ---------------------------------------------------------------------------

loc_B04E:
		call	grcg_setcolor pascal, (GC_RMW shl 16) + V_WHITE
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	si, ax
		push	[bp+arg_4]
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8+192
		call	@polar$qiii
		mov	di, ax
		push	[bp+arg_2]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8+64
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	0
		call	cdg_put_plane
		call	@polar$qiii pascal, [bp+arg_4], si, _CosTable8+128
		mov	di, ax
		call	@polar$qiii pascal, [bp+arg_2], si, _CosTable8
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	1
		call	cdg_put_plane
		push	[bp+arg_4]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8+448
		call	@polar$qiii
		mov	di, ax
		push	[bp+arg_2]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8+320
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	2
		call	cdg_put_plane
		call	@polar$qiii pascal, [bp+arg_4], si, _CosTable8+384
		mov	di, ax
		call	@polar$qiii pascal, [bp+arg_2], si, _CosTable8+256
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	3
		call	cdg_put_plane
		GRCG_OFF_CLOBBERING dx

loc_B13E:
		pop	di
		pop	si
		leave
		retn	6
sub_B02D	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B144	proc near

var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8

		enter	2, 0
		push	si
		push	di
		mov	si, [bp+arg_0]
		or	si, si
		jnz	short loc_B165
		push	[bp+arg_4]
		push	[bp+arg_2]
		mov	al, _cdg_slot
		mov	ah, 0
		push	ax
		call	cdg_put_8
		jmp	loc_B255
; ---------------------------------------------------------------------------

loc_B165:
		call	grcg_setcolor pascal, (GC_RMW shl 16) + V_WHITE
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	si, ax
		push	[bp+arg_4]
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8
		call	@polar$qiii
		mov	di, ax
		push	[bp+arg_2]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_SinTable8
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	0
		call	cdg_put_plane
		call	@polar$qiii pascal, [bp+arg_4], si, _CosTable8
		mov	di, ax
		call	@polar$qiii pascal, [bp+arg_2], si, _SinTable8
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	1
		call	cdg_put_plane
		push	[bp+arg_4]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8+256
		call	@polar$qiii
		mov	di, ax
		push	[bp+arg_2]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		push	ax
		push	_CosTable8+128
		call	@polar$qiii
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	2
		call	cdg_put_plane
		call	@polar$qiii pascal, [bp+arg_4], si, _CosTable8+256
		mov	di, ax
		call	@polar$qiii pascal, [bp+arg_2], si, _CosTable8+128
		mov	[bp+var_2], ax
		push	di
		push	ax
		mov	al, _cdg_slot
		mov	ah, 0
		inc	ax
		push	ax
		push	3
		call	cdg_put_plane
		GRCG_OFF_CLOBBERING dx

loc_B255:
		pop	di
		pop	si
		leave
		retn	6
sub_B144	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B25B	proc near

arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8
arg_6		= word ptr  0Ah
arg_8		= word ptr  0Ch

		push	bp
		mov	bp, sp
		push	si
		mov	si, [bp+arg_0]
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	si, ax
		mov	ax, [bp+arg_8]
		sub	ax, si
		push	ax
		mov	ax, [bp+arg_6]
		sub	ax, si
		push	ax
		mov	ax, si
		add	ax, ax
		add	ax, [bp+arg_4]
		push	ax
		mov	ax, si
		add	ax, ax
		add	ax, [bp+arg_2]
		push	ax
		call	bgimage_put_rect_16
		pop	si
		pop	bp
		retn	0Ah
sub_B25B	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B291	proc near

@@page    	= word ptr -2
@@base_top 	= word ptr  4
@@base_left	= word ptr  6

		enter	2, 0
		push	si
		push	di
		mov	di, [bp+@@base_left]
		mov	si, 3Fh	; '?'
		mov	[bp+@@page], 0
		graph_accesspage 0
		mov	dx, 164	; Port 00A4h: Page display register
		mov	al, 1
		jmp	short loc_B30B
; ---------------------------------------------------------------------------

loc_B2AF:
		push	di
		push	[bp+@@base_top]
		mov	al, _cdg_slot
		mov	ah, 0
		shl	ax, 4
		mov	bx, ax
		push	_cdg_slots.pixel_w[bx]
		mov	al, _cdg_slot
		mov	ah, 0
		shl	ax, 4
		mov	bx, ax
		push	_cdg_slots.pixel_h[bx]
		lea	ax, [si+1]
		push	ax
		call	sub_B25B
		dec	si
		mov	al, _radial_angle
		add	al, 8
		mov	_radial_angle, al
		call	_dissolve_put_func pascal, di, [bp+@@base_top], si

loc_B2E8:
		cmp	vsync_Count1, 2
		jb	short loc_B2E8
		mov	vsync_Count1, 0
		graph_showpage byte ptr [bp+@@page]
		mov	ax, 1
		sub	ax, [bp+@@page]
		mov	[bp+@@page], ax
		mov	dx, 166	; Port 00A6h: Page access register
		mov	al, byte ptr [bp+@@page]

loc_B30B:
		out	dx, al
		or	si, si
		jg	short loc_B2AF
		call	graph_copy_page pascal, [bp+@@page]
		pop	di
		pop	si
		leave
		retn	4
sub_B291	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B31E	proc near

@@page    	= word ptr -2
@@base_top	= word ptr  4
@@base_left	= word ptr  6

		enter	2, 0
		push	si
		push	di
		mov	di, [bp+@@base_left]
		xor	si, si
		mov	[bp+@@page], 0
		graph_accesspage 0
		mov	dx, 164	; Port 00A4h: Page display register
		mov	al, 1

loc_B339:
		out	dx, al
		push	di
		push	[bp+@@base_top]
		mov	al, _cdg_slot
		mov	ah, 0
		shl	ax, 4
		mov	bx, ax
		push	_cdg_slots.pixel_w[bx]
		mov	al, _cdg_slot
		mov	ah, 0
		shl	ax, 4
		mov	bx, ax
		push	_cdg_slots.pixel_h[bx]
		push	si
		call	sub_B25B
		inc	si
		mov	al, _radial_angle
		add	al, 8
		mov	_radial_angle, al
		cmp	si, 40h
		jge	short loc_B39A
		call	_dissolve_put_func pascal, di, [bp+@@base_top], si

loc_B375:
		cmp	vsync_Count1, 2
		jb	short loc_B375
		mov	vsync_Count1, 0
		graph_showpage byte ptr [bp+@@page]
		mov	ax, 1
		sub	ax, [bp+@@page]
		mov	[bp+@@page], ax
		mov	dx, 166	; Port 00A6h: Page access register
		mov	al, byte ptr [bp+@@page]
		jmp	short loc_B339
; ---------------------------------------------------------------------------

loc_B39A:
		mov	ax, 1
		sub	ax, [bp+@@page]
		call	graph_copy_page pascal, ax
		pop	di
		pop	si
		leave
		retn	4
sub_B31E	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_B3AC	proc near

@@page       	= word ptr -2
@@base_top_2 	= word ptr  4
@@base_left_2	= word ptr  6
@@base_top_1 	= word ptr  8
@@base_left_1	= word ptr  0Ah

		enter	2, 0
		push	si
		push	di
		mov	di, [bp+@@base_left_1]
		xor	si, si
		mov	[bp+@@page], 0
		graph_accesspage 0
		mov	dx, 164	; Port 00A4h: Page display register
		mov	al, 1

loc_B3C7:
		out	dx, al
		push	di
		push	[bp+@@base_top_1]
		push	_cdg_slots.pixel_w + (size cdg_t * 2)
		push	_cdg_slots.pixel_h + (size cdg_t * 2)
		push	si
		call	sub_B25B
		push	[bp+@@base_left_2]
		push	[bp+@@base_top_2]
		push	_cdg_slots.pixel_w + (size cdg_t * 0)
		push	_cdg_slots.pixel_h + (size cdg_t * 0)
		push	si
		call	sub_B25B
		inc	si
		mov	al, _radial_angle
		add	al, -8
		mov	_radial_angle, al
		cmp	si, 40h
		jge	short loc_B43B
		mov	_cdg_slot, 2
		call	_dissolve_put_func pascal, di, [bp+@@base_top_1], si
		mov	_cdg_slot, 0
		call	_dissolve_put_func pascal, [bp+@@base_left_2], [bp+@@base_top_2], si

loc_B416:
		cmp	vsync_Count1, 2
		jb	short loc_B416
		mov	vsync_Count1, 0
		graph_showpage byte ptr [bp+@@page]
		mov	ax, 1
		sub	ax, [bp+@@page]
		mov	[bp+@@page], ax
		mov	dx, 166	; Port 00A6h: Page access register
		mov	al, byte ptr [bp+@@page]
		jmp	short loc_B3C7
; ---------------------------------------------------------------------------

loc_B43B:
		mov	ax, 1
		sub	ax, [bp+@@page]
		call	graph_copy_page pascal, ax
		pop	di
		pop	si
		leave
		retn	8
sub_B3AC	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @staffroll_animate$qv
@staffroll_animate$qv proc near
		push	bp
		mov	bp, sp
		mov	PaletteTone, 0
		call	far ptr	palette_show
		graph_accesspage 1
		call	@pi_load$qinxc pascal, 0, ds, offset aSff1_pi
		call	@pi_palette_apply$qi pascal, 0
		call	@pi_put_8$qiii pascal, large 0, 0
		freePISlotLarge	0
		call	graph_copy_page pascal, 0
		call	_bgimage_snap
		kajacall	KAJA_SONG_STOP
		call	snd_load pascal, ds, offset aStaff, SND_LOAD_SONG
		kajacall	KAJA_SONG_PLAY
		push	0Ch
		call	palette_black_in
		call	cdg_load_single pascal, 0, ds, offset aSff1_cdg, 0
		call	cdg_load_single_noalpha pascal, 1, ds, offset aSff1b_cdg, 0
		call	snd_delay_until_measure pascal, (3 shl 16) or 64
		mov	_cdg_slot, 0
		mov	_dissolve_put_func, offset sub_AED0
		call	sub_B291 pascal, (352 shl 16) or 160
		call	cdg_load_single pascal, 2, ds, offset aSff2_cdg, 0
		call	cdg_load_single_noalpha pascal, 3, ds, offset aSff2b_cdg, 0
		call	snd_delay_until_measure pascal, (7 shl 16) or 160
		mov	_dissolve_put_func, offset sub_B02D
		call	sub_B31E pascal, (352 shl 16) or 160
		mov	_cdg_slot, 2
		mov	_dissolve_put_func, offset sub_B144
		call	sub_B291 pascal, (192 shl 16) or 128
		graph_accesspage 0
		mov	_cdg_slot, 0
		call	cdg_load_single pascal, 0, ds, offset aSff3_cdg, 0
		call	cdg_load_single_noalpha pascal, 1, ds, offset aSff3b_cdg, 0
		call	snd_delay_until_measure pascal, (11 shl 16) or 160
		call	sub_B291 pascal, (288 shl 16) or 200
		call	snd_delay_until_measure pascal, (19 shl 16) or 160
		mov	_dissolve_put_func, offset sub_B02D
		call	sub_B3AC pascal, (192 shl 16) or 128, (288 shl 16) or 200
		push	4
		call	palette_black_out
		call	cdg_free_all
		graph_accesspage 1
		call	@pi_load$qinxc pascal, 0, ds, offset aSff2_pi
		call	@pi_palette_apply$qi pascal, 0
		call	@pi_put_8$qiii pascal, large 0, 0
		freePISlotLarge	0
		call	graph_copy_page pascal, 0
		call	_bgimage_snap
		push	4
		call	palette_black_in
		call	cdg_load_single pascal, 2, ds, offset aSff4_cdg, 0
		call	cdg_load_single_noalpha pascal, 3, ds, offset aSff4b_cdg, 0
		call	snd_delay_until_measure pascal, (23 shl 16) or 160
		mov	_cdg_slot, 2
		mov	_dissolve_put_func, offset sub_B144
		call	sub_B291 pascal, (32 shl 16) or 112
		call	cdg_free pascal, 2
		call	cdg_load_single pascal, 4, ds, offset aSff5_cdg, 0
		call	cdg_load_single_noalpha pascal, 5, ds, offset aSff5b_cdg, 0
		call	snd_delay_until_measure pascal, (27 shl 16) or 160
		mov	_cdg_slot, 4
		mov	_dissolve_put_func, offset sub_B02D
		call	sub_B291 pascal, (32 shl 16) or 184
		call	cdg_load_single pascal, 0, ds, offset aSff8_cdg, 0
		call	cdg_load_single_noalpha pascal, 1, ds, offset aSff8b_cdg, 0
		call	snd_delay_until_measure pascal, (31 shl 16) or 160
		mov	_dissolve_put_func, offset sub_B144
		call	sub_B31E pascal, (32 shl 16) or 184
		mov	_cdg_slot, 0
		call	sub_B291 pascal, (64 shl 16) or 184
		call	cdg_load_single pascal, 4, ds, offset aSff9_cdg, 0
		call	cdg_load_single_noalpha pascal, 5, ds, offset aSff9b_cdg, 0
		call	snd_delay_until_measure pascal, (35 shl 16) or 160
		mov	_dissolve_put_func, offset sub_AED0
		call	sub_B31E pascal, (64 shl 16) or 184
		mov	_cdg_slot, 4
		call	sub_B291 pascal, (64 shl 16) or 184
		call	cdg_load_single pascal, 0, ds, offset aSff6_cdg, 0
		call	cdg_load_single_noalpha pascal, 1, ds, offset aSff6b_cdg, 0
		call	snd_delay_until_measure pascal, (39 shl 16) or 160
		mov	_dissolve_put_func, offset sub_B02D
		call	sub_B31E pascal, (64 shl 16) or 184
		mov	_cdg_slot, 0
		call	sub_B291 pascal, (32 shl 16) or 184
		call	snd_delay_until_measure pascal, (43 shl 16) or 160
		mov	_dissolve_put_func, offset sub_B144
		call	sub_B3AC pascal, (32 shl 16) or 112, (32 shl 16) or 184
		call	cdg_load_single pascal, 0, ds, offset aSff7_cdg, 0
		call	cdg_load_single_noalpha pascal, 1, ds, offset aSff7b_cdg, 0
		mov	_cdg_slot, 0
		call	sub_B291 pascal, (32 shl 16) or 336
		call	snd_delay_until_measure pascal, (48 shl 16) or 160
		call	_bgimage_free
		call	cdg_free_all
		push	4
		call	palette_black_out
		pop	bp
		retn
@staffroll_animate$qv endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @GRAPH_3_DIGIT_PUT$QIIUI
@graph_3_digit_put$qiiui	proc near

@@digit	= word ptr -6
@@g_str	= byte ptr -4
@@val  	= word ptr  4
@@top  	= word ptr  6
@@left 	= word ptr  8

		enter	6, 0
		push	si
		xor	si, si
		mov	[bp+@@g_str], g_EMPTY
		mov	ax, [bp+@@val]
		mov	bx, 100
		xor	dx, dx
		div	bx
		mov	[bp+@@digit], ax
		mov	ax, [bp+@@val]
		xor	dx, dx
		div	bx
		mov	[bp+@@val], dx
		cmp	_graph_3_digit_put_as_fixed_2_dig, 0
		jnz	short loc_B7C5
		or	si, [bp+@@digit]
		or	si, si
		jz	short loc_B7C1
		mov	al, byte ptr [bp+@@digit]
		add	al, gb_0_
		mov	[bp+@@g_str], al
		jmp	short loc_B7C5
; ---------------------------------------------------------------------------

loc_B7C1:
		mov	[bp+@@g_str], g_EMPTY

loc_B7C5:
		mov	ax, [bp+@@val]
		mov	bx, 10
		xor	dx, dx
		div	bx
		mov	[bp+@@digit], ax
		mov	ax, [bp+@@val]
		xor	dx, dx
		div	bx
		mov	[bp+@@val], dx
		or	si, [bp+@@digit]
		mov	al, _graph_3_digit_put_as_fixed_2_dig
		mov	ah, 0
		or	si, ax
		or	si, si
		jz	short loc_B7F4
		mov	al, byte ptr [bp+@@digit]
		add	al, gb_0_
		mov	[bp+@@g_str+1], al
		jmp	short loc_B7F8
; ---------------------------------------------------------------------------

loc_B7F4:
		mov	[bp+@@g_str+1], g_EMPTY

loc_B7F8:
		mov	al, byte ptr [bp+@@val]
		add	al, gb_0_
		mov	[bp+@@g_str+2], al
		mov	[bp+@@g_str+3], 0
		push	[bp+@@left]
		push	[bp+@@top]
		push	GAIJI_W
		push	ss
		lea	ax, [bp+@@g_str]
		push	ax
		push	14
		call	graph_gaiji_puts
		pop	si
		leave
		retn	6
@graph_3_digit_put$qiiui	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; kb/codegen/0123: a zero-byte alias so th04/end/verdict_stats.cpp can call
; this. `label` emits nothing, so every following offset is unchanged.
public _graph_score_and_ten_put
_graph_score_and_ten_put label near
sub_B81D	proc near

@@g_str		= byte ptr -0Ch
var_2		= byte ptr -2
var_1		= byte ptr -1

		enter	0Ch, 0
		push	si
		mov	[bp+var_2], 0
		xor	si, si
		jmp	short loc_B851
; ---------------------------------------------------------------------------

loc_B82A:
		mov	ax, 7
		sub	ax, si
		les	bx, _resident
		add	bx, ax
		mov	al, es:[bx+resident_t.score_last]
		mov	[bp+var_1], al
		or	[bp+var_2], al
		cmp	[bp+var_2], 0
		jz	short loc_B84C
		add	al, gb_0_
		mov	[bp+si+@@g_str], al
		jmp	short loc_B850
; ---------------------------------------------------------------------------

loc_B84C:
		mov	[bp+si+@@g_str], g_EMPTY

loc_B850:
		inc	si

loc_B851:
		cmp	si, 8
		jl	short loc_B82A
		mov	[bp+@@g_str+8], 0
		push	(160 shl 16) or 96
		push	GAIJI_W
		push	ss
		lea	ax, [bp+@@g_str]
		push	ax
		push	14
		call	graph_gaiji_puts
		mov	[bp+var_2], 1
		call	graph_putsa_fx pascal, (288 shl 16) or 96, 14, ds, offset aU_	; "点"
		pop	si
		leave
		retn
sub_B81D	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @SKILL_APPLY_AND_GRAPH_PERCENTAGE$QIIUIUI
@skill_apply_and_graph_percentage$qiiuiui	proc near

@@fraction	= dword	ptr -6
@@digits  	= word ptr -2
@@share   	= word ptr  4
@@total   	= word ptr  6
@@top     	= word ptr  8
@@left    	= word ptr  0Ah

		enter	6, 0
		push	si
		push	di
		mov	si, [bp+@@left]
		mov	di, [bp+@@top]
		cmp	[bp+@@total], 0
		jz	short loc_B8A2
		mov	[bp+@@fraction], 1000000
		jmp	short loc_B8AA
; ---------------------------------------------------------------------------

loc_B8A2:
		mov	[bp+@@fraction], 0

loc_B8AA:
		mov	ax, [bp+@@total]
		cmp	ax, [bp+@@share]
		jz	short loc_B8E3
		cmp	[bp+@@total], 0
		jz	short loc_B8CD
		movzx	ebx, [bp+@@total]
		mov	eax, [bp+@@fraction]
		xor	edx, edx
		div	ebx
		mov	[bp+@@fraction], eax
		jmp	short loc_B8D5
; ---------------------------------------------------------------------------

loc_B8CD:
		mov	[bp+@@fraction], 0

loc_B8D5:
		movzx	eax, [bp+@@share]
		imul	eax, [bp+@@fraction]
		mov	[bp+@@fraction], eax

loc_B8E3:
		cmp	_skill_subtract, 0
		jnz	short loc_B8F4
		mov	eax, _skill
		add	eax, [bp+@@fraction]
		jmp	short loc_B8FC
; ---------------------------------------------------------------------------

loc_B8F4:
		mov	eax, _skill
		sub	eax, [bp+@@fraction]

loc_B8FC:
		mov	_skill, eax
		mov	eax, [bp+@@fraction]
		mov	ebx, 10000
		xor	edx, edx
		div	ebx
		mov	[bp+@@digits], ax
		call	@graph_3_digit_put$qiiui pascal, si, di, ax
		mov	ebx, 10000
		mov	eax, [bp+@@fraction]
		xor	edx, edx
		div	ebx
		mov	[bp+@@fraction], edx
		mov	eax, [bp+@@fraction]
		mov	ebx, 100
		xor	edx, edx
		div	ebx
		mov	[bp+@@digits], ax
		mov	_graph_3_digit_put_as_fixed_2_dig, 1
		lea	ax, [si+48]
		call	@graph_3_digit_put$qiiui pascal, ax, di, [bp+@@digits]
		mov	_graph_3_digit_put_as_fixed_2_dig, 0
		lea	ax, [si+48]
		call	graph_putsa_fx pascal, ax, di, 14, ds, offset aBd	; "．"
		lea	ax, [si+96]
		call	graph_putsa_fx pascal, ax, di, 14, ds, offset aBu	; "％"
		pop	di
		pop	si
		leave
		retn	8
@skill_apply_and_graph_percentage$qiiuiui	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @GRAPH_FRACTION_OF_MILLION_PUT$QIIUL
@graph_fraction_of_million_put$qiiul	proc near

@@digits	= word ptr -2
@@val   	= dword	ptr  4
@@top   	= word ptr  8
@@left  	= word ptr  0Ah

		enter	2, 0
		push	si
		push	di
		mov	si, [bp+@@left]
		mov	di, [bp+@@top]
		mov	eax, [bp+@@val]
		mov	ebx, 10000
		xor	edx, edx
		div	ebx
		mov	[bp+@@digits], ax
		call	@graph_3_digit_put$qiiui pascal, si, di, ax
		mov	ebx, 10000
		mov	eax, [bp+@@val]
		xor	edx, edx
		div	ebx
		mov	[bp+@@val], edx
		mov	eax, [bp+@@val]
		mov	ebx, 100
		xor	edx, edx
		div	ebx
		mov	[bp+@@digits], ax
		mov	_graph_3_digit_put_as_fixed_2_dig, 1
		lea	ax, [si+48]
		call	@graph_3_digit_put$qiiui pascal, ax, di, [bp+@@digits]
		mov	_graph_3_digit_put_as_fixed_2_dig, 0
		lea	ax, [si+48]
		call	graph_putsa_fx pascal, ax, di, 14, ds, offset aBd_0	; "．"
		pop	di
		pop	si
		leave
		retn	8
@graph_fraction_of_million_put$qiiul	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; kb/codegen/0123: a zero-byte alias so th04/end/verdict_stats.cpp can call
; this. `label` emits nothing, so every following offset is unchanged.
public _skill_apply_and_graph_guts
_skill_apply_and_graph_guts label near
sub_B9F2	proc near

var_8		= dword	ptr -8
var_4		= dword	ptr -4

		enter	8, 0
		les	bx, _resident
		mov	eax, es:[bx+resident_t.rand]
		mov	random_seed, eax
		mov	al, es:[bx+resident_t.credit_lives]
		mov	ah, 0
		dec	ax
		mov	bx, ax
		cmp	bx, 5
		ja	short loc_BA52
		add	bx, bx
		jmp	cs:off_BB75[bx]

loc_BA18:
		mov	[bp+var_4], 2500
		jmp	short loc_BA52
; ---------------------------------------------------------------------------

loc_BA22:
		mov	[bp+var_4], 2000
		jmp	short loc_BA52
; ---------------------------------------------------------------------------

loc_BA2C:
		mov	[bp+var_4], 1500
		jmp	short loc_BA52
; ---------------------------------------------------------------------------

loc_BA36:
		mov	[bp+var_4], 1000
		jmp	short loc_BA52
; ---------------------------------------------------------------------------

loc_BA40:
		mov	[bp+var_4], 500
		jmp	short loc_BA52
; ---------------------------------------------------------------------------

loc_BA4A:
		mov	[bp+var_4], 0

loc_BA52:
		les	bx, _resident
		mov	al, es:[bx+resident_t.credit_bombs]
		mov	ah, 0
		or	ax, ax
		jz	short loc_BA67
		cmp	ax, 1
		jz	short loc_BA71
		jmp	short loc_BA79
; ---------------------------------------------------------------------------

loc_BA67:
		add	[bp+var_4], 2500
		jmp	short loc_BA79
; ---------------------------------------------------------------------------

loc_BA71:
		add	[bp+var_4], 1500

loc_BA79:
		les	bx, _resident
		cmp	es:[bx+resident_t.turbo_mode], 0
		jz	short loc_BA8C
		add	[bp+var_4], 2000

loc_BA8C:
		les	bx, _resident
		cmp	es:[bx+resident_t.graze], 0
		jz	short loc_BAA5
		mov	ax, es:[bx+resident_t.graze]
		add	ax, ax
		movzx	eax, ax
		add	[bp+var_4], eax

loc_BAA5:
		mov	[bp+var_8], 1000000
		les	bx, _resident
		mov	ax, es:[bx+resident_t.items_spawned]
		cmp	ax, es:[bx+resident_t.items_collected]
		jz	short loc_BAF3
		cmp	es:[bx+resident_t.items_spawned], 0
		jz	short loc_BAD8
		movzx	ebx, es:[bx+resident_t.items_spawned]
		mov	eax, [bp+var_8]
		xor	edx, edx
		div	ebx
		mov	[bp+var_8], eax
		jmp	short loc_BAE0
; ---------------------------------------------------------------------------

loc_BAD8:
		mov	[bp+var_8], 0

loc_BAE0:
		les	bx, _resident
		movzx	eax, es:[bx+resident_t.items_collected]
		imul	eax, [bp+var_8]
		mov	[bp+var_8], eax

loc_BAF3:
		mov	eax, 1000000
		sub	eax, [bp+var_8]
		mov	[bp+var_8], eax
		mov	ebx, 100
		xor	edx, edx
		div	ebx
		mov	[bp+var_8], eax
		cmp	[bp+var_8], 0
		jz	short loc_BB2A
		call	IRand
		cwde
		xor	edx, edx
		div	[bp+var_8]
		add	[bp+var_4], edx

loc_BB2A:
		mov	eax, [bp+var_4]
		imul	eax, 100
		mov	[bp+var_4], eax
		cmp	[bp+var_4], 1000000
		jbe	short loc_BB48
		mov	[bp+var_4], 1000000

loc_BB48:
		mov	eax, _skill
		add	eax, [bp+var_4]
		mov	_skill, eax
		call	@graph_fraction_of_million_put$qiiul pascal, (192 shl 16) or 264, [bp+var_4]
		call	graph_putsa_fx pascal, (288 shl 16) or 264, 14, ds, offset aBu_0	; "％"
		leave
		retn
sub_B9F2	endp

; ---------------------------------------------------------------------------
		db 0
off_BB75	dw offset loc_BA18
		dw offset loc_BA22
		dw offset loc_BA2C
		dw offset loc_BA36
		dw offset loc_BA40
		dw offset loc_BA4A

; verdict_stats_put_and_wait() -- the twelve labels and their values, the
; [skill] computation and its clamp, the `_ude.txt` verdict line, then the
; wait and the fade-out -- now lives in th04/end/verdict_stats.cpp, which
; th04/staff.cpp includes immediately BEFORE verdict_animate.cpp. That
; object is the LAST one in TH04's MAINE.EXE link list and already
; contributes to this segment immediately BEHIND this dump, so the lifted
; body lands at its original address by growing that contribution's head
; into the hole this deletion leaves: a kb/codegen/0098 tail lift, no
; carve, no new segment, no group-list edit and no Tupfile.lua line.
;
; Its two `jmp cs:` jump tables (`off_C0E2` and `off_C0EE`) went with it --
; Turbo C++ generates both after the epilogue -- and the deleted body
; contained no `assume` (kb/codegen/0121), so the state the rest of this
; contribution is assembled under is unchanged.
;
; The eighteen strings it passed stay in this dump's _DATA and are published
; there under C names, because the 'times' and 'point' counters each appear
; twice byte-identically below and `-d` would merge a C++ literal pair into
; one. See _TIMES_MSG / _TIMES_MSG_0 and _POINT_MSG_0 next to aU_.

; verdict_animate() now lives in th04/end/verdict_animate.cpp, which
; th04/staff.cpp includes. That object is the LAST one in TH04's MAINE.EXE
; link list and emitted nothing at all until now -- only an empty,
; auto-named STAFF_TEXT segment -- so a -zCMAINE_01_TEXT -zPgroup_01 body in
; it lands immediately BEHIND this contribution, at the address this proc
; already had. A kb/codegen/0098 tail lift: no carve, no new segment, no
; group-list edit and no Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`, so the state the
; rest of this contribution is assembled under is unchanged.
;
; Nothing may be added BELOW this line: the tail of this contribution is now
; the seam that every further lift out of this segment grows into.
maine_01_TEXT ends

SCORE_TEXT segment byte public 'CODE' use16
	@HISCORE_SCOREDAT_LOAD_FOR$Q10PLAYCHAR_T procdesc pascal near \
		playchar:byte
	@hiscore_scoredat_save$qv procdesc near

	; regist_score_enter_from_resident() now lives in
	; th04/hiscore/regist_enter.cpp, which th04/hiscore/end.cpp includes at
	; its very end -- and th04/hi_end.cpp's object already contributed to
	; this segment immediately AHEAD of this root contribution, so the
	; lifted body lands at its own original address by growing that object's
	; tail into the hole (kb/codegen/0098 + 0114). It was the FIRST proc of
	; this root contribution; nothing else moved, no carve, no new segment,
	; no group-list edit and no Tupfile.lua line were needed.
	;
	; kb/codegen/0121: the deleted body contained no `assume`, and the two
	; procdescs above it emit nothing, so the state this contribution is
	; assembled under is unchanged and there is nothing to restore.
	@regist_score_enter_from_resident$qv procdesc near
	@SCORE_PUT$QIUC procdesc pascal near \
		place:word, playchar:byte
	@STAGE_PUT$QIII procdesc pascal near \
		place:word, playchar:word, gaiji:word
	@NAME_PUT$QI10PLAYCHAR_TUC procdesc pascal near \
		place:word, playchar:byte, cursor:byte
	@PLACE_PUT$QIUC procdesc pascal near \
		place:word, playchar:byte
	@PLACES_PUT$QUC procdesc pascal near \
		playchar:byte
	@ALPHABET_PUTCA$QIIUI procdesc pascal near \
		col:word, row:word, atrb:word

; ALL SIX functions of this dump's high score table cluster now live in
; th04/hiscore/regist_view.cpp -- score_put(), stage_put(), name_put(),
; place_put(), places_put() and alphabet_putca(), in that order,
; immediately after regist_score_enter_from_resident() at the tail of
; th04/hi_end.cpp's SCORE_TEXT contribution, i.e. exactly where this
; block used to continue. One body serves all six in both games; TH04
; takes the two-player-character arms of its `#if`s, and the TEXT RAM
; arms that TH05 has no counterpart for.

; kb/codegen/0121: none of the deleted bodies contained an `assume`, so
; the state the rest of this contribution is assembled under is unchanged.
; regist_menu() -- the whole name registration screen -- now lives in
; th04/hiscore/regist_menu.cpp, the last #include of th04/hiscore/end.cpp.
; ONE body serves both games, as it already does for the six functions
; above; TH05's copy is appended to th05/regist.cpp instead, because its
; version calls three glyph ball functions that live there. th04/hi_end.cpp
; contributes to this segment immediately before this dump, so the lifted
; body lands at its original address by growing that contribution: another
; kb/codegen/0098 head lift, no carve, no new segment, no Tupfile.lua line.
; Its `jmp cs:` switch table went with it, and it contained no `assume`
; (kb/codegen/0121). The strings it passes stay in this dump's _DATA and are
; published there -- see _hi01_pi and the three below it -- because the two
; Japanese messages are byte-identical to each other and `-d` would merge a
; C++ literal pair into one.
; Nothing may be added above this line.

; egc_copy_rect_1_to_0_16_near() -- the `near` page 1 -> page 0 EGC
; rectangle copy that regist_menu() unblits through -- now lives in
; th04/hiscore/regist_unblit.cpp, together with the static egc_start_copy()
; helper it calls, which is th01/hardware/egc.inc's EGC_START_COPY_INLINED
; spelled in C++ (kb/codegen/0051 for the six 16-bit register writes,
; kb/codegen/0088 for the five immediate-form byte writes).
; th04/hiscore/end.cpp includes that file immediately after regist_menu.cpp,
; i.e. at the very end of th04/hi_end.cpp's SCORE_TEXT contribution -- the
; object that already sat immediately before this one -- so both bodies land
; at their original addresses by growing that contribution's tail
; (kb/codegen/0098 + 0114). No carve, no new segment, no group-list edit and
; no Tupfile.lua line.
;
; kb/codegen/0121: neither deleted body contained an `assume`, so the state
; this contribution is assembled under is unchanged and there is nothing to
; restore.
;
; THIS DUMP'S CONTRIBUTION TO SCORE_TEXT IS NOW EMPTY. Everything left in
; the block above is procdescs and externs, which emit nothing. Nothing may
; be added to it.

SCORE_TEXT	ends

; ===========================================================================

SHARED segment byte public 'CODE' use16
include th02/snd/snd.inc
	extern @FRAME_DELAY$QI:proc
	extern @PI_PALETTE_APPLY$QI:proc
	extern @PI_PUT_8$QIII:proc
	extern @PI_LOAD$QINXC:proc
	extern @INPUT_WAIT_FOR_CHANGE$QI:proc
	extern @POLAR$QIII:proc
	extern SND_KAJA_INTERRUPT:proc
	extern SND_DELAY_UNTIL_MEASURE:proc
	extern CDG_PUT_PLANE:proc
	extern SND_LOAD:proc
	extern GRAPH_PUTSA_FX:proc
	extern CDG_PUT_8:proc
	extern @input_reset_sense$qv:proc
	extern @input_sense$qv:proc
	extern _bgimage_snap:proc
	extern _bgimage_free:proc
	extern BGIMAGE_PUT_RECT_16:proc
	extern CDG_LOAD_SINGLE_NOALPHA:proc
	extern CDG_LOAD_SINGLE:proc
	extern CDG_FREE:proc
	extern CDG_FREE_ALL:proc
SHARED ends

	.data

	; libs/master/pal[data].mas
	extern PaletteTone:word

	; libs/master/rand[data].mas
	extern random_seed:dword

	; libs/master.lib/sin8[data].asm
	extern _SinTable8:word:256
	extern _CosTable8:word:256

	; th04/hardware/grppsafx.asm
	extern _graph_putsa_fx_func:word

include th03/snd/se_state[data].asm
include th04/hardware/bgimage[data].asm
include th03/formats/cdg[data].asm
include th03/formats/pi_put_masked[data].asm
include th03/cutscene/cutscene[data].asm
aSff1_pi	db 'sff1.pi',0
aStaff		db 'staff',0
aSff1_cdg	db 'sff1.cdg',0
aSff1b_cdg	db 'sff1b.cdg',0
aSff2_cdg	db 'sff2.cdg',0
aSff2b_cdg	db 'sff2b.cdg',0
aSff3_cdg	db 'sff3.cdg',0
aSff3b_cdg	db 'sff3b.cdg',0
aSff2_pi	db 'sff2.pi',0
aSff4_cdg	db 'sff4.cdg',0
aSff4b_cdg	db 'sff4b.cdg',0
aSff5_cdg	db 'sff5.cdg',0
aSff5b_cdg	db 'sff5b.cdg',0
aSff8_cdg	db 'sff8.cdg',0
aSff8b_cdg	db 'sff8b.cdg',0
aSff9_cdg	db 'sff9.cdg',0
aSff9b_cdg	db 'sff9b.cdg',0
aSff6_cdg	db 'sff6.cdg',0
aSff6b_cdg	db 'sff6b.cdg',0
aSff7_cdg	db 'sff7.cdg',0
aSff7b_cdg	db 'sff7b.cdg',0
		db    0
include th04/gaiji/verdict[data].asm
aU_		db '点',0
aBd		db '．',0
aBu		db '％',0
aBd_0		db '．',0
aBu_0		db '％',0
public _VERDICT_TITLE, _LABEL_RANK, _LABEL_SCORE, _LABEL_MISSES
public _LABEL_BOMBS, _LABEL_GAME_COMPLETION, _LABEL_ENEMIES_KILLED
public _LABEL_ITEMS_COLLECTED, _LABEL_POINT_ITEMS_MAXED, _LABEL_GUTS
public _LABEL_SLOWDOWN, _LABEL_YOUR_SKILL, _TIMES_MSG, _TIMES_MSG_0
public _POINT_MSG_0, _ude_txt, _SKILL_UNKNOWN_MSG, _SLOWDOWN_NO_VERDICT_MSG
_VERDICT_TITLE	db '　　　　　　　 腕前判定',0
_LABEL_RANK		db '難易度',0
_LABEL_SCORE		db '最終得点',0
_LABEL_MISSES		db 'ミス回数',0
_LABEL_BOMBS	db 'ボム使用回数',0
_LABEL_GAME_COMPLETION	db 'ゲーム達成率',0
_LABEL_ENEMIES_KILLED	db '悪霊退治率',0
_LABEL_ITEMS_COLLECTED	db 'アイテム回収率',0
_LABEL_POINT_ITEMS_MAXED	db '得点アイテム最高点率',0
_LABEL_GUTS		db '気合い',0
_LABEL_SLOWDOWN	db '処理落ち率',0
_LABEL_YOUR_SKILL	db 'あなたの腕前',0
_TIMES_MSG		db '回',0
_TIMES_MSG_0	db '回',0
_POINT_MSG_0		db '点',0
_ude_txt	db '_ude.txt',0
_SKILL_UNKNOWN_MSG	db '？？？？？？点',0
_SLOWDOWN_NO_VERDICT_MSG	db '処理落ちによる判定不可',0
public _ude_pi
_ude_pi		db 'ude.pi',0
		db    0
include th04/hiscore/alphabet[data].asm
public _SCOREDAT_FN, _SCOREDAT_FN_0, _SCOREDAT_FN_1, _SCOREDAT_FN_2
_SCOREDAT_FN	db 'GENSOU.SCR',0
_SCOREDAT_FN_0	db 'GENSOU.SCR',0
_SCOREDAT_FN_1	db 'GENSOU.SCR',0
_SCOREDAT_FN_2	db 'GENSOU.SCR',0
public _hi01_pi, _scnum2_bft, _SLOW_MODE_MSG_SHADOW, _SLOW_MODE_MSG
public _BGM_NAME_FN
_hi01_pi	db 'hi01.pi',0
_scnum2_bft	db 'scnum2.bft',0
_SLOW_MODE_MSG_SHADOW	db 'スローモードでのプレイでは、スコアは記録されません',0
_SLOW_MODE_MSG	db 'スローモードでのプレイでは、スコアは記録されません',0
_BGM_NAME_FN	db 'name',0
		db    0

	.data?

	extern _resident:dword

	; libs/master.lib/vs[bss].asm
	extern vsync_Count1:word

	; th01/hardware/vram_planes[bss].asm
	extern _VRAM_PLANE_B:dword

	; th02/formats/pi_slots[bss].asm
	extern _pi_buffers:dword:6
	extern _pi_headers:PiHeader:6

include th02/snd/load[bss].asm
include th04/mem[bss].asm
include th04/hardware/input[bss].asm
include th04/formats/cdg[bss].asm
include th03/cutscene/cutscene[bss].asm

public _cdg_slot, _radial_angle, _dissolve_put_func
_cdg_slot          	db ?
_radial_angle     	db ?
_dissolve_put_func	dw ?

		db 2 dup(?)
public _skill_stash_quarter
_skill_stash_quarter	db ?
		db    ?	;
public _skill, _verdict_rank, _verdict_line
_skill	dd ?
_verdict_rank	db ?
_verdict_line	db    ?	;
		db 27 dup(?)
byte_124EF	db ?
		db 2 dup(?)
include th04/formats/scoredat[bss].asm
include th03/hiscore/regist[bss].asm
public _rank, _playchar
_rank	db ?
_playchar	db ?

		end
