;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	50C37C4BDDEC04B753524F5D3B030A96

; File Name   :	th04/MAINE.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-126D0h Loaded length: 10062h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'E'

include ReC98.inc
include th04/th04.inc
include th04/hardware/grppsafx.inc

group_01 group maine_01_TEXT, SCORE_TEXT

; ===========================================================================

; Segment type:	Pure code
_TEXT segment word public 'CODE' use16
	extern PALETTE_BLACK_IN:proc
	extern PALETTE_BLACK_OUT:proc
	extern EGC_OFF:proc
	extern FILE_APPEND:proc
	extern FILE_CLOSE:proc
	extern FILE_READ:proc
	extern FILE_ROPEN:proc
	extern FILE_SEEK:proc
	extern FILE_WRITE:proc
	extern GRCG_SETCOLOR:proc
	extern GAIJI_PUTCA:proc
	extern GAIJI_PUTSA:proc
	extern GRAPH_COPY_PAGE:proc
	extern GRAPH_PI_FREE:proc
	extern PALETTE_SHOW:proc
	extern IRAND:proc
	extern TEXT_CLEAR:proc
	extern SUPER_FREE:proc
	extern SUPER_ENTRY_BFNT:proc
	extern SUPER_PUT:proc
	extern GRAPH_GAIJI_PUTS:proc
	extern GRAPH_GAIJI_PUTC:proc
_TEXT ends

; ===========================================================================

maine_01_TEXT segment byte public 'CODE' use16
		assume cs:group_01
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing

; THIS DUMP'S CONTRIBUTION TO MAINE_01_TEXT IS NOW EMPTY, and with
; SCORE_TEXT already empty, th04_maine.asm contributes no code to
; TH04's MAINE.EXE at all. Only _DATA, .data? and the extern/procdesc
; blocks are left, and none of those emit anything into a code segment.
;
; The staff roll -- staffroll_animate() and the seven procs of its CDG
; dissolve effect -- now lives in th04/end/staffroll.cpp and
; th04/end/staff_dissolve.cpp, which th04/staff.cpp includes ahead of
; everything else it already carried. That object is the LAST one in TH04's
; MAINE.EXE link list and by this point contributed the whole tail of this
; segment, so the last tail lift simply grows its head to the segment's
; start: kb/codegen/0098, no carve, no new segment, no group-list edit and
; no Tupfile.lua line, for the eighth time in this dump.
;
; kb/codegen/0121: the two `assume` directives above are the segment's own
; and stay; none of the deleted bodies carried one.
;
; Nothing may be added here. This segment's contribution is closed.

; The verdict screen's four digit renderers -- graph_3_digit_put(),
; graph_score_and_ten_put(), skill_apply_and_graph_percentage() and
; graph_fraction_of_million_put(), in that order -- now live in
; th04/end/verdict_digits.cpp, which th04/staff.cpp includes ahead of
; verdict_guts.cpp. ONE file already served TH05's four; this parcel opened
; its GAME==4 arms, and only graph_score_and_ten_put() needed a second body
; (TH04's takes no parameters and renders eight raw digits where TH05's
; takes three and renders nine).
;
; Another kb/codegen/0098 tail lift into the object that already contributes
; to this segment immediately behind this dump. They had to come out
; together with the guts row below them: that row alone left its generated
; jump table one byte early, and only an odd-length prefix in the same
; object fixes that (kb/codegen/0096). None of the four deleted bodies
; contained an `assume` (kb/codegen/0121).
;
; The four gaiji suffixes they render stay in this dump's _DATA and are
; published there as _POINT_MSG, _DOT_MSG, _PERCENT_MSG and _DOT_MSG_0.

; skill_apply_and_graph_guts() -- the verdict screen's guts row, a handicap
; bonus over the continues, the bombs, Turbo Mode and the graze count plus a
; random term bounded by the share of items missed -- now lives in
; th04/end/verdict_guts.cpp, which th04/staff.cpp includes immediately
; before verdict_stats.cpp so that the two lifted bodies stay in dump order.
; Another kb/codegen/0098 tail lift into the object that already contributes
; to this segment immediately behind this dump: no carve, no new segment, no
; group-list edit and no Tupfile.lua line. Its dense continues jump table
; went with it, Turbo C++ generates that after the epilogue, and the deleted
; body contained no `assume` (kb/codegen/0121).

; verdict_stats_put_and_wait() -- the twelve labels and their values, the
; [skill] computation and its clamp, the `_ude.txt` verdict line, then the
; wait and the fade-out -- now lives in th04/end/verdict_stats.cpp, which
; th04/staff.cpp includes immediately BEFORE verdict_animate.cpp. That
; object is the LAST one in TH04's MAINE.EXE link list and already
; contributes to this segment immediately BEHIND this dump, so the lifted
; body lands at its original address by growing that contribution's head
; into the hole this deletion leaves: a kb/codegen/0098 tail lift, no
; carve, no new segment, no group-list edit and no Tupfile.lua line.
;
; Its two `jmp cs:` jump tables (`off_C0E2` and `off_C0EE`) went with it --
; Turbo C++ generates both after the epilogue -- and the deleted body
; contained no `assume` (kb/codegen/0121), so the state the rest of this
; contribution is assembled under is unchanged.
;
; The eighteen strings it passed stay in this dump's _DATA and are published
; there under C names, because the 'times' and 'point' counters each appear
; twice byte-identically below and `-d` would merge a C++ literal pair into
; one. See _TIMES_MSG / _TIMES_MSG_0 and _POINT_MSG_0 next to aU_.

; verdict_animate() now lives in th04/end/verdict_animate.cpp, which
; th04/staff.cpp includes. That object is the LAST one in TH04's MAINE.EXE
; link list and emitted nothing at all until now -- only an empty,
; auto-named STAFF_TEXT segment -- so a -zCMAINE_01_TEXT -zPgroup_01 body in
; it lands immediately BEHIND this contribution, at the address this proc
; already had. A kb/codegen/0098 tail lift: no carve, no new segment, no
; group-list edit and no Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`, so the state the
; rest of this contribution is assembled under is unchanged.
;
; Nothing may be added BELOW this line: the tail of this contribution is now
; the seam that every further lift out of this segment grows into.
maine_01_TEXT ends

SCORE_TEXT segment byte public 'CODE' use16
	@HISCORE_SCOREDAT_LOAD_FOR$Q10PLAYCHAR_T procdesc pascal near \
		playchar:byte
	@hiscore_scoredat_save$qv procdesc near

	; regist_score_enter_from_resident() now lives in
	; th04/hiscore/regist_enter.cpp, which th04/hiscore/end.cpp includes at
	; its very end -- and th04/hi_end.cpp's object already contributed to
	; this segment immediately AHEAD of this root contribution, so the
	; lifted body lands at its own original address by growing that object's
	; tail into the hole (kb/codegen/0098 + 0114). It was the FIRST proc of
	; this root contribution; nothing else moved, no carve, no new segment,
	; no group-list edit and no Tupfile.lua line were needed.
	;
	; kb/codegen/0121: the deleted body contained no `assume`, and the two
	; procdescs above it emit nothing, so the state this contribution is
	; assembled under is unchanged and there is nothing to restore.
	@regist_score_enter_from_resident$qv procdesc near
	@SCORE_PUT$QIUC procdesc pascal near \
		place:word, playchar:byte
	@STAGE_PUT$QIII procdesc pascal near \
		place:word, playchar:word, gaiji:word
	@NAME_PUT$QI10PLAYCHAR_TUC procdesc pascal near \
		place:word, playchar:byte, cursor:byte
	@PLACE_PUT$QIUC procdesc pascal near \
		place:word, playchar:byte
	@PLACES_PUT$QUC procdesc pascal near \
		playchar:byte
	@ALPHABET_PUTCA$QIIUI procdesc pascal near \
		col:word, row:word, atrb:word

; ALL SIX functions of this dump's high score table cluster now live in
; th04/hiscore/regist_view.cpp -- score_put(), stage_put(), name_put(),
; place_put(), places_put() and alphabet_putca(), in that order,
; immediately after regist_score_enter_from_resident() at the tail of
; th04/hi_end.cpp's SCORE_TEXT contribution, i.e. exactly where this
; block used to continue. One body serves all six in both games; TH04
; takes the two-player-character arms of its `#if`s, and the TEXT RAM
; arms that TH05 has no counterpart for.

; kb/codegen/0121: none of the deleted bodies contained an `assume`, so
; the state the rest of this contribution is assembled under is unchanged.
; regist_menu() -- the whole name registration screen -- now lives in
; th04/hiscore/regist_menu.cpp, the last #include of th04/hiscore/end.cpp.
; ONE body serves both games, as it already does for the six functions
; above; TH05's copy is appended to th05/regist.cpp instead, because its
; version calls three glyph ball functions that live there. th04/hi_end.cpp
; contributes to this segment immediately before this dump, so the lifted
; body lands at its original address by growing that contribution: another
; kb/codegen/0098 head lift, no carve, no new segment, no Tupfile.lua line.
; Its `jmp cs:` switch table went with it, and it contained no `assume`
; (kb/codegen/0121). The strings it passes stay in this dump's _DATA and are
; published there -- see _hi01_pi and the three below it -- because the two
; Japanese messages are byte-identical to each other and `-d` would merge a
; C++ literal pair into one.
; Nothing may be added above this line.

; egc_copy_rect_1_to_0_16_near() -- the `near` page 1 -> page 0 EGC
; rectangle copy that regist_menu() unblits through -- now lives in
; th04/hiscore/regist_unblit.cpp, together with the static egc_start_copy()
; helper it calls, which is th01/hardware/egc.inc's EGC_START_COPY_INLINED
; spelled in C++ (kb/codegen/0051 for the six 16-bit register writes,
; kb/codegen/0088 for the five immediate-form byte writes).
; th04/hiscore/end.cpp includes that file immediately after regist_menu.cpp,
; i.e. at the very end of th04/hi_end.cpp's SCORE_TEXT contribution -- the
; object that already sat immediately before this one -- so both bodies land
; at their original addresses by growing that contribution's tail
; (kb/codegen/0098 + 0114). No carve, no new segment, no group-list edit and
; no Tupfile.lua line.
;
; kb/codegen/0121: neither deleted body contained an `assume`, so the state
; this contribution is assembled under is unchanged and there is nothing to
; restore.
;
; THIS DUMP'S CONTRIBUTION TO SCORE_TEXT IS NOW EMPTY. Everything left in
; the block above is procdescs and externs, which emit nothing. Nothing may
; be added to it.

SCORE_TEXT	ends

; ===========================================================================

SHARED segment byte public 'CODE' use16
include th02/snd/snd.inc
	extern @FRAME_DELAY$QI:proc
	extern @PI_PALETTE_APPLY$QI:proc
	extern @PI_PUT_8$QIII:proc
	extern @PI_LOAD$QINXC:proc
	extern @INPUT_WAIT_FOR_CHANGE$QI:proc
	extern @POLAR$QIII:proc
	extern SND_KAJA_INTERRUPT:proc
	extern SND_DELAY_UNTIL_MEASURE:proc
	extern CDG_PUT_PLANE:proc
	extern SND_LOAD:proc
	extern GRAPH_PUTSA_FX:proc
	extern CDG_PUT_8:proc
	extern @input_reset_sense$qv:proc
	extern @input_sense$qv:proc
	extern _bgimage_snap:proc
	extern _bgimage_free:proc
	extern BGIMAGE_PUT_RECT_16:proc
	extern CDG_LOAD_SINGLE_NOALPHA:proc
	extern CDG_LOAD_SINGLE:proc
	extern CDG_FREE:proc
	extern CDG_FREE_ALL:proc
SHARED ends

	.data

	; libs/master/pal[data].mas
	extern PaletteTone:word

	; libs/master/rand[data].mas
	extern random_seed:dword

	; libs/master.lib/sin8[data].asm
	extern _SinTable8:word:256
	extern _CosTable8:word:256

	; th04/hardware/grppsafx.asm
	extern _graph_putsa_fx_func:word

include th03/snd/se_state[data].asm
include th04/hardware/bgimage[data].asm
include th03/formats/cdg[data].asm
include th03/formats/pi_put_masked[data].asm
include th03/cutscene/cutscene[data].asm
public _sff1_pi, _sff2_pi, _staff_bgm
public _sff1_cdg, _sff1b_cdg, _sff2_cdg, _sff2b_cdg, _sff3_cdg, _sff3b_cdg
public _sff4_cdg, _sff4b_cdg, _sff5_cdg, _sff5b_cdg, _sff6_cdg, _sff6b_cdg
public _sff7_cdg, _sff7b_cdg, _sff8_cdg, _sff8b_cdg, _sff9_cdg, _sff9b_cdg
_sff1_pi	db 'sff1.pi',0
_staff_bgm		db 'staff',0
_sff1_cdg	db 'sff1.cdg',0
_sff1b_cdg	db 'sff1b.cdg',0
_sff2_cdg	db 'sff2.cdg',0
_sff2b_cdg	db 'sff2b.cdg',0
_sff3_cdg	db 'sff3.cdg',0
_sff3b_cdg	db 'sff3b.cdg',0
_sff2_pi	db 'sff2.pi',0
_sff4_cdg	db 'sff4.cdg',0
_sff4b_cdg	db 'sff4b.cdg',0
_sff5_cdg	db 'sff5.cdg',0
_sff5b_cdg	db 'sff5b.cdg',0
_sff8_cdg	db 'sff8.cdg',0
_sff8b_cdg	db 'sff8b.cdg',0
_sff9_cdg	db 'sff9.cdg',0
_sff9b_cdg	db 'sff9b.cdg',0
_sff6_cdg	db 'sff6.cdg',0
_sff6b_cdg	db 'sff6b.cdg',0
_sff7_cdg	db 'sff7.cdg',0
_sff7b_cdg	db 'sff7b.cdg',0
		db    0
include th04/gaiji/verdict[data].asm
public _POINT_MSG, _DOT_MSG, _PERCENT_MSG, _DOT_MSG_0
_POINT_MSG		db '点',0
_DOT_MSG		db '．',0
_PERCENT_MSG		db '％',0
_DOT_MSG_0		db '．',0
public _PERCENT_MSG_0
_PERCENT_MSG_0		db '％',0
public _VERDICT_TITLE, _LABEL_RANK, _LABEL_SCORE, _LABEL_MISSES
public _LABEL_BOMBS, _LABEL_GAME_COMPLETION, _LABEL_ENEMIES_KILLED
public _LABEL_ITEMS_COLLECTED, _LABEL_POINT_ITEMS_MAXED, _LABEL_GUTS
public _LABEL_SLOWDOWN, _LABEL_YOUR_SKILL, _TIMES_MSG, _TIMES_MSG_0
public _POINT_MSG_0, _ude_txt, _SKILL_UNKNOWN_MSG, _SLOWDOWN_NO_VERDICT_MSG
_VERDICT_TITLE	db '　　　　　　　 腕前判定',0
_LABEL_RANK		db '難易度',0
_LABEL_SCORE		db '最終得点',0
_LABEL_MISSES		db 'ミス回数',0
_LABEL_BOMBS	db 'ボム使用回数',0
_LABEL_GAME_COMPLETION	db 'ゲーム達成率',0
_LABEL_ENEMIES_KILLED	db '悪霊退治率',0
_LABEL_ITEMS_COLLECTED	db 'アイテム回収率',0
_LABEL_POINT_ITEMS_MAXED	db '得点アイテム最高点率',0
_LABEL_GUTS		db '気合い',0
_LABEL_SLOWDOWN	db '処理落ち率',0
_LABEL_YOUR_SKILL	db 'あなたの腕前',0
_TIMES_MSG		db '回',0
_TIMES_MSG_0	db '回',0
_POINT_MSG_0		db '点',0
_ude_txt	db '_ude.txt',0
_SKILL_UNKNOWN_MSG	db '？？？？？？点',0
_SLOWDOWN_NO_VERDICT_MSG	db '処理落ちによる判定不可',0
public _ude_pi
_ude_pi		db 'ude.pi',0
		db    0
include th04/hiscore/alphabet[data].asm
public _SCOREDAT_FN, _SCOREDAT_FN_0, _SCOREDAT_FN_1, _SCOREDAT_FN_2
_SCOREDAT_FN	db 'GENSOU.SCR',0
_SCOREDAT_FN_0	db 'GENSOU.SCR',0
_SCOREDAT_FN_1	db 'GENSOU.SCR',0
_SCOREDAT_FN_2	db 'GENSOU.SCR',0
public _hi01_pi, _scnum2_bft, _SLOW_MODE_MSG_SHADOW, _SLOW_MODE_MSG
public _BGM_NAME_FN
_hi01_pi	db 'hi01.pi',0
_scnum2_bft	db 'scnum2.bft',0
_SLOW_MODE_MSG_SHADOW	db 'スローモードでのプレイでは、スコアは記録されません',0
_SLOW_MODE_MSG	db 'スローモードでのプレイでは、スコアは記録されません',0
_BGM_NAME_FN	db 'name',0
		db    0

	.data?

	extern _resident:dword

	; libs/master.lib/vs[bss].asm
	extern vsync_Count1:word

	; th01/hardware/vram_planes[bss].asm
	extern _VRAM_PLANE_B:dword

	; th02/formats/pi_slots[bss].asm
	extern _pi_buffers:dword:6
	extern _pi_headers:PiHeader:6

include th02/snd/load[bss].asm
include th04/mem[bss].asm
include th04/hardware/input[bss].asm
include th04/formats/cdg[bss].asm
include th03/cutscene/cutscene[bss].asm

public _cdg_slot, _radial_angle, _dissolve_put_func
_cdg_slot          	db ?
_radial_angle     	db ?
_dissolve_put_func	dw ?

		db 2 dup(?)
public _skill_stash_quarter
_skill_stash_quarter	db ?
		db    ?	;
public _skill, _verdict_rank, _verdict_line
_skill	dd ?
_verdict_rank	db ?
_verdict_line	db    ?	;
		db 27 dup(?)
byte_124EF	db ?
		db 2 dup(?)
include th04/formats/scoredat[bss].asm
include th03/hiscore/regist[bss].asm
public _rank, _playchar
_rank	db ?
_playchar	db ?

		end
