;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	57F21130457B229B7ED74E30D2B6E6E5

; File Name   :	th05/MAINE.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-1C6F0h Loaded length: 128A6h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'E'

include ReC98.inc
include th05/th05.inc
include th01/math/subpixel.inc
include th04/hardware/grppsafx.inc

group_01 group CUTSCENE_TEXT, maine_01_TEXT, SCORE_TEXT, maine_01__TEXT

; ===========================================================================

_TEXT segment word public 'CODE' use16
	extern PALETTE_BLACK_IN:proc
	extern PALETTE_BLACK_OUT:proc
	extern FILE_APPEND:proc
	extern FILE_CLOSE:proc
	extern FILE_READ:proc
	extern FILE_ROPEN:proc
	extern FILE_SEEK:proc
	extern FILE_WRITE:proc
	extern GRCG_BOXFILL:proc
	extern GRCG_BYTEBOXFILL_X:proc
	extern GRCG_CIRCLEFILL:proc
	extern GRC_SETCLIP:proc
	extern GRCG_HLINE:proc
	extern GRCG_SETCOLOR:proc
	extern GRCG_VLINE:proc
	extern GAIJI_PUTCA:proc
	extern GAIJI_PUTSA:proc
	extern GRAPH_COPY_PAGE:proc
	extern IATAN2:proc
	extern IHYPOT:proc
	extern PALETTE_SHOW:proc
	extern IRAND:proc
	extern TEXT_CLEAR:proc
	extern TEXT_PUTSA:proc
	extern SUPER_FREE:proc
	extern SUPER_ENTRY_BFNT:proc
	extern SUPER_PUT_RECT:proc
	extern SUPER_PUT:proc
	extern SUPER_CONVERT_TINY:proc
	extern SUPER_PUT_TINY_SMALL:proc
	extern GRAPH_GAIJI_PUTS:proc
	extern GRAPH_GAIJI_PUTC:proc
_TEXT ends

; ===========================================================================

CUTSCENE_TEXT segment byte public 'CODE' use16
		assume cs:group_01
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing
CUTSCENE_TEXT ends

maine_01_TEXT segment byte public 'CODE' use16
	@wait_flip_and_check_measure_targ$qv procdesc near
maine_01_TEXT ends

SCORE_TEXT segment byte public 'CODE' use16
	; The only two symbols this dump still reaches across the segment
	; boundary: staffroll_animate(), in maine_01__TEXT, calls both, and the
	; calls stay near because group_01 spans both segments. Every other
	; procdesc that used to stand here went with verdict_stats_put(), the
	; last proc of this block and the last caller of any of them.
	@verdict_stage_scores_put$qv procdesc near
	@verdict_stats_put$qv procdesc near
	@verdict_comment_put$qv procdesc near

; The C++ contribution to SCORE_TEXT that precedes this block now ends
; with alphabet_putca() (th04/hiscore/regist_view.cpp); that file's other
; five functions, and regist_score_enter_from_resident()
; (th04/hiscore/regist_enter.cpp), are the six before it. All seven were
; lifted out of the head of this block. Nothing may be added above this
; line.


; ALL SIX functions of this dump's high score table cluster now live in
; th04/hiscore/regist_view.cpp -- score_put(), stage_put(), name_put(),
; place_put(), places_put() and alphabet_putca(), in that order,
; immediately after regist_score_enter_from_resident() at the tail of
; th05/hi_end.cpp's SCORE_TEXT contribution, i.e. exactly where this
; block used to continue. Their four `jmp cs:` switch tables and the
; alignment bytes ahead of three of them went with them; Turbo C++
; emits all of it from the `switch(playchar)` statements.

; kb/codegen/0121: none of the deleted bodies contained an `assume`, so
; the state the rest of this contribution is assembled under is unchanged.
; The three procs that used to open this block -- sub_BD1E, sub_BD46 and
; sub_BE76, TH05's glyph ball animation for the name registration screen --
; now live in th05/regist.cpp. That object contributes to SCORE_TEXT
; immediately ahead of this one (Tupfile.lua lists it directly before this
; dump), so the lifted bodies land at their original addresses by growing
; that contribution: a kb/codegen/0098 head lift with no carve, no new
; segment, no group-list edit and no Tupfile.lua line. Their two `jmp cs:`
; switch tables and the alignment byte ahead of each went with them, and
; none of them contained an `assume` either (kb/codegen/0121). The proc
; that followed them went the same way, into the same object, as
; glyphballs_rush_and_wait().
; Nothing may be added above this line.

; Still needed to type _glyphballs in this dump's BSS. The GBP_* phase
; equates that used to sit here went with regist_menu(), which was their
; last user in this file; th05/regist.cpp declares them as an enum.
glyphball_t struc
	GB_phase	db ?
	GB_glyph	db ?
	GB_pos	motion_t <?>
	GB_target	Point <?>
	GB_angle	db ?
	GB_speed	db ?
	GB_phase_frame	dw ?
		db 6 dup (?)
glyphball_t ends


; ...and regist_menu(), the name registration screen itself, is now the tail
; of th05/regist.cpp -- the same object, immediately after
; glyphballs_rush_and_wait(), which it calls. ONE body serves both games;
; TH04's copy of it is the last #include of th04/hiscore/end.cpp. Same
; kb/codegen/0098 head lift as everything above, and it too contained no
; `assume` (kb/codegen/0121). The strings it passes stay in this dump's
; _DATA and are published there, because the two Japanese messages are
; byte-identical to each other and `-d` would merge a C++ literal pair into
; one.
; Nothing may be added above this line.


; graph_3_digit_put() now lives in th04/end/verdict_digits.cpp, the last
; #include of th05/regist.cpp -- the object that already contributed to this
; segment immediately AHEAD of this block, so the lifted body lands at its
; original address by growing that object's tail into the hole
; (kb/codegen/0098 + 0114). It was the FIRST proc of this contribution;
; nothing else moved, no carve, no new segment, no group-list edit and no
; Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`, so the state the
; rest of this contribution is assembled under is unchanged.
;
; Nothing may be added above this line.


; This block's second proc -- the nine-digit LEBCD score renderer that
; appends the Shift-JIS points label -- now lives in
; th04/end/verdict_digits.cpp as
; graph_score_and_ten_put(), immediately after graph_3_digit_put() and
; therefore immediately after the previous head lift. th05/regist.cpp
; contributes to this segment right before this block, so it lands at its
; original address by growing that object's tail (kb/codegen/0098 + 0114).
; No carve, no new segment, no group-list edit, no Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added above this line.


; skill_apply_and_graph_percentage() and graph_fraction_of_million_put()
; now live in th04/end/verdict_digits.cpp, after graph_score_and_ten_put()
; and therefore still in this block's original order. th05/regist.cpp
; contributes to this segment right before this block, so both land at
; their original addresses by growing that object's tail
; (kb/codegen/0098 + 0114). No carve, no new segment, no group-list edit,
; no Tupfile.lua line.
;
; kb/codegen/0121: neither deleted body contained an `assume`.
;
; Nothing may be added above this line.


; skill_apply_and_graph_guts() -- the verdict screen's handicap bonus row
; -- now lives in th05/end/verdict_guts.cpp, the next #include of
; th05/regist.cpp after th04/end/verdict_digits.cpp. That object
; contributes to this segment immediately ahead of this block, so the
; lifted body lands at its original address by growing that object's tail
; into the hole (kb/codegen/0098 + 0114). It was the FIRST proc of this
; contribution; nothing else moved, no carve, no new segment, no
; group-list edit and no Tupfile.lua line. The six-entry `jmp cs:`
; continues table Turbo C++ generates after the epilogue went with it,
; and it needed no alignment pad, unlike TH04's: the table's address is
; already even, so `-a2` and `-a1` emit the same bytes there.
;
; kb/codegen/0121: the deleted body contained no `assume`, so the state
; the rest of this contribution is assembled under is unchanged.
;
; Nothing may be added above this line.


; ...and verdict_comment_2_num(), which picks the record this screen reads
; as the SECOND _ude.txt comment line, is now
; th05/end/verdict_comment_num.cpp, the #include right after it in the
; same object and therefore still in this block's original order. Same
; kb/codegen/0098 head lift, and TH04 has no counterpart to share.
;
; kb/codegen/0042: the original keeps a BP frame for a function with
; neither parameters nor locals, which the build's global `-k-` would
; drop, so that file restores `-k` around the body and `-k-` after it.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added above this line.


; verdict_stats_put() -- the verdict screen's body, and the LAST proc of
; this block -- now lives in th05/end/verdict_stats.cpp, the final
; #include of th05/regist.cpp. That object contributes to this segment
; immediately ahead of this block, so the body lands at its original
; address by growing that object's tail into the hole
; (kb/codegen/0098 + 0114). Its two `jmp cs:` switch tables went with it,
; and they needed no alignment pad: the first one's offset is ODD, so
; `-a1` reproduces it and `-a2` would not.
;
; The zero-byte `public _verdict_stats_put` alias that used to stand here
; is GONE, not moved: it existed so th04/end/verdict_animate.cpp could
; call INTO this dump, and now that C++ defines the body it would be a
; duplicate symbol. staffroll_animate() calls the body too, so the call
; direction has flipped in both directions at once and the linkage went
; with it: plain C++ linkage, reached from this dump by the mangled
; @verdict_stats_put$qv, exactly the flip state/notes/verdict_comment_put.md
; predicted this symbol would need.
;
; Lifting it also retired one of this file's hand-encoded instructions:
; a three-byte `db` stood in for the near jump out of the RANK_NORMAL arm,
; under upstream's own note that TASM would not assemble it after
; scoredat_load_for() was decompiled. Turbo C++ emits those bytes itself.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; **THIS BLOCK IS NOW EMPTY.** th05_maine.asm contributes zero bytes to
; SCORE_TEXT, so th05/regist.cpp's contribution runs straight into
; th05/staff.cpp's. Nothing may be added between them, above this line or
; below it.

; The verdict screen's two _ude.txt comment lines now live in
; th05/end/verdict_comment.cpp, at the head of th05/staff.cpp's
; contribution to this segment -- the third body lifted out of this
; tail, and the first of the three in emitted order. staffroll_animate()
; still calls it from maine_01__TEXT, which stays a near call because
; group_01 spans both segments.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added below this line.


; The verdict screen's entry point is now ONE body shared with TH04, in
; th04/end/verdict_animate.cpp, reached from th05/staff.cpp -- the object
; that contributes to this segment immediately after this block. It is
; the second lift out of this tail, so it sits ahead of
; verdict_stage_scores_put() in that file and lands at its original
; address. No carve, no new segment, no group-list edit, no Tupfile.lua
; line.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added below this line.


; This block's last proc -- the verdict screen's per-stage score table --
; now lives in th05/end/verdict_scores.cpp as verdict_stage_scores_put(),
; included from th05/staff.cpp. That object contributes to this segment
; immediately after this block, so the body lands at its original address
; by growing that object's head (kb/codegen/0099 + 0114). No carve, no new
; segment, no group-list edit, no Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added below this line.
SCORE_TEXT	ends

maine_01__TEXT	segment	byte public 'CODE' use16
	; Lifted out of the head of this block into th05/space.cpp; still
	; called from staffroll_animate() below.
	@space_reset$qv procdesc near
	@orb_gather_start$qv procdesc near
	@orb_gather_end$qv procdesc near
	@orb_burst$qv procdesc near
	@space_update$qv procdesc near
	@orb_particle_emit$qv procdesc near
	@orb_trails_advance$qv procdesc near
	@orb_gather_animate$qv procdesc near
	@orb_phase_update$qv procdesc near
	@rain_particle_spawn$qv procdesc near
	@rain_phase_update$qv procdesc near

	@SPACE_WINDOW_SET$QIIII procdesc pascal near \
		center_x:word, center_y:word, w:word, h:word

ORB_PARTICLE_CELS = 6
PAT_ORB_PARTICLE = 0
PAT_ORB_PARTICLE_last = (PAT_ORB_PARTICLE + ORB_PARTICLE_CELS - 1)
PAT_STAR_BIG = (PAT_ORB_PARTICLE + ORB_PARTICLE_CELS - 1) + 1
PAT_STAR_SMALL = PAT_STAR_BIG + 1

ORB_RADIUS_FULL = 16
ORB_W = 32
ORB_H = 32

X_RIGHT = 0
X_LEFT = 1

orb_particle_t struc
	OP_center_x	dd ?
	OP_center_y	dd ?
	OP_velocity	Point <?>
	OP_patnum_tiny	dw ?
	OP_speed	dw ?
	OP_gather_frame dw ?
	OP_angle	db ?
	OP_al_radius	label byte
	OP_al_rain_sway_x_direction	label byte
		db ?
orb_particle_t ends

ORB_PARTICLE_COUNT = 64
ORB_TRAIL_COUNT = 8
STAR_COUNT = 48
ORB_INDEX = ORB_PARTICLE_COUNT
orb	equ <_particles[ORB_INDEX * size orb_particle_t]>

; The scene reset -- scatter every particle and star across a fresh space
; window, clear the orb, its trails and the camera -- now lives in
; th05/space.cpp as space_reset(). That object contributes to this segment
; immediately AHEAD of this block (Tupfile.lua lists th05/space.cpp
; directly before th05_maine.asm), so the lifted body lands at its original
; address by growing that contribution: a kb/codegen/0098 head lift.
;
; This segment had no C++ contribution at all before, so the object and its
; Tupfile.lua line are new, and that line is POSITION-CRITICAL -- listed
; after this dump it would land at the segment's tail instead
; (kb/codegen/0112 + 0114).
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added above this line.

; The rest of the scene's own animation now lives in th05/space.cpp, in the
; same order, as orb_gather_start(), orb_gather_end(), orb_burst() and
; space_update(). Together with space_reset() above they are the whole head of
; this block, and they land at their original addresses by growing that
; object's contribution, which Tupfile.lua lists directly before this dump.
;
; The middle three have neither parameters nor stack locals, so they needed
; kb/codegen/0042's per-function -k. wrapper to keep the BP frame the build's
; global -k- would otherwise have dropped.
;
; kb/codegen/0121: none of the deleted bodies contained an `assume`.
;
; Nothing may be added above this line.


; The orb's own two per-frame helpers went the same way, into th05/space.cpp,
; as orb_particle_emit() and orb_trails_advance(). They were forced into this
; parcel by the naming gate rather than by layout: space_update() calls both,
; and tools/re/naming_precheck.py correctly refuses a `sub_XXXX` spelling in
; C++ whose search does not fail (kb/conventions/naming-precedents.md section
; 3). Defining them was cheaper and more honest than naming them in place.
;
; kb/codegen/0121: neither deleted body contained an `assume`.
;
; Nothing may be added above this line.

; The gather animation and the two phase scripts that drive the rest of the
; scene now live in th05/space.cpp too, in the same order, as
; orb_gather_animate(), orb_phase_update(), rain_particle_spawn() and
; rain_phase_update(). They extend the same contiguous prefix as the seven
; bodies above, into the object Tupfile.lua lists directly before this dump.
;
; rain_particle_spawn() was NOT forced in by the naming gate this time --
; rain_phase_update() is its only caller and follows it in dump order, so the
; contiguous head lift covers it either way. The whole remaining call graph is
; a DAG whose every edge points backwards in address order, which is why no
; further clustering is forced.
;
; orb_gather_animate(), rain_particle_spawn() and rain_phase_update() have
; neither parameters nor stack locals, so all three needed kb/codegen/0149's
; per-function -k. wrapper; orb_phase_update() has one stack local and did not.
;
; kb/codegen/0121: none of the four deleted bodies contained an `assume`.
;
; Nothing may be added above this line.
;
; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DBE6	proc near

var_2C		= byte ptr -2Ch
var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8
arg_6		= word ptr  0Ah
arg_8		= word ptr  0Ch
arg_A		= word ptr  0Eh

		enter	2Ch, 0
		push	si
		push	di
		mov	di, [bp+arg_8]
		cmp	[bp+arg_2], 0
		jge	short loc_DBFF
		mov	byte_11846, 1
		mov	al, 1
		jmp	loc_DCF6
; ---------------------------------------------------------------------------

loc_DBFF:
		mov	ax, [bp+arg_6]
		mov	bx, 10h
		cwd
		idiv	bx
		add	ax, 7
		cmp	ax, [bp+arg_2]
		jge	short loc_DC48
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		mov	ax, [bp+arg_A]
		mov	bx, 8
		cwd
		idiv	bx
		push	ax
		push	di
		mov	ax, [bp+arg_A]
		add	ax, [bp+arg_6]
		dec	ax
		cwd
		idiv	bx
		push	ax
		mov	ax, di
		add	ax, [bp+arg_4]
		dec	ax
		push	ax
		call	grcg_byteboxfill_x
		GRCG_OFF_CLOBBERING dx
		mov	al, 2
		jmp	loc_DCF6
; ---------------------------------------------------------------------------

loc_DC48:
		mov	bx, 8
		mov	ax, [bp+arg_A]
		cwd
		idiv	bx
		mov	[bp+arg_A], ax
		mov	bx, 10h
		mov	ax, di
		cwd
		idiv	bx
		mov	di, ax
		mov	ax, [bp+arg_6]
		cwd
		idiv	bx
		mov	[bp+arg_6], ax
		mov	ax, [bp+arg_4]
		cwd
		idiv	bx
		mov	[bp+arg_4], ax
		cmp	[bp+arg_0], 0
		jle	short loc_DC7D
		mov	[bp+var_2], 0
		jmp	short loc_DC84
; ---------------------------------------------------------------------------

loc_DC7D:
		mov	ax, [bp+arg_6]
		dec	ax
		mov	[bp+var_2], ax

loc_DC84:
		xor	si, si
		jmp	short loc_DCD0
; ---------------------------------------------------------------------------

loc_DC88:
		cmp	[bp+arg_2], 7
		jl	short loc_DC9A
		lea	bx, [bp+var_2C]
		add	bx, [bp+var_2]
		mov	byte ptr ss:[bx], 152
		jmp	short loc_DCBA
; ---------------------------------------------------------------------------

loc_DC9A:
		cmp	[bp+arg_2], 0
		jge	short loc_DCAC
		lea	bx, [bp+var_2C]
		add	bx, [bp+var_2]
		mov	byte ptr ss:[bx], 2
		jmp	short loc_DCBA
; ---------------------------------------------------------------------------

loc_DCAC:
		lea	bx, [bp+var_2C]
		add	bx, [bp+var_2]
		mov	al, 159
		sub	al, byte ptr [bp+arg_2]
		mov	ss:[bx], al

loc_DCBA:
		mov	ax, si
		add	ax, ax
		add	ax, [bp+arg_A]
		cmp	ax, 50h	; 'P'
		jge	short loc_DCD5
		inc	si
		mov	ax, [bp+arg_0]
		add	[bp+var_2], ax
		dec	[bp+arg_2]

loc_DCD0:
		cmp	si, [bp+arg_6]
		jl	short loc_DC88

loc_DCD5:
		mov	[bp+si+var_2C],	0
		xor	si, si
		jmp	short loc_DCEF
; ---------------------------------------------------------------------------

loc_DCDD:
		push	[bp+arg_A]
		push	di
		push	ss
		lea	ax, [bp+var_2C]
		push	ax
		push	TX_BLACK
		call	gaiji_putsa
		inc	si
		inc	di

loc_DCEF:
		cmp	si, [bp+arg_4]
		jle	short loc_DCDD
		mov	al, 0

loc_DCF6:
		pop	di
		pop	si
		leave
		retn	0Ch
sub_DBE6	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DCFC	proc near

var_4     	= word ptr -4
var_2     	= word ptr -2
@@measure     	= word ptr  4
@@slot    	= word ptr  6
@@y_center	= word ptr  8
@@x_center	= word ptr  0Ah

		enter	4, 0
		push	si
		push	di
		mov	di, [bp+@@y_center]

		cdg_slot_offset	ax, [bp+@@slot]

		mov	si, ax
		mov	ax, [si+cdg_t.pixel_w]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	[bp+@@x_center], ax
		mov	ax, [si+cdg_t.pixel_h]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	di, ax
		cmp	word_11848, 1
		jg	loc_DDBC
		mov	ax, [si+cdg_t.pixel_w]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, 7
		mov	word_151C4, ax
		mov	word_151C6, 0
		inc	word_11848
		call	cdg_put_noalpha_8 pascal, [bp+@@x_center], di, [bp+@@slot]
		mov	[bp+var_2], 0
		jmp	short loc_DDB1
; ---------------------------------------------------------------------------

loc_DD5A:
		mov	[bp+var_4], 0
		jmp	short loc_DDA2
; ---------------------------------------------------------------------------

loc_DD61:
		mov	ax, [bp+@@x_center]
		mov	bx, 8
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		cmp	dx, 50h	; 'P'
		jge	short loc_DD9E
		mov	ax, [bp+@@x_center]
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		push	dx
		mov	ax, di
		mov	bx, 16
		cwd
		idiv	bx
		push	ax
		push	ds
		push	offset unk_1184C
		push	TX_BLACK + TX_REVERSE
		call	text_putsa

loc_DD9E:
		add	[bp+var_4], 10h

loc_DDA2:
		mov	ax, [si+2]
		cmp	ax, [bp+var_4]
		jge	short loc_DD61
		add	[bp+var_2], 10h
		add	di, 10h

loc_DDB1:
		mov	ax, [si+4]
		cmp	ax, [bp+var_2]
		jge	short loc_DD5A
		jmp	loc_DE6C
; ---------------------------------------------------------------------------

loc_DDBC:
		cmp	word_11848, 3
		jg	short loc_DE01
		inc	word_151C6
		mov	ax, word_151C6
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DDD8
		dec	word_151C4

loc_DDD8:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C4
		push	1
		call	sub_DBE6
		cmp	al, 1
		jnz	short loc_DE6C
		inc	word_11848
		mov	word_151C4, 0
		mov	word_151C6, 0
		jmp	short loc_DE6C
; ---------------------------------------------------------------------------

loc_DE01:
		mov	ax, measure_151E0
		cmp	ax, [bp+@@measure]
		jl	short loc_DE6C
		cmp	[bp+@@measure], 3996
		jz	short loc_DE6C
		cmp	word_11848, 4
		jnz	short loc_DE49
		inc	word_151C6
		mov	ax, word_151C6
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DE2C
		inc	word_151C4

loc_DE2C:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C4
		push	0FFFFh
		call	sub_DBE6
		cmp	al, 2
		jnz	short loc_DE6C
		inc	word_11848
		jmp	short loc_DE6C
; ---------------------------------------------------------------------------

loc_DE49:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	80FFFFh
		call	sub_DBE6
		mov	word_11848, 0
		mov	byte_11846, 1
		mov	ax, 1
		jmp	short loc_DE6E
; ---------------------------------------------------------------------------

loc_DE6C:
		xor	ax, ax

loc_DE6E:
		pop	di
		pop	si
		leave
		retn	8
sub_DCFC	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DE74	proc near

var_4     	= word ptr -4
var_2     	= word ptr -2
@@measure     	= word ptr  4
@@slot    	= word ptr  6
@@y_center	= word ptr  8
@@x_center	= word ptr  0Ah

		enter	4, 0
		push	si
		push	di
		mov	di, [bp+@@y_center]

		cdg_slot_offset	ax, [bp+@@slot]

		mov	si, ax
		mov	ax, [si+cdg_t.pixel_w]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	[bp+@@x_center], ax
		mov	ax, [si+cdg_t.pixel_h]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	di, ax
		cmp	word_1184A, 1
		jg	loc_DF34
		mov	ax, [si+cdg_t.pixel_w]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, 7
		mov	word_151C8, ax
		mov	word_151CA, 0
		inc	word_1184A
		call	cdg_put_noalpha_8 pascal, [bp+@@x_center], di, [bp+@@slot]
		mov	[bp+var_2], 0
		jmp	short loc_DF29
; ---------------------------------------------------------------------------

loc_DED2:
		mov	[bp+var_4], 0
		jmp	short loc_DF1A
; ---------------------------------------------------------------------------

loc_DED9:
		mov	ax, [bp+@@x_center]
		mov	bx, 8
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		cmp	dx, 50h	; 'P'
		jge	short loc_DF16
		mov	ax, [bp+@@x_center]
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		push	dx
		mov	ax, di
		mov	bx, 16
		cwd
		idiv	bx
		push	ax
		push	ds
		push	offset unk_1184F
		push	TX_BLACK + TX_REVERSE
		call	text_putsa

loc_DF16:
		add	[bp+var_4], 10h

loc_DF1A:
		mov	ax, [si+cdg_t.pixel_w]
		cmp	ax, [bp+var_4]
		jge	short loc_DED9
		add	[bp+var_2], 10h
		add	di, 10h

loc_DF29:
		mov	ax, [si+cdg_t.pixel_h]
		cmp	ax, [bp+var_2]
		jge	short loc_DED2
		jmp	loc_DFE4
; ---------------------------------------------------------------------------

loc_DF34:
		cmp	word_1184A, 3
		jg	short loc_DF79
		inc	word_151CA
		mov	ax, word_151CA
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DF50
		dec	word_151C8

loc_DF50:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C8
		push	1
		call	sub_DBE6
		cmp	al, 1
		jnz	short loc_DFE4
		inc	word_1184A
		mov	word_151C8, 0
		mov	word_151CA, 0
		jmp	short loc_DFE4
; ---------------------------------------------------------------------------

loc_DF79:
		mov	ax, measure_151E0
		cmp	ax, [bp+@@measure]
		jl	short loc_DFE4
		cmp	[bp+@@measure], 3996
		jz	short loc_DFE4
		cmp	word_1184A, 4
		jnz	short loc_DFC1
		inc	word_151CA
		mov	ax, word_151CA
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DFA4
		inc	word_151C8

loc_DFA4:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C8
		push	0FFFFh
		call	sub_DBE6
		cmp	al, 2
		jnz	short loc_DFE4
		inc	word_1184A
		jmp	short loc_DFE4
; ---------------------------------------------------------------------------

loc_DFC1:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	80FFFFh
		call	sub_DBE6
		mov	word_1184A, 0
		mov	byte_11846, 1
		mov	ax, 1
		jmp	short loc_DFE6
; ---------------------------------------------------------------------------

loc_DFE4:
		xor	ax, ax

loc_DFE6:
		pop	di
		pop	si
		leave
		retn	8
sub_DE74	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DFEC	proc near

@@star_center		= word ptr -0Ah
@@trail_center		= word ptr -8
@@trail_col		= word ptr -6
@@y		= word ptr -4
@@x		= word ptr -2

		enter	0Ah, 0
		push	si
		push	di
		mov	si, offset orb
		mov	[bp+@@trail_center], offset _orb_trails_center[(ORB_TRAIL_COUNT - 1) * size Point]
		mov	[bp+@@star_center], offset _stars_center
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		dec	ax
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		dec	ax
		push	ax
		call	grcg_boxfill
		GRCG_OFF_CLOBBERING dx
		xor	di, di
		jmp	short loc_E098
; ---------------------------------------------------------------------------

loc_E053:
		mov	bx, [bp+@@star_center]
		mov	ax, [bx+Point.x]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.x
		add	ax, -4
		mov	[bp+@@x], ax
		mov	bx, [bp+@@star_center]
		mov	ax, [bx+Point.y]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.y
		add	ax, -4
		mov	[bp+@@y], ax
		push	[bp+@@x]	; x
		push	ax	; y
		mov	ax, di
		mov	bx, 2
		cwd
		idiv	bx
		add	dx, PAT_STAR_BIG
		push	dx	; num
		call	super_put_tiny_small
		inc	di
		add	[bp+@@star_center], size Point

loc_E098:
		cmp	di, STAR_COUNT
		jl	short loc_E053
		xor	di, di
		mov	[bp+@@trail_col], 6
		jmp	short loc_E0FB
; ---------------------------------------------------------------------------

loc_E0A6:
		mov	bx, [bp+@@trail_center]
		cmp	[bx+Point.x], SUBPIXEL_NONE
		jz	short loc_E0F6
		mov	bx, [bp+@@trail_center]
		mov	ax, [bx+Point.x]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.x
		mov	[bp+@@x], ax
		mov	bx, [bp+@@trail_center]
		mov	ax, [bx+Point.y]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.y
		mov	[bp+@@y], ax
		push	GC_RMW
		mov	ax, [bp+@@trail_col]
		inc	[bp+@@trail_col]
		push	ax
		call	grcg_setcolor
		call	grcg_circlefill pascal, [bp+@@x], [bp+@@y], ORB_RADIUS_FULL
		GRCG_OFF_CLOBBERING dx

loc_E0F6:
		inc	di
		sub	[bp+@@trail_center], size Point

loc_E0FB:
		cmp	di, ORB_TRAIL_COUNT
		jl	short loc_E0A6
		cmp	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jz	loc_E18B
		mov	eax, [si+orb_particle_t.OP_center_x]
		mov	ebx, 16
		cdq
		idiv	ebx
		add	ax, _space_window_center.x
		add	ax, -(ORB_W / 2)
		mov	[bp+@@x], ax
		mov	eax, [si+orb_particle_t.OP_center_y]
		cdq
		idiv	ebx
		add	ax, _space_window_center.y
		add	ax, -(ORB_H / 2)
		mov	[bp+@@y], ax
		cmp	[si+orb_particle_t.OP_al_radius], ORB_RADIUS_FULL
		jb	short loc_E161
		mov	al, byte_151CC
		mov	ah, 0
		mov	bx, 4
		cwd
		idiv	bx
		cwd
		idiv	bx
		add	dx, 8
		mov	di, dx
		call	super_put_rect pascal, [bp+@@x], [bp+@@y], dx
		inc	byte_151CC
		jmp	short loc_E18B
; ---------------------------------------------------------------------------

loc_E161:
		call	grcg_setcolor pascal, (GC_RMW shl 16) + V_WHITE
		mov	ax, [bp+@@x]
		add	ax, (ORB_W / 2)
		push	ax
		mov	ax, [bp+@@y]
		add	ax, (ORB_H / 2)
		push	ax
		mov	al, [si+orb_particle_t.OP_al_radius]
		mov	ah, 0
		push	ax
		call	grcg_circlefill
		GRCG_OFF_CLOBBERING dx

loc_E18B:
		sub	si, size orb_particle_t
		; ; si == particles[ORB_PARTICLE_COUNT - 1]
		xor	di, di
		jmp	loc_E21D
; ---------------------------------------------------------------------------

loc_E193:
		cmp	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jz	short loc_E219
		mov	ax, _space_window_w
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_x]
		jge	short loc_E219
		mov	ax, _space_window_w
		shl	ax, 3
		add	ax, (4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_x]
		jle	short loc_E219
		mov	ax, _space_window_h
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_y]
		jge	short loc_E219
		mov	ax, _space_window_h
		shl	ax, 3
		add	ax, (4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_y]
		jle	short loc_E219
		mov	eax, [si+orb_particle_t.OP_center_x]
		mov	ebx, 16
		cdq
		idiv	ebx
		add	ax, _space_window_center.x
		add	ax, -4
		mov	[bp+@@x], ax
		mov	eax, [si+orb_particle_t.OP_center_y]
		cdq
		idiv	ebx
		add	ax, _space_window_center.y
		add	ax, -4
		mov	[bp+@@y], ax
		call	super_put_tiny_small pascal, [bp+@@x], ax, [si+orb_particle_t.OP_patnum_tiny]

loc_E219:
		inc	di
		sub	si, size orb_particle_t

loc_E21D:
		cmp	di, ORB_PARTICLE_COUNT
		jl	loc_E193
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		dec	dx
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		dec	ax
		push	ax
		call	grcg_boxfill
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		add	ax, 7
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		dec	ax
		push	ax
		call	grcg_boxfill
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		add	ax, 7
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		dec	dx
		push	dx
		call	grcg_boxfill
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		push	ax
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		add	ax, 7
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		add	ax, 7
		push	ax
		call	grcg_boxfill
		GRCG_OFF_CLOBBERING dx
		pop	di
		pop	si
		leave
		retn
sub_DFEC	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_E349	proc near
		push	bp
		mov	bp, sp
		call	@space_update$qv
		call	sub_DFEC
		call	@frame_delay$qi pascal, 1
		graph_accesspage byte_1183A
		mov	al, 1
		sub	al, byte_1183A
		mov	byte_1183A, al
		graph_showpage al
		cmp	byte_11846, 0
		jz	short loc_E37E
		call	text_clear
		mov	byte_11846, 0

loc_E37E:
		inc	word_151E2
		call	_snd_bgm_measure
		mov	measure_151E0, ax
		cmp	measure_151E0, 0
		jge	short loc_E39D
		mov	ax, word_151E2
		mov	bx, 22
		cwd
		idiv	bx
		mov	measure_151E0, ax

loc_E39D:
		pop	bp
		retn
sub_E349	endp

include th05/end/verdict_bitmap.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @staffroll_animate$qv
@staffroll_animate$qv proc near

var_4		= word ptr -4
@@verdict_bitmap_offset		= word ptr -2

		enter	4, 0
		push	si
		push	di
		mov	x_116E2, 32
		mov	col_116E4, 13
		mov	word_116E6, 0Dh
		mov	y_116E8, 16
		mov	PaletteTone, 0
		call	far ptr	palette_show
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		graph_accesspage 0
		call	grcg_byteboxfill_x pascal, large 0, (((RES_X - 1) / 8) shl 16) or (RES_Y - 1)
		GRCG_OFF_CLOBBERING dx
		call	@verdict_stage_scores_put$qv
		call	verdict_bitmap_snap pascal, (1 * VERDICT_SCREEN_SIZE)
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		call	grcg_byteboxfill_x pascal, large 0, (((RES_X - 1) / 8) shl 16) or (RES_Y - 1)
		graph_accesspage 1
		call	grcg_byteboxfill_x pascal, large 0, (((RES_X - 1) / 8) shl 16) or (RES_Y - 1)
		GRCG_OFF_CLOBBERING dx
		call	snd_load pascal, ds, offset aStaff, SND_LOAD_SONG
		kajacall	KAJA_SONG_PLAY
		call	cdg_load_all_noalpha pascal,  0, ds, offset aStf00_cdg
		call	cdg_load_all_noalpha pascal,  1, ds, offset aStf01_cdg
		call	cdg_load_all_noalpha pascal,  2, ds, offset aStf02_cdg
		call	cdg_load_all_noalpha pascal,  3, ds, offset aStf03_cdg
		call	cdg_load_all_noalpha pascal,  4, ds, offset aStf04_cdg
		call	cdg_load_all_noalpha pascal,  5, ds, offset aStf05_cdg
		call	cdg_load_all_noalpha pascal,  6, ds, offset aStf06_cdg
		call	cdg_load_all_noalpha pascal,  7, ds, offset aStf07_cdg
		call	cdg_load_all_noalpha pascal,  8, ds, offset aStf08_cdg
		call	cdg_load_all_noalpha pascal,  9, ds, offset aStf09_cdg
		call	cdg_load_all_noalpha pascal, 10, ds, offset aStf10_cdg
		call	super_entry_bfnt pascal, ds, offset aStf01_bft ; "stf01.bft"
		call	super_entry_bfnt pascal, ds, offset aStf00_bft ; "stf00.bft"
		xor	si, si
		jmp	short loc_E550
; ---------------------------------------------------------------------------

loc_E549:
		call	super_convert_tiny pascal, si
		inc	si

loc_E550:
		cmp	si, 8
		jl	short loc_E549
		mov	Palettes[0 * size rgb_t].b, 48
		call	@space_reset$qv
		xor	si, si
		mov	word_151E2, 0

loc_E565:
		cmp	si, 100
		jg	short loc_E573
		mov	PaletteTone, si
		call	far ptr	palette_show

loc_E573:
		call	sub_E349
		inc	si
		cmp	measure_151E0, 30
		jl	short loc_E565
		call	@orb_gather_start$qv
		xor	si, si
		jmp	short loc_E58C
; ---------------------------------------------------------------------------

loc_E585:
		call	@orb_gather_animate$qv
		call	sub_E349
		inc	si

loc_E58C:
		cmp	si, 32
		jl	short loc_E585
		call	@orb_gather_end$qv

loc_E594:
		call	@orb_phase_update$qv
		mov	si, ax
		call	sub_E349
		or	si, si
		jz	short loc_E594
		cmp	measure_151E0, 48
		jl	short loc_E594
		xor	si, si
		xor	di, di

loc_E5AB:
		call	@orb_phase_update$qv
		cmp	si, 128
		jle	short loc_E5C9
		push	(528 shl 16) or 240
		push	(1 shl 16) or 76
		call	sub_DE74
		or	ax, ax
		jz	short loc_E5C9
		xor	si, si

loc_E5C9:
		push	(464 shl 16) or 192
		pushd	(0 shl 16) or 76
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		inc	si
		or	di, di
		jz	short loc_E5AB
		xor	di, di

loc_E5E1:
		call	@orb_phase_update$qv
		push	(464 shl 16) or 200
		push	(2 shl 16) or 92
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E5E1
		xor	si, si
		xor	di, di

loc_E600:
		call	@orb_phase_update$qv
		cmp	si, 256
		jle	short loc_E61E
		push	(464 shl 16) or 224
		push	(4 shl 16) or 120
		call	sub_DE74
		or	ax, ax
		jz	short loc_E61E
		xor	si, si

loc_E61E:
		push	(464 shl 16) or 176
		push	(3 shl 16) or 120
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		inc	si
		or	di, di
		jz	short loc_E600
		call	@orb_burst$qv

loc_E63A:
		call	@rain_phase_update$qv
		mov	si, ax
		call	sub_E349
		or	si, si
		jz	short loc_E63A
		xor	di, di

loc_E648:
		call	@rain_phase_update$qv
		push	(176 shl 16) or 200
		push	(5 shl 16) or 172
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E648

loc_E663:
		call	@rain_phase_update$qv
		push	(176 shl 16) or 200
		push	(6 shl 16) or 188
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E663

loc_E67E:
		call	@rain_phase_update$qv
		push	(176 shl 16) or 200
		push	(7 shl 16) or 204
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E67E

loc_E699:
		call	@rain_phase_update$qv
		push	(176 shl 16) or 200
		push	(8 shl 16) or 220
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E699

loc_E6B4:
		call	@rain_phase_update$qv
		push	(176 shl 16) or 200
		push	(9 shl 16) or 236
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E6B4
		xor	si, si
		mov	[bp+@@verdict_bitmap_offset], 0
		mov	[bp+var_4], 0

loc_E6DB:
		call	@input_reset_sense_held$qv
		cmp	si, 256
		jz	short loc_E6EC
		cmp	si, 257
		jnz	short loc_E6F1

loc_E6EC:
		call	@verdict_stats_put$qv
		jmp	short loc_E70D
; ---------------------------------------------------------------------------

loc_E6F1:
		cmp	si, 320
		jz	short loc_E6FD
		cmp	si, 321
		jnz	short loc_E702

loc_E6FD:
		call	@verdict_comment_put$qv
		jmp	short loc_E70D
; ---------------------------------------------------------------------------

loc_E702:
		cmp	si, 350
		jnz	short loc_E70D
		call	verdict_bitmap_snap pascal, 0

loc_E70D:
		call	@rain_phase_update$qv
		push	(176 shl 16) or 368
		push	(10 shl 16) or 3996
		call	sub_DCFC
		inc	si
		cmp	si, 400
		; Hack (jl	loc_E7BB)
		; No idea why TASM can't assemble this properly after script_op() was
		; decompiled. Seems to be related to the size of this segment; it works
		; when removing some instructions further above.
		; It still doesn't after decompiling cutscene_animate() though?
		db	0Fh, 8Ch, 93h, 00h
		test	_key_det.hi, high INPUT_CANCEL
		jnz	short loc_E757
		test	_key_det.lo, low INPUT_BOMB
		jnz	short loc_E757
		cmp	[bp+var_4], 0
		jnz	short loc_E781
		test	_key_det.lo, low INPUT_SHOT
		jnz	short loc_E74A
		test	_key_det.hi, high INPUT_OK
		jz	short loc_E75C

loc_E74A:
		cmp	[bp+@@verdict_bitmap_offset], 0
		jnz	short loc_E757
		mov	[bp+var_4], 1
		jmp	short loc_E75C
; ---------------------------------------------------------------------------

loc_E757:
		call	sub_E349
		jmp	short loc_E7C1
; ---------------------------------------------------------------------------

loc_E75C:
		test	_key_det.lo, low INPUT_DOWN
		jz	short loc_E76E
		cmp	[bp+@@verdict_bitmap_offset], 0
		jnz	short loc_E76E
		mov	[bp+var_4], 1

loc_E76E:
		test	_key_det.lo, low INPUT_UP
		jz	short loc_E781
		cmp	[bp+@@verdict_bitmap_offset], VERDICT_SCREEN_SIZE
		jnz	short loc_E781
		mov	[bp+var_4], 2

loc_E781:
		cmp	[bp+var_4], 1
		jnz	short loc_E79A
		add	[bp+@@verdict_bitmap_offset], (8 * VERDICT_BITMAP_VRAM_W)
		cmp	[bp+@@verdict_bitmap_offset], VERDICT_SCREEN_SIZE
		jbe	short loc_E7B5
		mov	[bp+@@verdict_bitmap_offset], VERDICT_SCREEN_SIZE
		jmp	short loc_E7B0
; ---------------------------------------------------------------------------

loc_E79A:
		cmp	[bp+var_4], 2
		jnz	short loc_E7BB
		sub	[bp+@@verdict_bitmap_offset], (8 * VERDICT_BITMAP_VRAM_W)
		cmp	[bp+@@verdict_bitmap_offset], 0
		jge	short loc_E7B5
		mov	[bp+@@verdict_bitmap_offset], 0

loc_E7B0:
		mov	[bp+var_4], 0

loc_E7B5:
		call	verdict_bitmap_put pascal, [bp+@@verdict_bitmap_offset]

loc_E7BB:
		call	sub_E349
		jmp	loc_E6DB
; ---------------------------------------------------------------------------

loc_E7C1:
		kajacall	KAJA_SONG_FADE, 4
		mov	si, 100

loc_E7CC:
		mov	PaletteTone, si
		call	far ptr	palette_show
		call	@rain_phase_update$qv
		call	sub_E349
		dec	si
		or	si, si
		jg	short loc_E7CC
		call	cdg_free_all
		call	super_free
		call	grc_setclip pascal, large 0, ((RES_X - 1) shl 16) or (RES_Y - 1)
		pop	di
		pop	si
		leave
		retn
@staffroll_animate$qv endp

maine_01__TEXT	ends

; ---------------------------------------------------------------------------
; ===========================================================================

; Segment type:	Pure code
SHARED segment byte public 'CODE' use16
include th02/snd/snd.inc
	extern GRAPH_PUTSA_FX:proc
	extern CDG_PUT_NOALPHA_8:proc
	extern SND_SE_PLAY:proc
	extern _snd_se_update:proc
	extern _bgimage_snap:proc
	extern _bgimage_free:proc
	extern VECTOR2_AT:proc
	extern BGIMAGE_PUT_RECT_16:proc
	extern SND_LOAD:proc
	extern SND_KAJA_INTERRUPT:proc
	extern @PI_LOAD$QINXC:proc
	extern @PI_PUT_8$QIII:proc
	extern @PI_PALETTE_APPLY$QI:proc
	extern @PI_FREE$QI:proc
	extern @input_reset_sense_held$qv:proc
	extern @INPUT_WAIT_FOR_CHANGE$QI:proc
	extern _snd_bgm_measure:proc
	extern @FRAME_DELAY$QI:proc
	extern CDG_LOAD_ALL_NOALPHA:proc
	extern CDG_FREE_ALL:proc
SHARED ends

	.data

	; libs/master/pal[data].asm
	extern PaletteTone:word

	; libs/master/rand[data].asm
	extern random_seed:dword

	; th04/hardware/grppsafx.asm
	extern _graph_putsa_fx_func:word

include th03/snd/se_state[data].asm
include th04/hardware/bgimage[data].asm
include th05/mem[data].asm
include th05/snd/load[data].asm
include th04/snd/snd[data].asm
include th03/formats/pi_put_masked[data].asm
include th05/formats/pi_buffers[bss].asm
include th05/hardware/vram_planes[data].asm
include th03/formats/cdg[data].asm
include th03/cutscene/cutscene[data].asm
public _page_shown
_page_shown	db 0
	evendata
public _BG_FN
_BG_FN	label dword
		dd aExed01_pi		; "EXED01.pi"
		dd aExed07_pi		; "EXED07.pi"
		dd aExed08_pi		; "EXED08.pi"
		dd aExed09_pi		; "EXED09.pi"
		dd aExed10_pi		; "EXED10.pi"
		dd aExed16_pi		; "EXED16.pi"
		dd aExed15_pi		; "EXED15.pi"
		dd 0
		dd aExed01_pi_0		; "EXED01.pi"
		dd aExed11_pi		; "EXED11.pi"
		dd aExed11_pi_0		; "EXED11.pi"
		dd aExed11_pi_1		; "EXED11.pi"
		dd aExed03_pi		; "EXED03.pi"
		dd aExed16_pi_0		; "EXED16.pi"
		dd aExed15_pi_0		; "EXED15.pi"
		dd 0
		dd aExed01_pi_1		; "EXED01.pi"
		dd aExed12_pi		; "EXED12.pi"
		dd aExed12_pi_0		; "EXED12.pi"
		dd aExed13_pi		; "EXED13.pi"
		dd aExed04_pi		; "EXED04.pi"
		dd aExed16_pi_1		; "EXED16.pi"
		dd aExed15_pi_1		; "EXED15.pi"
		dd 0
		dd aExed01_pi_2		; "EXED01.pi"
		dd aExed14_pi		; "EXED14.pi"
		dd aExed05_pi		; "EXED05.pi"
		dd aExed14_pi_0		; "EXED14.pi"
		dd aExed06_pi		; "EXED06.pi"
		dd aExed16_pi_2		; "EXED16.pi"
		dd aExed15_pi_2		; "EXED15.pi"
		dd 0
public _BG_QUARTER
_BG_QUARTER	label word
		dw 1, 0, 1, 3, 0, 0, 0, 0
		dw 1, 0, 1, 2, 1, 1, 1, 0
		dw 1, 2, 0, 1, 0, 2, 2, 0
		dw 1, 0, 0, 2, 0, 3, 3, 0
public _LINES
_LINES	dd aProjectOfTouho
		dd aNo_1Buumx		; "		     Project of	TOUHOU	  "...
		dd aReimuHakureiSh
		dd aNo_2Buumx
		dd aReimuHakurei_0
		dd aRikaEngineer
		dd aMeiraSamurai
		dd aMarisaKirisame
		dd aMimaGhost
		dd aNo_3Buumx
		dd aReimuHakurei_1
		dd aMarisaKirisa_0
		dd aMimaGhost_0
		dd aEllenWitch
		dd aKotohimePrince
		dd aKanaAnaberalPo
		dd aRikakoAsakuraS
		dd aTiyuriKitashir
		dd aYumemiOkazakiP
		dd aNo_4Buumx
		dd aReimuHakurei_2
		dd aMarisaKirisa_1
		dd aOrangeOriental
		dd aKurumiVampire
		dd aElliyGateKeepe
		dd aYukaOrientalDe
		dd aMugetuMaid
		dd aGengetuDemon
		dd aNo_5Buumx
		dd aReimuHakurei_3
		dd aMarisaKirisa_2
		dd aMimaGhost_1
		dd aYukaOriental_0
		dd aSaraGateKeeper
		dd aLuizeDemon
		dd aAliceWitchOfDe
		dd aYukiBlackWitch
		dd aMaiWhiteWitch
		dd aYumekoMaid
		dd aShinkiGoddessO
		dd aProgramerZunJu
		dd aGraphicsZunJun
		dd aMusicComposeZu
		dd aP_m_d_ProgramM
		dd aSpecialThanksA
		dd aAmusementMaker
		dd aAndAllTestPlay
public _LINES_PER_SCREEN, _line_id_on_screen
_LINES_PER_SCREEN	equ $-2
		dw 1, 2, 6, 10, 9, 12, 7
		db    0
		db    0
_line_id_on_screen	dw 0
aExed01_pi	db 'EXED01.pi',0
aExed07_pi	db 'EXED07.pi',0
aExed08_pi	db 'EXED08.pi',0
aExed09_pi	db 'EXED09.pi',0
aExed10_pi	db 'EXED10.pi',0
aExed16_pi	db 'EXED16.pi',0
aExed15_pi	db 'EXED15.pi',0
aExed01_pi_0	db 'EXED01.pi',0
aExed11_pi	db 'EXED11.pi',0
aExed11_pi_0	db 'EXED11.pi',0
aExed11_pi_1	db 'EXED11.pi',0
aExed03_pi	db 'EXED03.pi',0
aExed16_pi_0	db 'EXED16.pi',0
aExed15_pi_0	db 'EXED15.pi',0
aExed01_pi_1	db 'EXED01.pi',0
aExed12_pi	db 'EXED12.pi',0
aExed12_pi_0	db 'EXED12.pi',0
aExed13_pi	db 'EXED13.pi',0
aExed04_pi	db 'EXED04.pi',0
aExed16_pi_1	db 'EXED16.pi',0
aExed15_pi_1	db 'EXED15.pi',0
aExed01_pi_2	db 'EXED01.pi',0
aExed14_pi	db 'EXED14.pi',0
aExed05_pi	db 'EXED05.pi',0
aExed14_pi_0	db 'EXED14.pi',0
aExed06_pi	db 'EXED06.pi',0
aExed16_pi_2	db 'EXED16.pi',0
aExed15_pi_2	db 'EXED15.pi',0
aProjectOfTouho	db '                  Project of TOUHOU    All Cast',0
aNo_1Buumx	db 'No.1 「東方靈異伝」 ～ Highly Responsive to Prayers    1996,1997',0
aReimuHakureiSh	db '      Reimu Hakurei                           ( Shaman )',0
aNo_2Buumx	db 'No.2 「東方封魔録」 ～ The story of eastern wonderland 1997',0
aReimuHakurei_0	db '      Reimu Hakurei                           ( Shaman )',0
aRikaEngineer	db '         Rika                                ( Engineer )',0
aMeiraSamurai	db '         Meira                                ( Samurai )',0
aMarisaKirisame	db '     Marisa Kirisame                         ( Sorceress )',0
aMimaGhost	db '         Mima                                 ( Ghost )',0
aNo_3Buumx	db 'No.3 「東方夢時空」 ～ The Phantasmagoria of Dim.Dream... 1997',0
aReimuHakurei_1	db '      Reimu Hakurei                           ( Shaman )',0
aMarisaKirisa_0	db '     Marisa Kirisame                         ( Sorceress )',0
aMimaGhost_0	db '         Mima                                  ( Ghost )',0
aEllenWitch	db '        Ellen                                  ( Witch )',0
aKotohimePrince	db '       Kotohime                               ( Princess )',0
aKanaAnaberalPo	db '     Kana Anaberal                           ( Poltergeist )',0
aRikakoAsakuraS	db '     Rikako Asakura                          ( Scientist )',0
aTiyuriKitashir	db '   Tiyuri Kitashirakawa                  ( Assistant professor )',0
aYumemiOkazakiP	db '     Yumemi Okazaki                          ( Professor )',0
aNo_4Buumx	db 'No.4 「東方幻想郷」 ～ Lotus Land Story                  1998',0
aReimuHakurei_2	db '      Reimu Hakurei                           ( Shaman )',0
aMarisaKirisa_1	db '     Marisa Kirisame                         ( Sorceress )',0
aOrangeOriental	db '        Orange                             ( Oriental demon )',0
aKurumiVampire	db '        Kurumi                                ( Vampire )',0
aElliyGateKeepe	db '        Elliy                                ( Gate keeper )',0
aYukaOrientalDe	db '         Yuka                              ( Oriental demon )',0
aMugetuMaid	db '        Mugetu                                 ( Maid )',0
aGengetuDemon	db '        Gengetu                                ( Demon )',0
aNo_5Buumx	db 'No.5 「東方怪綺談」 ～ Mystic Square                    1998',0
aReimuHakurei_3	db '      Reimu Hakurei                           ( Shaman )',0
aMarisaKirisa_2	db '     Marisa Kirisame                         ( Sorceress )',0
aMimaGhost_1	db '         Mima                                  ( Ghost )',0
aYukaOriental_0	db '         Yuka                              ( Oriental demon )',0
aSaraGateKeeper	db '         Sara                                ( Gate keeper )',0
aLuizeDemon	db '        Luize                                  ( Demon )',0
aAliceWitchOfDe	db '        Alice                              ( Witch of death )',0
aYukiBlackWitch	db '         Yuki                                ( Black witch )',0
aMaiWhiteWitch	db '         Mai                                 ( White witch )',0
aYumekoMaid	db '        Yumeko                                 ( Maid )',0
aShinkiGoddessO	db '        Shinki                         ( Goddess of devil',27h,'s world )',0
aProgramerZunJu	db '      Programer                                ZUN (Junya Ota)',0
aGraphicsZunJun	db '      Graphics                                 ZUN (Junya Ota)',0
aMusicComposeZu	db '    Music Compose                              ZUN (Junya Ota)',0
aP_m_d_ProgramM	db '    P.M.D. Program                             M.Kajihara(KAJA)',0
aSpecialThanksA	db '    Special Thanks                             Aotaka',0
aAmusementMaker	db '                                               Amusement Makers',0
aAndAllTestPlay	db '             and all test player and you ... ',0
public _EXED
_EXED db 'EXED',0
include th04/hiscore/alphabet[data].asm
public _regist_page_shown
_regist_page_shown	db 0
public _entered_name_cursor
_entered_name_cursor	dw 0
public _SCOREDAT_FN, _SCOREDAT_FN_2
_SCOREDAT_FN	db 'GENSOU.SCR',0
include th05/formats/scoredat_load_for[data].asm
_SCOREDAT_FN_2	db 'GENSOU.SCR',0
public _hi01_pi, _scnum_bft, _sctm0_bft, _sctm1_bft
public _SLOW_MODE_MSG_SHADOW, _SLOW_MODE_MSG, _BGM_NAME_FN
public _STAGE_1_MSG, _STAGE_2_MSG, _STAGE_3_MSG, _STAGE_4_MSG
public _STAGE_5_MSG, _STAGE_6_MSG, _FINAL_SCORE_MSG_0
_hi01_pi	db 'hi01.pi',0
_scnum_bft	db 'scnum.bft',0
_sctm0_bft	db 'sctm0.bft',0
_sctm1_bft	db 'sctm1.bft',0
_SLOW_MODE_MSG_SHADOW	db 'スローモードでのプレイでは、スコアは記録されません',0
_SLOW_MODE_MSG	db 'スローモードでのプレイでは、スコアは記録されません',0
_BGM_NAME_FN	db 'name',0
		db 0
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_scores.cpp can
; read this. `label` emits nothing, so every following offset is
; unchanged, and this block's own references keep the original spelling.
public _verdict_left
_verdict_left	label word
x_116E2	dw 336
; kb/codegen/0123: a zero-byte alias so th04/end/verdict_digits.cpp can read
; this. `label` emits nothing, so every following offset is unchanged, and
; this block's own thirty-odd references keep the original spelling.
public _verdict_col
_verdict_col	label word
col_116E4	dw 2
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_comment.cpp can read this.
; `label` emits nothing, so every following offset is unchanged, and
; this dump's own remaining references keep the original spelling.
public _verdict_comment_col
_verdict_comment_col	label word
word_116E6	dw 6
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_scores.cpp can
; read this. `label` emits nothing, so every following offset is
; unchanged, and this block's own references keep the original spelling.
public _verdict_top
_verdict_top	label word
y_116E8	dw 48
include th04/gaiji/verdict[data].asm
public _POINT_MSG
_POINT_MSG	label byte
aU__0		db '点',0
public _DOT_MSG
_DOT_MSG	label byte
aBd		db '．',0
public _PERCENT_MSG
_PERCENT_MSG	label byte
aBu		db '％',0
public _DOT_MSG_0
_DOT_MSG_0	label byte
aBd_0		db '．',0
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_guts.cpp can
; read this. `label` emits nothing, so every following offset is
; unchanged, and this block's own reference keeps the original spelling.
public _PERCENT_MSG_0
_PERCENT_MSG_0	label byte
aBu_0		db '％',0
; kb/codegen/0123: zero-byte aliases so th05/end/verdict_stats.cpp can read
; these. `label` emits nothing, so every following offset is unchanged.
; They stay _DATA bytes of this dump rather than becoming literals of that
; translation unit because the build compiles with `-d` and three of them
; have byte-identical duplicates elsewhere in this contribution.
public _VERDICT_TITLE
_VERDICT_TITLE	label byte
aB@b@b@b@b@b@b@	db '　　　　　　　 腕前判定',0
public _LABEL_RANK
_LABEL_RANK	label byte
aUqiUx		db '難易度',0
public _FINAL_SCORE_MSG
_FINAL_SCORE_MSG	label byte
aNPiuU_		db '最終得点',0
public _LABEL_MISSES
_LABEL_MISSES	label byte
aGGxi		db 'ミス回数',0
public _LABEL_BOMBS
_LABEL_BOMBS	label byte
aGGaogcpi	db 'ボム使用回数',0
public _LABEL_GAME_COMPLETION
_LABEL_GAME_COMPLETION	label byte
aGqbGatbrmcj	db 'ゲーム達成率',0
public _LABEL_ENEMIES_KILLED
_LABEL_ENEMIES_KILLED	label byte
aIlcSObcj	db '悪霊退治率',0
public _LABEL_ITEMS_COLLECTED
_LABEL_ITEMS_COLLECTED	label byte
aGagcgegai	db 'アイテム回収率',0
public _LABEL_POINT_ITEMS_MAXED
_LABEL_POINT_ITEMS_MAXED	label byte
aUU_gagcgeganNv	db '得点アイテム最高点率',0
public _LABEL_GUTS
_LABEL_GUTS	label byte
aLcnzvv		db '気合い',0
public _LABEL_SLOWDOWN
_LABEL_SLOWDOWN	label byte
aPicacovCj	db '処理落ち率',0
public _LABEL_YOUR_SKILL
_LABEL_YOUR_SKILL	label byte
aVavVVSrso	db 'あなたの腕前',0
public _TIMES_MSG
_TIMES_MSG	label byte
aI		db '回',0
public _TIMES_MSG_0
_TIMES_MSG_0	label byte
aI_0		db '回',0
public _POINT_MSG_0
_POINT_MSG_0	label byte
aU_		db '点',0
public _ude_txt
_ude_txt	label byte
a_ude_txt	db '_ude.txt',0
public _SKILL_UNKNOWN_MSG
_SKILL_UNKNOWN_MSG	label byte
aBhbhbhbhbhbhu_	db '？？？？？？点',0
public _SLOWDOWN_NO_VERDICT_MSG
_SLOWDOWN_NO_VERDICT_MSG	label byte
aPicacovVVcvsfT	db '処理落ちによる判定不可',0
public _ude_pi
_ude_pi		db 'ude.pi',0
_STAGE_1_MSG	db '　１面　',0
_STAGE_2_MSG	db '　２面　',0
_STAGE_3_MSG	db '　３面　',0
_STAGE_4_MSG	db '　４面　',0
_STAGE_5_MSG	db '　５面　',0
_STAGE_6_MSG	db '　６面　',0
_FINAL_SCORE_MSG_0	db '最終得点',0
; kb/codegen/0123: zero-byte alias for the page this scene shows.
; sub_E349 spells out the same graph_accesspage()/graph_showpage() flip
; that th02/op_04.cpp and th03/op/m_select.cpp write in C++ as
; page_shown; the name is scoped because this binary already links a
; different _page_shown.
public _staffroll_page_shown
_staffroll_page_shown	label byte
byte_1183A	db 0
		db 0
; kb/codegen/0123: zero-byte alias. orb_particle_emit() is the only user
; and is now C++, so it spells upstream's own name for this without the
; address.
public _particle_i
_particle_i	label word
particle_i_1183C	dw 0
; kb/codegen/0123: zero-byte aliases for the orb phase's two pieces of
; state. orb_phase_update() is the sole user of both, so both are named
; from their complete usage set.
public _orb_phase_frame
_orb_phase_frame	label word
word_1183E	dw 0
public _orb_phase_camera_slowing
_orb_phase_camera_slowing	label byte
byte_11840	db 0
		db 0
; kb/codegen/0123: zero-byte aliases for the rain phase's two pieces of
; state. rain_particle_spawn() is the sole user of the first and
; rain_phase_update() the sole user of the second.
public _rain_particle_i
_rain_particle_i	label word
word_11842	dw 0
public _rain_phase_frame
_rain_phase_frame	label word
word_11844	dw 0
byte_11846	db 0
		db 0
word_11848	dw 0
word_1184A	dw 0
unk_1184C	db  20h
		db  20h
		db    0
unk_1184F	db  20h
		db  20h
		db    0
aStaff		db 'staff',0
aStf00_cdg	db 'stf00.cdg',0
aStf01_cdg	db 'stf01.cdg',0
aStf02_cdg	db 'stf02.cdg',0
aStf03_cdg	db 'stf03.cdg',0
aStf04_cdg	db 'stf04.cdg',0
aStf05_cdg	db 'stf05.cdg',0
aStf06_cdg	db 'stf06.cdg',0
aStf07_cdg	db 'stf07.cdg',0
aStf08_cdg	db 'stf08.cdg',0
aStf09_cdg	db 'stf09.cdg',0
aStf10_cdg	db 'stf10.cdg',0
aStf01_bft	db 'stf01.bft',0
aStf00_bft	db 'stf00.bft',0

	.data?

	extern _resident:dword

	; libs/master.lib/pal[bss].asm
	extern Palettes:byte:48

	; th04/hardware/input[bss].asm
	extern _key_det:word

	; th03/formats/cdg[bss].asm
	extern _cdg_slots:cdg_t:CDG_SLOT_COUNT

	; th05/allcast.cpp
	extern _loaded_screen_id:word
	extern _line_id_total:word

include th04/formats/scoredat[bss].asm
public _glyphballs
_glyphballs	glyphball_t	(SCOREDAT_NAME_LEN + 1) dup (<?>)
include th03/hiscore/regist[bss].asm
public _rank, _playchar
_rank	db ?
_playchar	db ?
		db 3 dup(?)
public _skill
; kb/codegen/0123: zero-byte aliases so th04/end/verdict_digits.cpp can
; reach these two. `label` emits nothing.
public _skill_stash_quarter
_skill_stash_quarter	label byte
byte_1517C	db ?
		db ?
_skill	dd ?
public _skill_quarter
_skill_quarter	label dword
dword_15182	dd ?
; th05/end/verdict_stats.cpp now WRITES this, and the still-ASM
; staffroll_animate() still reads it, so the storage stays here and
; only the name is exported.
public _verdict_rank
_verdict_rank	db ?
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_comment.cpp can read this.
; `label` emits nothing, so every following offset is unchanged, and
; this dump's own remaining references keep the original spelling.
public _verdict_comment_1
_verdict_comment_1	label byte
byte_15187	db ?
		db 27 dup(?)
byte_151A3	db ?
		db    ?	;
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_comment.cpp can read this.
; `label` emits nothing, so every following offset is unchanged, and
; this dump's own remaining references keep the original spelling.
public _verdict_comment_2
_verdict_comment_2	label byte
byte_151A5	db ?
		db 27 dup(?)
byte_151C1	db ?
		db 2 dup(?)
word_151C4	dw ?
word_151C6	dw ?
word_151C8	dw ?
word_151CA	dw ?
byte_151CC	db ?
		db ?
public _space_window_center, _space_window_w, _space_window_h
public _space_window_w, _space_window_h
_space_window_w	dw ?
_space_window_h	dw ?
; kb/codegen/0123: zero-byte alias. Both users -- orb_burst() and
; orb_particle_emit() -- are now in th05/space.cpp; the storage stays
; here because moving it would move every _BSS address after it.
public _particle_spawn_center
_particle_spawn_center	label word
point_151D2	Point <?>
_space_window_center	Point <?>
public _space_camera_velocity
_space_camera_velocity	Point <?>
; kb/codegen/0123: zero-byte alias so th05/space.cpp can reach this word.
; It is the per-frame deceleration space_update() subtracts from every
; particle's speed; 0 additionally selects the wrap-around field mode.
; Named from its complete usage set: the four writers and the one reader
; that space_reset(), orb_gather_end(), orb_burst() and space_update()
; now are, plus rain_phase_update(), which zeroes it again every frame of
; the rain phase.
public _particle_decel
_particle_decel	label word
word_151DE	dw ?
measure_151E0	dw ?
; kb/codegen/0123: zero-byte alias for the scene's frame counter.
; staffroll_animate() zeroes it, sub_E349 increments it, and
; space_update() and orb_phase_update() read it.
public _staffroll_frame
_staffroll_frame	label word
word_151E2	dw ?
	extern _particles:orb_particle_t:ORB_PARTICLE_COUNT
	extern _orb_trails_center:Point:ORB_TRAIL_COUNT
	extern _stars_center:Point:STAR_COUNT
	extern _verdict_bitmap:word:(VERDICT_SCREEN_H * 2 * (VERDICT_BITMAP_W / 16))

		end
