;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input MD5   : E22366913B7288F2EC82E280B386C86D

; File Name   : th04/ZUN.COM:ZUNINIT (-I)
; Format      : MS-DOS COM-file
; Base Address: 0h Range: 100h-4F1h Loaded length: 3F1h
; OS type     :  MS DOS
; Application type:  Executable 16bit

		.386
		.model use16 tiny
		.code
		org 100h

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn thunk

public start
start proc near
		jmp	zuninit_main
start endp
		even


; =============== S U B R O U T I N E =======================================


zun_stop_interrupt_handler proc far
		cmp	cs:zun_stop_copy_key, 0
		jnz	short locret_115
		mov	cs:zun_stop_copy_key, 1
		call	stop_copy_key_warning

locret_115:
		iret
zun_stop_interrupt_handler endp


; =============== S U B R O U T I N E =======================================


zun_copy_interrupt_handler proc far
		cmp	cs:zun_stop_copy_key, 0
		jnz	short locret_127
		mov	cs:zun_stop_copy_key, 2
		call	stop_copy_key_warning

locret_127:
		iret
zun_copy_interrupt_handler endp


; =============== S U B R O U T I N E =======================================


stop_copy_key_warning proc near
		pushf
		pusha
		push	ds
		push	es
		mov	ah, 41h
		int	18h
		mov	di, offset STOP_MESSAGE_1 ; "むやみにＳＴＯＰキー押したりしない$"
		cmp	cs:zun_stop_copy_key, 1
		jz	short loc_13E
		mov	di, offset COPY_MESSAGE_1	; "なんでＣＯＰＹキー押したりしてるの$"

loc_13E:
		mov	ax, 650h
		call	zuninit_message_put
		add	di, offset STOP_MESSAGE_2 - offset STOP_MESSAGE_1 ; "方がいいと思うの。（ゲーム中はね）$"
		mov	ax, 6F0h
		call	zuninit_message_put
		add	di, offset STOP_MESSAGE_3 - offset STOP_MESSAGE_2 ; "（ＳＴＯＰキーで戻れるよ、ねっ）　$"
		mov	ax, 790h
		call	zuninit_message_put
		mov	bl, cs:zun_stop_copy_key

loc_15B:
		call	stop_copy_key_state_test
		jnz	short loc_15B

loc_160:
		call	stop_copy_key_state_test
		jz	short loc_160

loc_165:
		call	stop_copy_key_state_test
		jnz	short loc_165
		mov	ah, 40h
		int	18h
		mov	di, offset WARNING_MESSAGE_BLANK ; "　　　　　　　　　　　　　　　　　$"
		mov	ax, 650h
		call	zuninit_message_put
		mov	ax, 6F0h
		call	zuninit_message_put
		mov	ax, 790h
		call	zuninit_message_put
		mov	ah, 6
		int	18h
		pop	es
		pop	ds
		popa
		popf
		mov	cs:zun_stop_copy_key, 0
		retn
stop_copy_key_warning endp


; =============== S U B R O U T I N E =======================================


stop_copy_key_state_test proc near
		mov	ah, 4
		mov	al, 0Ch
		int	18h
		test	ah, bl
		retn
stop_copy_key_state_test endp
		even

; =============== S U B R O U T I N E =======================================


shiftjis_to_jis proc near
		shl	ah, 1
		cmp	al, 9Fh
		jnb	short loc_1A7
		cmp	al, 80h
		adc	ax, 0FEDFh

loc_1A7:
		sbb	ax, 0DFFEh
		and	ax, 7F7Fh
		retn
shiftjis_to_jis endp


; =============== S U B R O U T I N E =======================================


zuninit_message_put proc near
		push	di
		mov	bx, di
		mov	dx, 0A000h
		mov	es, dx
		assume es:nothing
		mov	di, ax
		mov	dx, ax
		xor	ax, ax
		xor	cx, cx

loc_1BE:
		mov	ax, cs:[bx]
		cmp	al, 24h
		jz	short loc_1DB
		xchg	ah, al
		call	shiftjis_to_jis
		xchg	ah, al
		sub	al, 20h
		stosw
		or	ah, 80h
		stosw
		add	bx, 2
		add	cl, 2
		jmp	short loc_1BE
; ---------------------------------------------------------------------------

loc_1DB:
		mov	ax, 0A200h
		mov	es, ax
		assume es:nothing
		mov	di, dx
		mov	ax, 41h

loc_1E5:
		stosw
		loop	loc_1E5
		pop	di
		retn
zuninit_message_put endp

; ---------------------------------------------------------------------------
public _zun_resident_signature
_zun_resident_signature label word
ZUNP	dw 'ZU', 'NP'
zun_prior_copy_interrupt_vector	dd 0
zun_prior_stop_interrupt_vector	dd 0
STOP_MESSAGE_1	db 'むやみにＳＴＯＰキー押したりしない$'
STOP_MESSAGE_2	db '方がいいと思うの。（ゲーム中はね）$'
STOP_MESSAGE_3	db '（ＳＴＯＰキーで戻れるよ、ねっ）　$'
COPY_MESSAGE_1	db 'なんでＣＯＰＹキー押したりしてるの$'
COPY_MESSAGE_2	db 'かな～。ふしぎ～。　　（もう一度、$'
COPY_MESSAGE_3	db 'ＣＯＰＹキー押せば戻れるよ、ねっ）$'
WARNING_MESSAGE_BLANK	db '　　　　　　　　　　　　　　　　　$'
zun_stop_copy_key	db 0

; =============== S U B R O U T I N E =======================================


_TEXT ends

DGROUP group ZUN_RES_TEXT, ZUN_TAIL_TEXT

ZUN_RES_TEXT segment byte public 'CODE' use16
ZUN_RES_TEXT ends

ZUN_TAIL_TEXT segment byte public 'CODE' use16
	assume cs:DGROUP, ds:DGROUP
	extrn _zun_resident_check:near




















; =============== S U B R O U T I N E =======================================

zuninit_main proc near
		mov	si, 81h

loc_311:
		lodsb
		cmp	al, 0Dh
		jz	short loc_322
		cmp	al, '/'
		jz	short loc_32C
		cmp	al, '-'
		jz	short loc_32C
		cmp	al, ' '
		jbe	short loc_311

loc_322:
		call	_zun_resident_check
		test	ax, ax
		jz	short loc_344
		jmp	loc_3B0
; ---------------------------------------------------------------------------

loc_32C:
		lodsb
		cmp	al, ' '
		jbe	loc_3BA
		and	al, 0DFh
		cmp	al, 'R'
		jnz	loc_3BA
		call	_zun_resident_check
		test	ax, ax
		jnz	short loc_381
		jmp	short loc_3B5
; ---------------------------------------------------------------------------

loc_344:
		mov	ax, 3506h
		int	21h		; DOS - 2+ - GET INTERRUPT VECTOR
					; AL = interrupt number
					; Return: ES:BX = value of interrupt vector
		mov	word ptr zun_prior_stop_interrupt_vector, bx
		mov	word ptr zun_prior_stop_interrupt_vector+2, es
		mov	dx, offset zun_stop_interrupt_handler
		mov	ax, 2506h
		int	21h		; DOS - SET INTERRUPT VECTOR
					; AL = interrupt number
					; DS:DX = new vector to be used for specified interrupt
		mov	ax, 3505h
		int	21h		; DOS - 2+ - GET INTERRUPT VECTOR
					; AL = interrupt number
					; Return: ES:BX = value of interrupt vector
		mov	word ptr zun_prior_copy_interrupt_vector, bx
		mov	word ptr zun_prior_copy_interrupt_vector+2, es
		mov	dx, offset zun_copy_interrupt_handler
		mov	ax, 2505h
		int	21h		; DOS - SET INTERRUPT VECTOR
					; AL = interrupt number
					; DS:DX = new vector to be used for specified interrupt
		mov	dx, offset ZUNINIT_INSTALLING_MESSAGE ; "ちょこっとお部屋かりるね☆\r\n\r\n$"
		mov	ah, 9
		int	21h		; DOS - PRINT STRING
					; DS:DX -> string terminated by "$"
		mov	dx, offset _zun_resident_check
		shr	dx, 4
		inc	dx
		mov	ax, 3100h
		int	21h		; DOS - DOS 2+ - TERMINATE BUT STAY RESIDENT
					; AL = exit code, DX = program size, in paragraphs
; ---------------------------------------------------------------------------

loc_381:
		push	ds
		lds	dx, es:zun_prior_stop_interrupt_vector
		mov	ax, 2506h
		int	21h		; DOS - SET INTERRUPT VECTOR
					; AL = interrupt number
					; DS:DX = new vector to be used for specified interrupt
		lds	dx, es:zun_prior_copy_interrupt_vector
		mov	ax, 2505h
		int	21h		; DOS - SET INTERRUPT VECTOR
					; AL = interrupt number
					; DS:DX = new vector to be used for specified interrupt
		pop	ds
		push	es
		mov	es, word ptr es:2Ch
		assume es:nothing
		mov	ah, 49h
		int	21h		; DOS - 2+ - FREE MEMORY
					; ES = segment address of area to be freed
		pop	es
		mov	ah, 49h
		int	21h		; DOS - 2+ - FREE MEMORY
					; ES = segment address of area to be freed
		mov	dx, offset ZUNINIT_UNINSTALLED_MESSAGE ; "借りてたお部屋をお返ししますね。それで?"...
		jnb	short loc_3BD
		mov	dx, offset ZUNINIT_FREE_ERROR_MESSAGE ; "メモリ解放エラーです\r\n$"
		jmp	short loc_3BD
; ---------------------------------------------------------------------------

loc_3B0:
		mov	dx, offset ZUNINIT_ALREADY_RESIDENT_MESSAGE ; "すでに常駐してます～\r\n\r\n$"
		jmp	short loc_3BD
; ---------------------------------------------------------------------------

loc_3B5:
		mov	dx, offset ZUNINIT_NOT_RESIDENT_MESSAGE ; "まだ、常駐してないです\r\n\r\n$"
		jmp	short loc_3BD
; ---------------------------------------------------------------------------

loc_3BA:
		mov	dx, offset ZUNINIT_INVALID_OPTION_MESSAGE ; "意味不明なオプションよぉ（オプションは "...

loc_3BD:
		mov	ah, 9
		int	21h		; DOS - PRINT STRING
					; DS:DX -> string terminated by "$"
		mov	ax, 4C00h
		int	21h		; DOS - 2+ - QUIT WITH EXIT CODE (EXIT)
zuninit_main endp			; AL = exit code

; ---------------------------------------------------------------------------
public _zun_resident_banner
_zun_resident_banner label byte
ZUNINIT_BANNER	db 0Dh,0Ah
		db 'INTvector set program  zuninit.com                      Version1.02 (c)zun 1998',0Dh,0Ah,'$'
ZUNINIT_INSTALLING_MESSAGE	db 'ちょこっとお部屋かりるね☆',0Dh,0Ah
		db 0Dh,0Ah,'$'
ZUNINIT_ALREADY_RESIDENT_MESSAGE	db 'すでに常駐してます～',0Dh,0Ah
		db 0Dh,0Ah,'$'
ZUNINIT_UNINSTALLED_MESSAGE	db '借りてたお部屋をお返ししますね。それではまた☆',0Dh,0Ah

		db 0Dh,0Ah,'$'
ZUNINIT_NOT_RESIDENT_MESSAGE	db 'まだ、常駐してないです',0Dh,0Ah
		db 0Dh,0Ah,'$'
ZUNINIT_INVALID_OPTION_MESSAGE	db '意味不明なオプションよぉ（オプションは -R : 解放 のみ）',0Dh,0Ah,'$'

ZUNINIT_FREE_ERROR_MESSAGE	db 'メモリ解放エラーです',0Dh,0Ah,'$'

ZUN_TAIL_TEXT ends

		end start
