;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	57F21130457B229B7ED74E30D2B6E6E5

; File Name   :	th05/MAINE.EXE
; Format      :	MS-DOS executable (EXE)
; Base Address:	0h Range: 0h-1C6F0h Loaded length: 128A6h
; Entry	Point :	0:0
; OS type	  :  MS	DOS
; Application type:  Executable	16bit

		.386
		.model use16 large _TEXT

BINARY = 'E'

include ReC98.inc
include th05/th05.inc
include th01/math/subpixel.inc
include th04/hardware/grppsafx.inc

group_01 group CUTSCENE_TEXT, maine_01_TEXT, SCORE_TEXT, maine_01__TEXT

; ===========================================================================

_TEXT segment word public 'CODE' use16
	extern PALETTE_BLACK_IN:proc
	extern PALETTE_BLACK_OUT:proc
	extern FILE_APPEND:proc
	extern FILE_CLOSE:proc
	extern FILE_READ:proc
	extern FILE_ROPEN:proc
	extern FILE_SEEK:proc
	extern FILE_WRITE:proc
	extern GRCG_BOXFILL:proc
	extern GRCG_BYTEBOXFILL_X:proc
	extern GRCG_CIRCLEFILL:proc
	extern GRC_SETCLIP:proc
	extern GRCG_HLINE:proc
	extern GRCG_SETCOLOR:proc
	extern GRCG_VLINE:proc
	extern GAIJI_PUTCA:proc
	extern GAIJI_PUTSA:proc
	extern GRAPH_COPY_PAGE:proc
	extern IATAN2:proc
	extern IHYPOT:proc
	extern PALETTE_SHOW:proc
	extern IRAND:proc
	extern TEXT_CLEAR:proc
	extern TEXT_PUTSA:proc
	extern SUPER_FREE:proc
	extern SUPER_ENTRY_BFNT:proc
	extern SUPER_PUT_RECT:proc
	extern SUPER_PUT:proc
	extern SUPER_CONVERT_TINY:proc
	extern SUPER_PUT_TINY_SMALL:proc
	extern GRAPH_GAIJI_PUTS:proc
	extern GRAPH_GAIJI_PUTC:proc
_TEXT ends

; ===========================================================================

CUTSCENE_TEXT segment byte public 'CODE' use16
		assume cs:group_01
		assume es:nothing, ss:nothing, ds:_DATA, fs:nothing, gs:nothing
CUTSCENE_TEXT ends

maine_01_TEXT segment byte public 'CODE' use16
	@wait_flip_and_check_measure_targ$qv procdesc near
maine_01_TEXT ends

SCORE_TEXT segment byte public 'CODE' use16
	@HISCORE_SCOREDAT_LOAD_FOR$QI procdesc pascal near \
		playchar:word
	@hiscore_scoredat_save$qv procdesc near
	; regist_score_enter_from_resident() now lives in
	; th04/hiscore/regist_enter.cpp, at the tail of th05/hi_end.cpp's
	; SCORE_TEXT contribution, i.e. exactly where this block used to begin.
	@regist_score_enter_from_resident$qv procdesc near
	@SCORE_PUT$QII procdesc pascal near \
		place:word, playchar:word
	@STAGE_PUT$QIII procdesc pascal near \
		place:word, playchar:word, gaiji:word
	@NAME_PUT$QI10PLAYCHAR_TUC procdesc pascal near \
		place:word, playchar:byte, cursor:byte
	@PLACE_PUT$QII procdesc pascal near \
		place:word, playchar:word
	@PLACES_PUT$QI procdesc pascal near \
		playchar:word
	@ALPHABET_PUTCA$QIIUI procdesc pascal near \
		col:word, row:word, atrb:word
	@regist_frame_and_flip$qv procdesc near
	@GLYPHBALL_SPAWN$QIII10PLAYCHAR_TUC procdesc pascal near \
		alphabet_col:word, alphabet_row:word, place:word, \
		playchar:byte, slot:byte
	@glyphballs_rush_and_wait$qv procdesc near
	@GRAPH_3_DIGIT_PUT$QIIUI procdesc pascal near \
		left:word, top:word, num:word
	GRAPH_SCORE_AND_TEN_PUT procdesc pascal near \
		left:word, top:word, score:dword
	@SKILL_APPLY_AND_GRAPH_PERCENTAGE$QIIUIUI procdesc pascal near \
		left:word, top:word, total:word, share:word
	@GRAPH_FRACTION_OF_MILLION_PUT$QIIUL procdesc pascal near \
		left:word, top:word, num:dword
	; The per-stage score table, now at the tail of this segment in
	; th05/end/verdict_scores.cpp. staffroll_animate() still calls it
	; from maine_01__TEXT, which stays a near call because group_01
	; spans both segments.
	@verdict_stage_scores_put$qv procdesc near

; The C++ contribution to SCORE_TEXT that precedes this block now ends
; with alphabet_putca() (th04/hiscore/regist_view.cpp); that file's other
; five functions, and regist_score_enter_from_resident()
; (th04/hiscore/regist_enter.cpp), are the six before it. All seven were
; lifted out of the head of this block. Nothing may be added above this
; line.


; ALL SIX functions of this dump's high score table cluster now live in
; th04/hiscore/regist_view.cpp -- score_put(), stage_put(), name_put(),
; place_put(), places_put() and alphabet_putca(), in that order,
; immediately after regist_score_enter_from_resident() at the tail of
; th05/hi_end.cpp's SCORE_TEXT contribution, i.e. exactly where this
; block used to continue. Their four `jmp cs:` switch tables and the
; alignment bytes ahead of three of them went with them; Turbo C++
; emits all of it from the `switch(playchar)` statements.

; kb/codegen/0121: none of the deleted bodies contained an `assume`, so
; the state the rest of this contribution is assembled under is unchanged.
; The three procs that used to open this block -- sub_BD1E, sub_BD46 and
; sub_BE76, TH05's glyph ball animation for the name registration screen --
; now live in th05/regist.cpp. That object contributes to SCORE_TEXT
; immediately ahead of this one (Tupfile.lua lists it directly before this
; dump), so the lifted bodies land at their original addresses by growing
; that contribution: a kb/codegen/0098 head lift with no carve, no new
; segment, no group-list edit and no Tupfile.lua line. Their two `jmp cs:`
; switch tables and the alignment byte ahead of each went with them, and
; none of them contained an `assume` either (kb/codegen/0121). The proc
; that followed them went the same way, into the same object, as
; glyphballs_rush_and_wait().
; Nothing may be added above this line.

; Still needed to type _glyphballs in this dump's BSS. The GBP_* phase
; equates that used to sit here went with regist_menu(), which was their
; last user in this file; th05/regist.cpp declares them as an enum.
glyphball_t struc
	GB_phase	db ?
	GB_glyph	db ?
	GB_pos	motion_t <?>
	GB_target	Point <?>
	GB_angle	db ?
	GB_speed	db ?
	GB_phase_frame	dw ?
		db 6 dup (?)
glyphball_t ends


; ...and regist_menu(), the name registration screen itself, is now the tail
; of th05/regist.cpp -- the same object, immediately after
; glyphballs_rush_and_wait(), which it calls. ONE body serves both games;
; TH04's copy of it is the last #include of th04/hiscore/end.cpp. Same
; kb/codegen/0098 head lift as everything above, and it too contained no
; `assume` (kb/codegen/0121). The strings it passes stay in this dump's
; _DATA and are published there, because the two Japanese messages are
; byte-identical to each other and `-d` would merge a C++ literal pair into
; one.
; Nothing may be added above this line.


; graph_3_digit_put() now lives in th04/end/verdict_digits.cpp, the last
; #include of th05/regist.cpp -- the object that already contributed to this
; segment immediately AHEAD of this block, so the lifted body lands at its
; original address by growing that object's tail into the hole
; (kb/codegen/0098 + 0114). It was the FIRST proc of this contribution;
; nothing else moved, no carve, no new segment, no group-list edit and no
; Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`, so the state the
; rest of this contribution is assembled under is unchanged.
;
; Nothing may be added above this line.


; This block's second proc -- the nine-digit LEBCD score renderer that
; appends the Shift-JIS points label -- now lives in
; th04/end/verdict_digits.cpp as
; graph_score_and_ten_put(), immediately after graph_3_digit_put() and
; therefore immediately after the previous head lift. th05/regist.cpp
; contributes to this segment right before this block, so it lands at its
; original address by growing that object's tail (kb/codegen/0098 + 0114).
; No carve, no new segment, no group-list edit, no Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added above this line.


; skill_apply_and_graph_percentage() and graph_fraction_of_million_put()
; now live in th04/end/verdict_digits.cpp, after graph_score_and_ten_put()
; and therefore still in this block's original order. th05/regist.cpp
; contributes to this segment right before this block, so both land at
; their original addresses by growing that object's tail
; (kb/codegen/0098 + 0114). No carve, no new segment, no group-list edit,
; no Tupfile.lua line.
;
; kb/codegen/0121: neither deleted body contained an `assume`.
;
; Nothing may be added above this line.


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_C8AE	proc near

var_4		= dword	ptr -4

		enter	4, 0
		les	bx, _resident
		mov	eax, es:[bx+resident_t.rand]
		mov	random_seed, eax
		mov	al, es:[bx+resident_t.credit_lives]
		mov	ah, 0
		dec	ax
		mov	bx, ax
		cmp	bx, 5
		ja	short loc_C90E
		add	bx, bx
		jmp	cs:off_C9F6[bx]

loc_C8D4:
		mov	[bp+var_4], 2500
		jmp	short loc_C90E
; ---------------------------------------------------------------------------

loc_C8DE:
		mov	[bp+var_4], 2000
		jmp	short loc_C90E
; ---------------------------------------------------------------------------

loc_C8E8:
		mov	[bp+var_4], 1500
		jmp	short loc_C90E
; ---------------------------------------------------------------------------

loc_C8F2:
		mov	[bp+var_4], 1000
		jmp	short loc_C90E
; ---------------------------------------------------------------------------

loc_C8FC:
		mov	[bp+var_4], 500
		jmp	short loc_C90E
; ---------------------------------------------------------------------------

loc_C906:
		mov	[bp+var_4], 0

loc_C90E:
		les	bx, _resident
		mov	al, es:[bx+resident_t.credit_bombs]
		mov	ah, 0
		or	ax, ax
		jz	short loc_C928
		cmp	ax, 1
		jz	short loc_C932
		cmp	ax, 2
		jz	short loc_C93C
		jmp	short loc_C944
; ---------------------------------------------------------------------------

loc_C928:
		add	[bp+var_4], 2500
		jmp	short loc_C944
; ---------------------------------------------------------------------------

loc_C932:
		add	[bp+var_4], 1500
		jmp	short loc_C944
; ---------------------------------------------------------------------------

loc_C93C:
		add	[bp+var_4], 1000

loc_C944:
		les	bx, _resident
		cmp	es:[bx+resident_t.turbo_mode], 0
		jz	short loc_C957
		add	[bp+var_4], 2000

loc_C957:
		les	bx, _resident
		cmp	es:[bx+resident_t.graze], 0
		jz	short loc_C971
		mov	ax, es:[bx+resident_t.graze]
		imul	ax, 3
		movzx	eax, ax
		add	[bp+var_4], eax

loc_C971:
		les	bx, _resident
		mov	al, es:[bx+resident_t.miss_count]
		mov	ah, 0
		mov	dl, es:[bx+resident_t.bombs_used]
		mov	dh, 0
		sub	ax, dx
		cwde
		imul	eax, 200
		add	[bp+var_4], eax
		cmp	[bp+var_4], 0
		jge	short loc_C9A1
		mov	[bp+var_4], 0
		jmp	short loc_C9B3
; ---------------------------------------------------------------------------

loc_C9A1:
		cmp	[bp+var_4], 10000
		jle	short loc_C9B3
		mov	[bp+var_4], 10000

loc_C9B3:
		mov	eax, [bp+var_4]
		imul	eax, 100
		mov	[bp+var_4], eax
		add	_skill, eax
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 216
		push	ax	; top
		pushd	[bp+var_4]	; num
		call	@graph_fraction_of_million_put$qiiul
		mov	ax, x_116E2
		add	ax, 272
		push	ax
		mov	ax, y_116E8
		add	ax, 216
		push	ax
		push	col_116E4
		push	ds
		push	offset aBu_0
		call	graph_putsa_fx
		leave
		retn
sub_C8AE	endp

; ---------------------------------------------------------------------------
off_C9F6	dw offset loc_C8D4
		dw offset loc_C8DE
		dw offset loc_C8E8
		dw offset loc_C8F2
		dw offset loc_C8FC
		dw offset loc_C906

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_CA02	proc near
		push	bp
		mov	bp, sp
		les	bx, _resident
		cmp	es:[bx+resident_t.end_sequence], ES_GOOD
		jz	short loc_CA17
		cmp	es:[bx+resident_t.end_sequence], ES_EXTRA
		jnz	short loc_CA57

loc_CA17:
		les	bx, _resident
		cmp	es:[bx+resident_t.rank], RANK_EASY
		jnz	short loc_CA26
		mov	al, 4
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA26:
		les	bx, _resident
		cmp	byte ptr es:[bx+score_last][7], 7
		ja	short loc_CA35
		mov	al, 1
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA35:
		les	bx, _resident
		cmp	es:[bx+resident_t.miss_count], 6
		jb	short loc_CA44
		mov	al, 7
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA44:
		les	bx, _resident
		cmp	es:[bx+resident_t.RESIDENT_unknown], 15
		jb	short loc_CA53
		mov	al, 8
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA53:
		mov	al, 0
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA57:
		les	bx, _resident
		cmp	es:[bx+resident_t.end_sequence], ES_BAD
		jnz	short loc_CA66
		mov	al, 2
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA66:
		les	bx, _resident
		mov	al, es:[bx+resident_t.bombs_used]
		mov	ah, 0
		mov	dl, es:[bx+resident_t.miss_count]
		mov	dh, 0
		add	dx, dx
		cmp	ax, dx
		jg	short loc_CA80
		mov	al, 5
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA80:
		les	bx, _resident
		cmp	es:[bx+resident_t.stage], 4
		jb	short loc_CA97
		cmp	es:[bx+resident_t.point_items_collected], 350
		ja	short loc_CA97
		mov	al, 6
		pop	bp
		retn
; ---------------------------------------------------------------------------

loc_CA97:
		mov	al, 3
		pop	bp
		retn
sub_CA02	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_CA9B	proc near

var_4		= dword	ptr -4

		enter	4, 0
		push	si
		mov	_skill, 0
		mov	_graph_putsa_fx_func, FX_WEIGHT_BOLD
		call	graph_putsa_fx pascal, x_116E2, y_116E8, col_116E4, ds, offset aB@b@b@b@b@b@b@ ; "　　　　　　　 腕前判定"
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 24
		push	ax
		push	col_116E4
		push	ds
		push	offset aUqiUx	; "難易度"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 48
		push	ax
		push	col_116E4
		push	ds
		push	offset aNPiuU_	; "最終得点"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 72
		push	ax
		push	col_116E4
		push	ds
		push	offset aGGxi
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 96
		push	ax
		push	col_116E4
		push	ds
		push	offset aGGaogcpi
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 120
		push	ax
		push	col_116E4
		push	ds
		push	offset aGqbGatbrmcj ; "ゲーム達成率"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 144
		push	ax
		push	col_116E4
		push	ds
		push	offset aIlcSObcj ; "悪霊退治率"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 168
		push	ax
		push	col_116E4
		push	ds
		push	offset aGagcgegai
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 192
		push	ax
		push	col_116E4
		push	ds
		push	offset aUU_gagcgeganNv ; "得点アイテム最高点率"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 216
		push	ax
		push	col_116E4
		push	ds
		push	offset aLcnzvv	; "気合い"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 240
		push	ax
		push	col_116E4
		push	ds
		push	offset aPicacovCj ; "処理落ち率"
		call	graph_putsa_fx
		push	x_116E2
		mov	ax, y_116E8
		add	ax, 272
		push	ax
		push	col_116E4
		push	ds
		push	offset aVavVVSrso ; "あなたの腕前"
		call	graph_putsa_fx
		les	bx, _resident
		cmp	es:[bx+resident_t.stage], STAGE_EXTRA
		jnz	short loc_CBDB
		mov	al, RANK_EXTRA
		jmp	short loc_CBE3
; ---------------------------------------------------------------------------

loc_CBDB:
		les	bx, _resident
		mov	al, es:[bx+resident_t.rank]

loc_CBE3:
		mov	_verdict_rank, al
		mov	ax, x_116E2
		add	ax, 160
		push	ax
		mov	ax, y_116E8
		add	ax, 24
		push	ax
		push	GAIJI_W
		push	ds
		mov	al, _verdict_rank
		mov	ah, 0
		shl	ax, 3
		add	ax, offset grEASY
		push	ax
		push	col_116E4
		call	graph_gaiji_puts
		mov	ax, x_116E2
		add	ax, 128
		push	ax
		mov	ax, y_116E8
		add	ax, 48
		push	ax
		mov	ax, word ptr _resident
		add	ax, 20h	; ' '
		push	word ptr _resident+2
		push	ax
		call	GRAPH_SCORE_AND_TEN_PUT
		mov	ax, x_116E2
		add	ax, 224
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 72
		push	ax	; top
		les	bx, _resident
		mov	al, es:[bx+resident_t.miss_count]
		mov	ah, 0
		push	ax	; num
		call	@graph_3_digit_put$qiiui
		mov	ax, x_116E2
		add	ax, 224
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 96
		push	ax	; top
		les	bx, _resident
		mov	al, es:[bx+resident_t.bombs_used]
		mov	ah, 0
		push	ax	; num
		call	@graph_3_digit_put$qiiui
		mov	ax, x_116E2
		add	ax, 272
		push	ax
		mov	ax, y_116E8
		add	ax, 72
		push	ax
		push	col_116E4
		push	ds
		push	offset aI
		call	graph_putsa_fx
		mov	ax, x_116E2
		add	ax, 272
		push	ax
		mov	ax, y_116E8
		add	ax, 96
		push	ax
		push	col_116E4
		push	ds
		push	offset aI_0
		call	graph_putsa_fx
		mov	byte_1517C, 1
		les	bx, _resident
		cmp	es:[bx+resident_t.stage], STAGE_EXTRA
		jz	short loc_CCC6
		cmp	es:[bx+resident_t.end_sequence], ES_BAD
		jb	short loc_CCB3
		mov	es:[bx+resident_t.std_frames], 46000

loc_CCB3:
		mov	ax, x_116E2
		add	ax, 176
		push	ax
		mov	ax, y_116E8
		add	ax, 120
		push	ax
		push	46000
		jmp	short loc_CCE8
; ---------------------------------------------------------------------------

loc_CCC6:
		les	bx, _resident
		cmp	es:[bx+resident_t.end_sequence], ES_EXTRA
		jnz	short loc_CCD7
		mov	es:[bx+resident_t.std_frames], 12800

loc_CCD7:
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 120
		push	ax	; top
		push	12800	; total

loc_CCE8:
		les	bx, _resident
		push	es:[bx+resident_t.std_frames]	; share
		call	@skill_apply_and_graph_percentage$qiiuiui
		mov	byte_1517C, 0
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 144
		push	ax	; top
		les	bx, _resident
		push	es:[bx+resident_t.enemies_gone]	; total
		push	es:[bx+resident_t.enemies_killed]	; share
		call	@skill_apply_and_graph_percentage$qiiuiui
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 168
		push	ax	; top
		les	bx, _resident
		push	es:[bx+resident_t.items_spawned]	; total
		push	es:[bx+resident_t.items_collected]	; share
		call	@skill_apply_and_graph_percentage$qiiuiui
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 192
		push	ax	; top
		les	bx, _resident
		push	es:[bx+resident_t.point_items_collected]	; total
		push	es:[bx+resident_t.max_valued_point_items_collected]	; share
		call	@skill_apply_and_graph_percentage$qiiuiui
		call	sub_C8AE
		mov	_skill_subtract, 1
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 240
		push	ax	; top
		les	bx, _resident
		mov	eax, es:[bx+resident_t.frames]
		mov	ebx, 10
		xor	edx, edx
		div	ebx
		push	ax	; total
		mov	bx, word ptr _resident
		mov	eax, es:[bx+resident_t.slow_frames]
		mov	ebx, 10
		xor	edx, edx
		div	ebx
		push	ax	; share
		call	@skill_apply_and_graph_percentage$qiiuiui
		mov	_skill_subtract, 0
		mov	ebx, 12
		mov	eax, _skill
		cdq
		idiv	ebx
		mov	_skill, eax
		mov	eax, dword_15182
		add	_skill, eax
		les	bx, _resident
		cmp	es:[bx+resident_t.score_highest][7], 10
		jb	short loc_CDCB
		add	_skill, 500000
		jmp	short loc_CDF3
; ---------------------------------------------------------------------------

loc_CDCB:
		les	bx, _resident
		movzx	eax, es:[bx+resident_t.score_highest][6]
		imul	eax, 5000
		add	_skill, eax
		movzx	eax, es:[bx+resident_t.score_highest][7]
		imul	eax, 50000
		add	_skill, eax

loc_CDF3:
		mov	al, _verdict_rank
		mov	ah, 0
		mov	bx, ax
		cmp	bx, RANK_EXTRA
		ja	loc_CEAF
		add	bx, bx
		jmp	cs:off_D165[bx]

loc_CE08:
		sub	_skill, 50000
		mov	[bp+var_4], 800000
		jmp	loc_CEAF
; ---------------------------------------------------------------------------

loc_CE1C:
		mov	[bp+var_4], 1000000
		; Hack (jmp	loc_CEAF)
		; No idea why TASM can't assemble this properly after
		; scoredat_load_for() was decompiled.
		db	0E9h, 88h, 00h
; ---------------------------------------------------------------------------

loc_CE27:
		mov	eax, _skill
		imul	eax, 5
		mov	_skill, eax
		mov	ebx, 4
		cdq
		idiv	ebx
		mov	_skill, eax
		add	_skill, 150000
		mov	[bp+var_4], 1200000
		jmp	short loc_CEAF
; ---------------------------------------------------------------------------

loc_CE55:
		mov	eax, _skill
		imul	eax, 3
		mov	_skill, eax
		mov	ebx, 2
		cdq
		idiv	ebx
		mov	_skill, eax
		add	_skill, 300000
		mov	[bp+var_4], 1400000
		jmp	short loc_CEAF
; ---------------------------------------------------------------------------

loc_CE83:
		mov	eax, _skill
		imul	eax, 3
		mov	_skill, eax
		mov	ebx, 2
		cdq
		idiv	ebx
		mov	_skill, eax
		add	_skill, 250000
		mov	[bp+var_4], 2000000

loc_CEAF:
		les	bx, _resident
		mov	al, es:[bx+resident_t.credit_lives]
		mov	ah, 0
		dec	ax
		mov	bx, ax
		cmp	bx, 5
		ja	short loc_CF0A
		add	bx, bx
		jmp	cs:off_D159[bx]

loc_CEC8:
		add	_skill, 50000
		add	[bp+var_4], 100000
		jmp	short loc_CF0A
; ---------------------------------------------------------------------------

loc_CEDB:
		add	_skill, 25000
		add	[bp+var_4], 50000
		jmp	short loc_CF0A
; ---------------------------------------------------------------------------

loc_CEEE:
		sub	[bp+var_4], 25000
		jmp	short loc_CF0A
; ---------------------------------------------------------------------------

loc_CEF8:
		sub	[bp+var_4], 50000
		jmp	short loc_CF0A
; ---------------------------------------------------------------------------

loc_CF02:
		sub	[bp+var_4], 75000

loc_CF0A:
		les	bx, _resident
		mov	al, es:[bx+resident_t.credit_bombs]
		mov	ah, 0
		or	ax, ax
		jz	short loc_CF24
		cmp	ax, 1
		jz	short loc_CF37
		cmp	ax, 2
		jz	short loc_CF4A
		jmp	short loc_CF5B
; ---------------------------------------------------------------------------

loc_CF24:
		add	_skill, 50000
		add	[bp+var_4], 100000
		jmp	short loc_CF5B
; ---------------------------------------------------------------------------

loc_CF37:
		add	_skill, 30000
		add	[bp+var_4], 50000
		jmp	short loc_CF5B
; ---------------------------------------------------------------------------

loc_CF4A:
		add	_skill, 20000
		add	[bp+var_4], 25000

loc_CF5B:
		les	bx, _resident
		cmp	es:[bx+resident_t.turbo_mode], 0
		jnz	short loc_CF77
		sub	_skill, 200000
		sub	[bp+var_4], 100000

loc_CF77:
		les	bx, _resident
		cmp	es:[bx+resident_t.miss_count], 10
		jb	short loc_CF8D
		sub	_skill, 300000
		jmp	short loc_CFA3
; ---------------------------------------------------------------------------

loc_CF8D:
		les	bx, _resident
		movzx	eax, es:[bx+resident_t.miss_count]
		imul	eax, 30000
		sub	_skill, eax

loc_CFA3:
		les	bx, _resident
		cmp	es:[bx+resident_t.bombs_used], 15
		jb	short loc_CFB9
		sub	_skill, 225000
		jmp	short loc_CFCF
; ---------------------------------------------------------------------------

loc_CFB9:
		les	bx, _resident
		movzx	eax, es:[bx+resident_t.bombs_used]
		imul	eax, 15000
		sub	_skill, eax

loc_CFCF:
		les	bx, _resident
		cmp	es:[bx+resident_t.end_sequence], ES_EXTRA
		jnb	short loc_CFF5
		mov	eax, _skill
		imul	eax, 7
		mov	_skill, eax
		mov	ebx, 8
		cdq
		idiv	ebx
		mov	_skill, eax

loc_CFF5:
		cmp	_skill, 0
		jge	short loc_D008
		mov	_skill, 0
		jmp	short loc_D01A
; ---------------------------------------------------------------------------

loc_D008:
		mov	eax, _skill
		cmp	eax, [bp+var_4]
		jbe	short loc_D01A
		mov	eax, [bp+var_4]
		mov	_skill, eax

loc_D01A:
		mov	byte_15187, 0
		mov	byte_151A5, 0
		les	bx, _resident
		mov	eax, es:[bx+resident_t.frames]
		shr	eax, 1
		cmp	eax, es:[bx+resident_t.slow_frames]
		jbe	loc_D120
		mov	ax, x_116E2
		add	ax, 176
		push	ax	; left
		mov	ax, y_116E8
		add	ax, 272
		push	ax	; top
		pushd	[_skill]	; num
		call	@graph_fraction_of_million_put$qiiul
		mov	ax, x_116E2
		add	ax, 272
		push	ax
		mov	ax, y_116E8
		add	ax, 272
		push	ax
		push	col_116E4
		push	ds
		push	offset aU_
		call	graph_putsa_fx
		push	ds
		push	offset a_ude_txt ; "_ude.txt"
		call	file_ropen
		cmp	_skill, 1500000
		jge	short loc_D0E1
		cmp	_skill, 0
		jnz	short loc_D08B
		mov	si, 19h
		jmp	short loc_D0D1
; ---------------------------------------------------------------------------

loc_D08B:
		cmp	_skill, 1050000
		jge	short loc_D0AE
		mov	eax, _skill
		mov	ebx, 50000
		cdq
		idiv	ebx
		mov	dx, 24
		sub	dx, ax
		mov	si, dx
		jmp	short loc_D0D1
; ---------------------------------------------------------------------------

loc_D0AE:
		cmp	_skill, 1200000
		jge	short loc_D0BE
		mov	si, 3
		jmp	short loc_D0D1
; ---------------------------------------------------------------------------

loc_D0BE:
		cmp	_skill, 1350000
		jge	short loc_D0CE
		mov	si, 2
		jmp	short loc_D0D1
; ---------------------------------------------------------------------------

loc_D0CE:
		mov	si, 1

loc_D0D1:
		mov	ax, si
		imul	ax, 1Eh
		cwde
		push	eax
		push	0
		call	file_seek

loc_D0E1:
		push	ds
		push	offset byte_15187
		push	1Eh
		call	file_read
		call	sub_CA02
		mov	ah, 0
		mov	si, ax
		imul	ax, 1Eh
		add	ax, 780
		cwde
		push	eax
		push	0
		call	file_seek
		push	ds
		push	offset byte_151A5
		push	1Eh
		call	file_read
		call	file_close
		mov	byte_151A3, 0
		mov	byte_151C1, 0
		jmp	short loc_D156
; ---------------------------------------------------------------------------

loc_D120:
		mov	ax, x_116E2
		add	ax, 176
		push	ax
		mov	ax, y_116E8
		add	ax, 272
		push	ax
		push	col_116E4
		push	ds
		push	offset aBhbhbhbhbhbhu_ ; "？？？？？？点"
		call	graph_putsa_fx
		mov	ax, x_116E2
		add	ax, 48
		push	ax
		mov	ax, y_116E8
		add	ax, 296
		push	ax
		push	word_116E6
		push	ds
		push	offset aPicacovVVcvsfT ; "処理落ちによる判定不可"
		call	graph_putsa_fx

loc_D156:
		pop	si
		leave
		retn
sub_CA9B	endp

; ---------------------------------------------------------------------------
off_D159	dw offset loc_CEC8
		dw offset loc_CEDB
		dw offset loc_CF0A
		dw offset loc_CEEE
		dw offset loc_CEF8
		dw offset loc_CF02
off_D165	dw offset loc_CE08
		dw offset loc_CE1C
		dw offset loc_CE27
		dw offset loc_CE55
		dw offset loc_CE83

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D16F	proc near
		push	bp
		mov	bp, sp
		cmp	byte_15187, 0
		jz	short loc_D1AF
		mov	ax, x_116E2
		add	ax, 48
		push	ax
		mov	ax, y_116E8
		add	ax, 296
		push	ax
		push	word_116E6
		push	ds
		push	offset byte_15187
		call	graph_putsa_fx
		mov	ax, x_116E2
		add	ax, 48
		push	ax
		mov	ax, y_116E8
		add	ax, 312
		push	ax
		push	word_116E6
		push	ds
		push	offset byte_151A5
		call	graph_putsa_fx

loc_D1AF:
		pop	bp
		retn
sub_D16F	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @verdict_animate$qv
@verdict_animate$qv proc near
		push	bp
		mov	bp, sp
		mov	PaletteTone, 0
		call	far ptr	palette_show
		graph_accesspage 1
		call	@pi_load$qinxc pascal, 0, ds, offset aUde_pi
		call	@pi_palette_apply$qi pascal, 0
		call	@pi_put_8$qiii pascal, large 0, 0
		call	@pi_free$qi pascal, 0
		call	graph_copy_page pascal, 0
		push	4
		call	palette_black_in
		graph_accesspage 0
		graph_showpage al
		call	sub_CA9B
		call	@frame_delay$qi pascal, 64
		call	sub_D16F
		call	@input_wait_for_change$qi pascal, 0
		push	2
		call	palette_black_out
		pop	bp
		retn
@verdict_animate$qv endp


; This block's last proc -- the verdict screen's per-stage score table --
; now lives in th05/end/verdict_scores.cpp as verdict_stage_scores_put(),
; included from th05/staff.cpp. That object contributes to this segment
; immediately after this block, so the body lands at its original address
; by growing that object's head (kb/codegen/0099 + 0114). No carve, no new
; segment, no group-list edit, no Tupfile.lua line.
;
; kb/codegen/0121: the deleted body contained no `assume`.
;
; Nothing may be added below this line.
SCORE_TEXT	ends

maine_01__TEXT	segment	byte public 'CODE' use16
	@SPACE_WINDOW_SET$QIIII procdesc pascal near \
		center_x:word, center_y:word, w:word, h:word

ORB_PARTICLE_CELS = 6
PAT_ORB_PARTICLE = 0
PAT_ORB_PARTICLE_last = (PAT_ORB_PARTICLE + ORB_PARTICLE_CELS - 1)
PAT_STAR_BIG = (PAT_ORB_PARTICLE + ORB_PARTICLE_CELS - 1) + 1
PAT_STAR_SMALL = PAT_STAR_BIG + 1

ORB_RADIUS_FULL = 16
ORB_W = 32
ORB_H = 32

X_RIGHT = 0
X_LEFT = 1

orb_particle_t struc
	OP_center_x	dd ?
	OP_center_y	dd ?
	OP_velocity	Point <?>
	OP_patnum_tiny	dw ?
	OP_speed	dw ?
	OP_gather_frame dw ?
	OP_angle	db ?
	OP_al_radius	label byte
	OP_al_rain_sway_x_direction	label byte
		db ?
orb_particle_t ends

ORB_PARTICLE_COUNT = 64
ORB_TRAIL_COUNT = 8
STAR_COUNT = 48
ORB_INDEX = ORB_PARTICLE_COUNT
orb	equ <_particles[ORB_INDEX * size orb_particle_t]>

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D387	proc near

@@star_center		= word ptr -4
@@trail_center		= word ptr -2

		enter	4, 0
		push	si
		push	di
		mov	si, offset _particles
		mov	[bp+@@trail_center], offset _orb_trails_center
		mov	[bp+@@star_center], offset _stars_center
		push	((RES_X / 2) shl 16) or (RES_Y / 2)	; (center_x shl 16) or center_y
		push	(384 shl 16) or 320               	; (w shl 16) or h
		call	@space_window_set$qiiii
		mov	word_151DE, 0
		xor	di, di
		jmp	short loc_D41B
; ---------------------------------------------------------------------------

loc_D3B3:
		call	IRand
		cwd
		idiv	_space_window_w
		shl	dx, 4
		mov	ax, _space_window_w
		shl	ax, 3
		sub	dx, ax
		movsx	eax, dx
		mov	[si+orb_particle_t.OP_center_x], eax
		call	IRand
		cwd
		idiv	_space_window_h
		shl	dx, 4
		mov	ax, _space_window_h
		shl	ax, 3
		sub	dx, ax
		movsx	eax, dx
		mov	[si+orb_particle_t.OP_center_y], eax
		call	IRand
		mov	[si+orb_particle_t.OP_angle], al
		mov	[si+orb_particle_t.OP_speed], (0 shl 4) + 10
		mov	[si+orb_particle_t.OP_patnum_tiny], PAT_ORB_PARTICLE
		mov	[si+orb_particle_t.OP_al_rain_sway_x_direction], X_RIGHT
		lea	ax, [si+orb_particle_t.OP_velocity]
		push	ax
		pushd	0
		push	[si+orb_particle_t.OP_speed]
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at
		inc	di
		add	si, size orb_particle_t

loc_D41B:
		cmp	di, ORB_PARTICLE_COUNT
		jl	short loc_D3B3
		; si == particles[ORB_INDEX]
		mov	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		mov	[si+orb_particle_t.OP_al_radius], 0
		mov	[si+orb_particle_t.OP_velocity.x], 0
		mov	[si+orb_particle_t.OP_velocity.y], 0
		mov	_space_camera_velocity.x, 0
		mov	_space_camera_velocity.y, 0
		xor	di, di
		jmp	short loc_D451
; ---------------------------------------------------------------------------

loc_D445:
		mov	bx, [bp+@@trail_center]
		mov	[bx+Point.x], SUBPIXEL_NONE
		inc	di
		add	[bp+@@trail_center], size Point

loc_D451:
		cmp	di, ORB_TRAIL_COUNT
		jl	short loc_D445
		xor	di, di
		jmp	short loc_D494
; ---------------------------------------------------------------------------

loc_D45A:
		call	IRand
		cwd
		idiv	_space_window_w
		shl	dx, 4
		mov	ax, _space_window_w
		shl	ax, 3
		sub	dx, ax
		mov	bx, [bp+@@star_center]
		mov	[bx+Point.x], dx
		call	IRand
		cwd
		idiv	_space_window_h
		shl	dx, 4
		mov	ax, _space_window_h
		shl	ax, 3
		sub	dx, ax
		mov	bx, [bp+@@star_center]
		mov	[bx+Point.y], dx
		inc	di
		add	[bp+@@star_center], size Point

loc_D494:
		cmp	di, STAR_COUNT
		jl	short loc_D45A
		pop	di
		pop	si
		leave
		retn
sub_D387	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D49D	proc near
		push	bp
		mov	bp, sp
		push	si
		push	di
		mov	si, offset _particles
		xor	di, di
		jmp	short loc_D4ED
; ---------------------------------------------------------------------------

loc_D4A9:
		mov	ax, word ptr [si+orb_particle_t.OP_center_y]
		neg	ax
		push	ax
		mov	ax, word ptr [si+orb_particle_t.OP_center_x]
		neg	ax
		push	ax
		call	iatan2
		mov	[si+orb_particle_t.OP_angle], al
		push	word ptr [si+orb_particle_t.OP_center_x]
		push	word ptr [si+orb_particle_t.OP_center_y]
		call	ihypot
		mov	bx, 32
		cwd
		idiv	bx
		mov	[si+orb_particle_t.OP_speed], ax
		mov	[si+orb_particle_t.OP_gather_frame], 0
		lea	ax, [si+orb_particle_t.OP_velocity]
		push	ax
		pushd	0
		push	[si+orb_particle_t.OP_speed]
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at
		inc	di
		add	si, size orb_particle_t

loc_D4ED:
		cmp	di, ORB_PARTICLE_COUNT
		jl	short loc_D4A9
		; si == particles[ORB_INDEX]
		mov	[si+orb_particle_t.OP_center_x], 0
		mov	[si+orb_particle_t.OP_center_y], 0
		mov	[si+orb_particle_t.OP_al_radius], 1
		pop	di
		pop	si
		pop	bp
		retn
sub_D49D	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D509	proc near
		push	bp
		mov	bp, sp
		push	si
		mov	si, offset _particles
		xor	ax, ax
		jmp	short loc_D51F
; ---------------------------------------------------------------------------

loc_D514:
		mov	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		inc	ax
		add	si, size orb_particle_t

loc_D51F:
		cmp	ax, ORB_PARTICLE_COUNT
		jl	short loc_D514
		; si == particles[ORB_INDEX]
		mov	[si+orb_particle_t.OP_al_radius], ORB_RADIUS_FULL
		mov	word_151DE, 1
		pop	si
		pop	bp
		retn
sub_D509	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D531	proc near
		push	bp
		mov	bp, sp
		push	si
		push	di
		mov	si, offset _particles
		xor	di, di
		jmp	loc_D5C9
; ---------------------------------------------------------------------------

loc_D53E:
		mov	ax, word ptr [si+orb_particle_t.OP_center_y]
		neg	ax
		push	ax
		mov	ax, word ptr [si+orb_particle_t.OP_center_x]
		neg	ax
		push	ax
		call	iatan2
		mov	[si+orb_particle_t.OP_angle], al
		push	word ptr [si+orb_particle_t.OP_center_x]
		push	word ptr [si+orb_particle_t.OP_center_y]
		call	ihypot
		mov	bx, 32
		cwd
		idiv	bx
		mov	[si+orb_particle_t.OP_speed], ax
		mov	[si+orb_particle_t.OP_patnum_tiny], PAT_ORB_PARTICLE
		call	IRand
		and	al, 7Fh
		mov	[si+orb_particle_t.OP_angle], al
		call	IRand
		mov	bx, (4 shl 4)
		cwd
		idiv	bx
		add	dx, (5 shl 4) + 12
		mov	[si+orb_particle_t.OP_speed], dx
		push	offset point_151D2
		push	word ptr orb.OP_center_x
		push	word ptr orb.OP_center_y
		push	(12 shl 4)
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at
		lea	ax, [si+orb_particle_t.OP_velocity]
		push	ax
		pushd	0
		push	[si+orb_particle_t.OP_speed]
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at
		movsx	eax, point_151D2.x
		mov	[si+orb_particle_t.OP_center_x], eax
		movsx	eax, point_151D2.y
		mov	[si+orb_particle_t.OP_center_y], eax
		inc	di
		add	si, size orb_particle_t

loc_D5C9:
		cmp	di, ORB_PARTICLE_COUNT
		jl	loc_D53E
		; si == particles[ORB_INDEX]
		mov	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		mov	word_151DE, 1
		pop	di
		pop	si
		pop	bp
		retn
sub_D531	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D5E1	proc near

@@trail_center		= word ptr -4
@@i		= word ptr -2

		enter	4, 0
		push	si
		push	di
		mov	si, offset _particles
		mov	[bp+@@trail_center], offset _orb_trails_center
		mov	di, offset _stars_center
		mov	[bp+@@i], 0
		jmp	loc_D6FF
; ---------------------------------------------------------------------------

loc_D5FA:
		cmp	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jz	loc_D6F9
		mov	ax, [si+orb_particle_t.OP_velocity.x]
		sub	ax, _space_camera_velocity.x
		cwde
		add	[si+orb_particle_t.OP_center_x], eax
		mov	ax, [si+orb_particle_t.OP_velocity.y]
		sub	ax, _space_camera_velocity.y
		cwde
		add	[si+orb_particle_t.OP_center_y], eax
		cmp	word_151DE, 0
		jnz	loc_D6AB
		mov	ax, _space_window_w
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_x]
		jl	short loc_D649
		mov	ax, _space_window_w
		shl	ax, 4
		add	ax, (8 shl 4)
		cwde
		add	[si+orb_particle_t.OP_center_x], eax
		jmp	short loc_D667
; ---------------------------------------------------------------------------

loc_D649:
		mov	ax, _space_window_w
		shl	ax, 3
		add	ax, (4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_x]
		jg	short loc_D667
		mov	ax, _space_window_w
		shl	ax, 4
		add	ax, (8 shl 4)
		cwde
		sub	[si+orb_particle_t.OP_center_x], eax

loc_D667:
		mov	ax, _space_window_h
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_y]
		jl	short loc_D68B
		mov	ax, _space_window_h
		shl	ax, 4
		add	ax, (8 shl 4)
		cwde
		add	[si+orb_particle_t.OP_center_y], eax
		jmp	short loc_D6AB
; ---------------------------------------------------------------------------

loc_D68B:
		mov	ax, _space_window_h
		shl	ax, 3
		add	ax, (4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_y]
		jg	short loc_D6AB
		mov	ax, _space_window_h
		shl	ax, 4
		add	ax, (8 shl 4)
		cwde
		sub	[si+orb_particle_t.OP_center_y], eax

loc_D6AB:
		cmp	word_151DE, 0
		jz	short loc_D6F9
		mov	ax, word_151DE
		sub	[si+orb_particle_t.OP_speed], ax
		cmp	[si+orb_particle_t.OP_speed], 0
		jnz	short loc_D6C7
		mov	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jmp	short loc_D6F9
; ---------------------------------------------------------------------------

loc_D6C7:
		cmp	[si+orb_particle_t.OP_speed], (2 shl 4) + 3
		jle	short loc_D6D4
		mov	[si+orb_particle_t.OP_patnum_tiny], PAT_ORB_PARTICLE
		jmp	short loc_D6E4
; ---------------------------------------------------------------------------

loc_D6D4:
		mov	ax, [si+orb_particle_t.OP_speed]
		mov	bx, 7
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_D6E4
		inc	[si+orb_particle_t.OP_patnum_tiny]

loc_D6E4:
		lea	ax, [si+orb_particle_t.OP_velocity]
		push	ax
		pushd	0
		push	[si+orb_particle_t.OP_speed]
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at

loc_D6F9:
		inc	[bp+@@i]
		add	si, size orb_particle_t

loc_D6FF:
		cmp	[bp+@@i], ORB_PARTICLE_COUNT
		jl	loc_D5FA
		mov	[bp+@@i], 0
		jmp	short loc_D72C
; ---------------------------------------------------------------------------

loc_D70E:
		mov	bx, [bp+@@trail_center]
		cmp	[bx+Point.x], SUBPIXEL_NONE
		jz	short loc_D725
		mov	bx, [bp+@@trail_center]
		mov	ax, _space_camera_velocity.x
		sub	[bx+Point.x], ax
		mov	ax, _space_camera_velocity.y
		sub	[bx+Point.y], ax

loc_D725:
		inc	[bp+@@i]
		add	[bp+@@trail_center], size Point

loc_D72C:
		cmp	[bp+@@i], ORB_TRAIL_COUNT
		jl	short loc_D70E
		mov	[bp+@@i], 0
		jmp	loc_D7F8
; ---------------------------------------------------------------------------

loc_D73A:
		mov	ax, [bp+@@i]
		mov	bx, 2
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_D751
		mov	ax, _space_camera_velocity.x
		sub	[di+Point.x], ax
		mov	ax, _space_camera_velocity.y
		jmp	short loc_D763
; ---------------------------------------------------------------------------

loc_D751:
		mov	ax, _space_camera_velocity.x
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	[di+Point.x], ax
		mov	ax, _space_camera_velocity.y
		cwd
		sub	ax, dx
		sar	ax, 1

loc_D763:
		sub	[di+Point.y], ax
		cmp	_space_camera_velocity.x, 0
		jnz	short loc_D7A5
		mov	ax, _space_window_w
		neg	ax
		shl	ax, 3
		cmp	ax, [di+Point.x]
		jge	short loc_D783
		mov	ax, _space_window_w
		shl	ax, 3
		cmp	ax, [di+Point.x]
		jg	short loc_D7CA

loc_D783:
		call	IRand
		cwd
		idiv	_space_window_w
		shl	dx, 4
		mov	ax, _space_window_w
		shl	ax, 3
		sub	dx, ax
		mov	[di+Point.x], dx
		mov	ax, _space_window_h
		shl	ax, 3
		mov	[di+Point.y], ax
		jmp	short loc_D7CA
; ---------------------------------------------------------------------------

loc_D7A5:
		mov	ax, _space_window_w
		neg	ax
		shl	ax, 3
		cmp	ax, [di+Point.x]
		jl	short loc_D7B6
		mov	ax, _space_window_w
		jmp	short loc_D7C5
; ---------------------------------------------------------------------------

loc_D7B6:
		mov	ax, _space_window_w
		shl	ax, 3
		cmp	ax, [di+Point.x]
		jg	short loc_D7CA
		mov	ax, _space_window_w
		neg	ax

loc_D7C5:
		shl	ax, 3
		mov	[di+Point.x], ax

loc_D7CA:
		mov	ax, _space_window_h
		neg	ax
		shl	ax, 3
		cmp	ax, [di+Point.y]
		jl	short loc_D7DC
		mov	ax, _space_window_h
		jmp	short loc_D7EC
; ---------------------------------------------------------------------------

loc_D7DC:
		mov	ax, _space_window_h
		shl	ax, 3
		cmp	ax, [di+Point.y]
		jg	short loc_D7F2
		mov	ax, _space_window_h
		neg	ax

loc_D7EC:
		shl	ax, 3
		mov	[di+Point.y], ax

loc_D7F2:
		inc	[bp+@@i]
		add	di, size Point

loc_D7F8:
		cmp	[bp+@@i], STAR_COUNT
		jl	loc_D73A
		mov	si, offset orb
		cmp	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jz	short loc_D83F
		mov	ax, [si+orb_particle_t.OP_velocity.x]
		sub	ax, _space_camera_velocity.x
		cwde
		add	[si+orb_particle_t.OP_center_x], eax
		mov	ax, [si+orb_particle_t.OP_velocity.y]
		sub	ax, _space_camera_velocity.y
		cwde
		add	[si+orb_particle_t.OP_center_y], eax
		cmp	[si+orb_particle_t.OP_al_radius], ORB_RADIUS_FULL
		jb	short loc_D83F
		cmp	byte_1183A, 0
		jz	short loc_D83F
		call	sub_D853
		cmp	[si+orb_particle_t.OP_velocity.y], (11 shl 4) + 4
		jge	short loc_D83F
		inc	[si+orb_particle_t.OP_velocity.y]

loc_D83F:
		mov	ax, word_151E2
		mov	bx, 3
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_D84F
		call	sub_D8B6

loc_D84F:
		pop	di
		pop	si
		leave
		retn
sub_D5E1	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D853	proc near
		push	bp
		mov	bp, sp
		push	si
		mov	ax, particle_i_1183C
		inc	particle_i_1183C
		imul	ax, size orb_particle_t
		add	ax, offset _particles
		mov	si, ax
		mov	[si+orb_particle_t.OP_patnum_tiny], PAT_ORB_PARTICLE
		call	IRand
		and	al, 7Fh
		mov	[si+orb_particle_t.OP_angle], al
		mov	[si+orb_particle_t.OP_speed], (3 shl 4)
		push	offset point_151D2
		push	word ptr orb.OP_center_x
		push	word ptr orb.OP_center_y
		push	(12 shl 4)
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at
		movsx	eax, point_151D2.x
		mov	[si+orb_particle_t.OP_center_x], eax
		movsx	eax, point_151D2.y
		mov	[si+orb_particle_t.OP_center_y], eax
		cmp	particle_i_1183C, ORB_PARTICLE_COUNT
		jl	short loc_D8B3
		mov	particle_i_1183C, 0

loc_D8B3:
		pop	si
		pop	bp
		retn
sub_D853	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D8B6	proc near
		push	bp
		mov	bp, sp
		mov	dx, (ORB_TRAIL_COUNT - 2)
		jmp	short loc_D8E3
; ---------------------------------------------------------------------------

loc_D8BE:
		mov	bx, dx
		shl	bx, 2
		mov	ax, _orb_trails_center[0 * size Point][bx].x
		mov	bx, dx
		shl	bx, 2
		mov	_orb_trails_center[1 * size Point][bx].x, ax
		mov	bx, dx
		shl	bx, 2
		mov	ax, _orb_trails_center[0 * size Point][bx].y
		mov	bx, dx
		shl	bx, 2
		mov	_orb_trails_center[1 * size Point][bx].y, ax
		dec	dx

loc_D8E3:
		or	dx, dx
		jge	short loc_D8BE
		mov	ax, word ptr orb.OP_center_x
		mov	_orb_trails_center[0 * size Point].x, ax
		mov	ax, word ptr orb.OP_center_y
		mov	_orb_trails_center[0 * size Point].y, ax
		pop	bp
		retn
sub_D8B6	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D8F5	proc near
		push	bp
		mov	bp, sp
		push	si
		mov	si, offset _particles
		xor	cx, cx
		jmp	short loc_D91D
; ---------------------------------------------------------------------------

loc_D900:
		inc	[si+orb_particle_t.OP_gather_frame]
		mov	ax, [si+orb_particle_t.OP_gather_frame]
		mov	bx, 8
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_D919
		cmp	[si+orb_particle_t.OP_patnum_tiny], PAT_ORB_PARTICLE_last
		jge	short loc_D919
		inc	[si+orb_particle_t.OP_patnum_tiny]

loc_D919:
		inc	cx
		add	si, size orb_particle_t

loc_D91D:
		cmp	cx, ORB_PARTICLE_COUNT
		jl	short loc_D900
		; si == particles[ORB_INDEX]
		cmp	[si+orb_particle_t.OP_al_radius], ORB_RADIUS_FULL
		jnb	short loc_D92E
		mov	al, byte_1183A
		add	[si+orb_particle_t.OP_al_radius], al

loc_D92E:
		pop	si
		pop	bp
		retn
sub_D8F5	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_D931	proc near

var_2		= word ptr -2

		enter	2, 0
		push	si
		inc	word_1183E
		cmp	word_1183E, 80
		jl	loc_DA31
		cmp	word_1183E, 176
		jge	short loc_D951
		inc	_space_camera_velocity.y
		jmp	short loc_D9B5
; ---------------------------------------------------------------------------

loc_D951:
		cmp	word_1183E, 344
		jge	short loc_D964
		mov	al, byte_1183A
		mov	ah, 0
		add	_space_camera_velocity.y, ax
		jmp	short loc_D9B5
; ---------------------------------------------------------------------------

loc_D964:
		cmp	byte_11840, 0
		jnz	short loc_D991
		mov	ax, word_151E2
		mov	bx, 16
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_D97D
		mov	ax, 1
		jmp	short loc_D97F
; ---------------------------------------------------------------------------

loc_D97D:
		xor	ax, ax

loc_D97F:
		add	_space_camera_velocity.y, ax
		cmp	_space_camera_velocity.y, ((11 shl 4) + 6)
		jle	short loc_D9B5
		inc	byte_11840
		jmp	short loc_D9B5
; ---------------------------------------------------------------------------

loc_D991:
		mov	ax, word_151E2
		mov	bx, 16
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_D9A3
		mov	ax, 1
		jmp	short loc_D9A5
; ---------------------------------------------------------------------------

loc_D9A3:
		xor	ax, ax

loc_D9A5:
		sub	_space_camera_velocity.y, ax
		cmp	_space_camera_velocity.y, ((11 shl 4) + 2)
		jge	short loc_D9B5
		dec	byte_11840

loc_D9B5:
		cmp	word_1183E, 234
		jl	short loc_DA31
		cmp	word_1183E, 512
		jge	short loc_DA04
		mov	ax, word_1183E
		add	ax, -234
		mov	si, ax
		cmp	si, 88
		jle	short loc_D9D7
		add	ax, -88
		jmp	short loc_D9D9
; ---------------------------------------------------------------------------

loc_D9D7:
		xor	ax, ax

loc_D9D9:
		mov	[bp+var_2], ax
		mov	ax, (RES_X / 2)
		sub	ax, [bp+var_2]
		push	ax	; center_x
		push	(RES_Y / 2)	; center_y
		mov	ax, si
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, 384
		sub	dx, ax
		push	dx	; w
		mov	ax, si
		mov	bx, 8
		cwd
		idiv	bx
		add	ax, 320
		push	ax	; h
		call	@space_window_set$qiiii
		jmp	short loc_DA31
; ---------------------------------------------------------------------------

loc_DA04:
		cmp	word_1183E, 992
		jl	short loc_DA18
		cmp	word_1183E, 1024
		jg	short loc_DA18
		dec	orb.OP_velocity.x

loc_DA18:
		cmp	word_1183E, 1008
		jl	short loc_DA2C
		cmp	word_1183E, 1040
		jg	short loc_DA2C
		dec	_space_camera_velocity.x

loc_DA2C:
		mov	ax, 1
		jmp	short loc_DA33
; ---------------------------------------------------------------------------

loc_DA31:
		xor	ax, ax

loc_DA33:
		pop	si
		leave
		retn
sub_D931	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DA36	proc near
		push	bp
		mov	bp, sp
		push	si
		mov	ax, word_11842
		imul	ax, size orb_particle_t
		add	ax, offset _particles
		mov	si, ax
		inc	word_11842
		mov	ax, word_11842
		cmp	ax, 40h
		jge	loc_DAD4
		call	IRand
		mov	bx, (1 shl 4) + 8
		cwd
		idiv	bx
		add	dx, 8
		mov	[si+orb_particle_t.OP_speed], dx
		call	IRand
		mov	bx, 40h
		cwd
		idiv	bx
		add	dl, 20h
		mov	[si+orb_particle_t.OP_angle], dl
		call	IRand
		mov	bx, ORB_PARTICLE_CELS
		cwd
		idiv	bx
		mov	[si+orb_particle_t.OP_patnum_tiny], dx
		call	IRand
		cwd
		idiv	_space_window_w
		shl	dx, 4
		mov	ax, _space_window_w
		shl	ax, 3
		sub	dx, ax
		movsx	eax, dx
		mov	[si+orb_particle_t.OP_center_x], eax
		mov	ax, _space_window_h
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		mov	[si+orb_particle_t.OP_center_y], eax
		cmp	[si+orb_particle_t.OP_angle], 40h
		jnb	short loc_DABA
		mov	al, X_RIGHT
		jmp	short loc_DABC
; ---------------------------------------------------------------------------

loc_DABA:
		mov	al, X_LEFT

loc_DABC:
		mov	[si+orb_particle_t.OP_al_rain_sway_x_direction], al
		lea	ax, [si+orb_particle_t.OP_velocity]
		push	ax
		pushd	0
		push	[si+orb_particle_t.OP_speed]
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at

loc_DAD4:
		pop	si
		pop	bp
		retn
sub_DA36	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DAD7	proc near
		push	bp
		mov	bp, sp
		push	si
		push	di
		mov	si, offset _particles
		cmp	_space_camera_velocity.x, 0
		jge	short loc_DAEF
		mov	al, byte_1183A
		mov	ah, 0
		add	_space_camera_velocity.x, ax

loc_DAEF:
		inc	word_11844
		cmp	word_11844, 32
		jl	loc_DBE0
		cmp	word_11844, 128
		jge	short loc_DB0B
		dec	_space_camera_velocity.y
		jmp	loc_DBC3
; ---------------------------------------------------------------------------

loc_DB0B:
		cmp	word_11844, 308
		jge	short loc_DB1F
		mov	al, byte_1183A
		mov	ah, 0
		sub	_space_camera_velocity.y, ax
		jmp	loc_DBC3
; ---------------------------------------------------------------------------

loc_DB1F:
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		cmp	ax, (RES_X - 10)
		jge	short loc_DB45
		mov	ax, _space_window_center.x
		add	ax, 4
		call	@space_window_set$qiiii pascal, ax, (RES_Y / 2), _space_window_w, _space_window_h

loc_DB45:
		mov	word_151DE, 0
		mov	ax, word_11844
		mov	bx, 8
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DB9F
		call	sub_DA36
		xor	di, di
		jmp	short loc_DB9A
; ---------------------------------------------------------------------------

loc_DB5F:
		cmp	[si+orb_particle_t.OP_al_rain_sway_x_direction], X_RIGHT
		jnz	short loc_DB74
		inc	[si+orb_particle_t.OP_angle]
		cmp	[si+orb_particle_t.OP_angle], 60h
		jb	short loc_DB81
		mov	[si+orb_particle_t.OP_al_rain_sway_x_direction], X_LEFT
		jmp	short loc_DB81
; ---------------------------------------------------------------------------

loc_DB74:
		dec	[si+orb_particle_t.OP_angle]
		cmp	[si+orb_particle_t.OP_angle], 20h
		ja	short loc_DB81
		mov	[si+orb_particle_t.OP_al_rain_sway_x_direction], X_RIGHT

loc_DB81:
		lea	ax, [si+orb_particle_t.OP_velocity]
		push	ax
		pushd	0
		push	[si+orb_particle_t.OP_speed]
		mov	al, [si+orb_particle_t.OP_angle]
		mov	ah, 0
		push	ax
		call	vector2_at
		inc	di
		add	si, size orb_particle_t

loc_DB9A:
		cmp	di, ORB_PARTICLE_COUNT
		jl	short loc_DB5F

loc_DB9F:
		cmp	word_11844, 30000
		jl	short loc_DBAD
		mov	word_11844, 29992

loc_DBAD:
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		cmp	ax, (RES_X - 10)
		jl	short loc_DBC3
		mov	ax, 1
		jmp	short loc_DBE2
; ---------------------------------------------------------------------------

loc_DBC3:
		mov	ax, word_11844
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DBE0
		cmp	Palettes[0 * size rgb_t].b, 96
		jnb	short loc_DBE0
		inc	Palettes[0 * size rgb_t].b
		call	far ptr	palette_show

loc_DBE0:
		xor	ax, ax

loc_DBE2:
		pop	di
		pop	si
		pop	bp
		retn
sub_DAD7	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DBE6	proc near

var_2C		= byte ptr -2Ch
var_2		= word ptr -2
arg_0		= word ptr  4
arg_2		= word ptr  6
arg_4		= word ptr  8
arg_6		= word ptr  0Ah
arg_8		= word ptr  0Ch
arg_A		= word ptr  0Eh

		enter	2Ch, 0
		push	si
		push	di
		mov	di, [bp+arg_8]
		cmp	[bp+arg_2], 0
		jge	short loc_DBFF
		mov	byte_11846, 1
		mov	al, 1
		jmp	loc_DCF6
; ---------------------------------------------------------------------------

loc_DBFF:
		mov	ax, [bp+arg_6]
		mov	bx, 10h
		cwd
		idiv	bx
		add	ax, 7
		cmp	ax, [bp+arg_2]
		jge	short loc_DC48
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		mov	ax, [bp+arg_A]
		mov	bx, 8
		cwd
		idiv	bx
		push	ax
		push	di
		mov	ax, [bp+arg_A]
		add	ax, [bp+arg_6]
		dec	ax
		cwd
		idiv	bx
		push	ax
		mov	ax, di
		add	ax, [bp+arg_4]
		dec	ax
		push	ax
		call	grcg_byteboxfill_x
		GRCG_OFF_CLOBBERING dx
		mov	al, 2
		jmp	loc_DCF6
; ---------------------------------------------------------------------------

loc_DC48:
		mov	bx, 8
		mov	ax, [bp+arg_A]
		cwd
		idiv	bx
		mov	[bp+arg_A], ax
		mov	bx, 10h
		mov	ax, di
		cwd
		idiv	bx
		mov	di, ax
		mov	ax, [bp+arg_6]
		cwd
		idiv	bx
		mov	[bp+arg_6], ax
		mov	ax, [bp+arg_4]
		cwd
		idiv	bx
		mov	[bp+arg_4], ax
		cmp	[bp+arg_0], 0
		jle	short loc_DC7D
		mov	[bp+var_2], 0
		jmp	short loc_DC84
; ---------------------------------------------------------------------------

loc_DC7D:
		mov	ax, [bp+arg_6]
		dec	ax
		mov	[bp+var_2], ax

loc_DC84:
		xor	si, si
		jmp	short loc_DCD0
; ---------------------------------------------------------------------------

loc_DC88:
		cmp	[bp+arg_2], 7
		jl	short loc_DC9A
		lea	bx, [bp+var_2C]
		add	bx, [bp+var_2]
		mov	byte ptr ss:[bx], 152
		jmp	short loc_DCBA
; ---------------------------------------------------------------------------

loc_DC9A:
		cmp	[bp+arg_2], 0
		jge	short loc_DCAC
		lea	bx, [bp+var_2C]
		add	bx, [bp+var_2]
		mov	byte ptr ss:[bx], 2
		jmp	short loc_DCBA
; ---------------------------------------------------------------------------

loc_DCAC:
		lea	bx, [bp+var_2C]
		add	bx, [bp+var_2]
		mov	al, 159
		sub	al, byte ptr [bp+arg_2]
		mov	ss:[bx], al

loc_DCBA:
		mov	ax, si
		add	ax, ax
		add	ax, [bp+arg_A]
		cmp	ax, 50h	; 'P'
		jge	short loc_DCD5
		inc	si
		mov	ax, [bp+arg_0]
		add	[bp+var_2], ax
		dec	[bp+arg_2]

loc_DCD0:
		cmp	si, [bp+arg_6]
		jl	short loc_DC88

loc_DCD5:
		mov	[bp+si+var_2C],	0
		xor	si, si
		jmp	short loc_DCEF
; ---------------------------------------------------------------------------

loc_DCDD:
		push	[bp+arg_A]
		push	di
		push	ss
		lea	ax, [bp+var_2C]
		push	ax
		push	TX_BLACK
		call	gaiji_putsa
		inc	si
		inc	di

loc_DCEF:
		cmp	si, [bp+arg_4]
		jle	short loc_DCDD
		mov	al, 0

loc_DCF6:
		pop	di
		pop	si
		leave
		retn	0Ch
sub_DBE6	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DCFC	proc near

var_4     	= word ptr -4
var_2     	= word ptr -2
@@measure     	= word ptr  4
@@slot    	= word ptr  6
@@y_center	= word ptr  8
@@x_center	= word ptr  0Ah

		enter	4, 0
		push	si
		push	di
		mov	di, [bp+@@y_center]

		cdg_slot_offset	ax, [bp+@@slot]

		mov	si, ax
		mov	ax, [si+cdg_t.pixel_w]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	[bp+@@x_center], ax
		mov	ax, [si+cdg_t.pixel_h]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	di, ax
		cmp	word_11848, 1
		jg	loc_DDBC
		mov	ax, [si+cdg_t.pixel_w]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, 7
		mov	word_151C4, ax
		mov	word_151C6, 0
		inc	word_11848
		call	cdg_put_noalpha_8 pascal, [bp+@@x_center], di, [bp+@@slot]
		mov	[bp+var_2], 0
		jmp	short loc_DDB1
; ---------------------------------------------------------------------------

loc_DD5A:
		mov	[bp+var_4], 0
		jmp	short loc_DDA2
; ---------------------------------------------------------------------------

loc_DD61:
		mov	ax, [bp+@@x_center]
		mov	bx, 8
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		cmp	dx, 50h	; 'P'
		jge	short loc_DD9E
		mov	ax, [bp+@@x_center]
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		push	dx
		mov	ax, di
		mov	bx, 16
		cwd
		idiv	bx
		push	ax
		push	ds
		push	offset unk_1184C
		push	TX_BLACK + TX_REVERSE
		call	text_putsa

loc_DD9E:
		add	[bp+var_4], 10h

loc_DDA2:
		mov	ax, [si+2]
		cmp	ax, [bp+var_4]
		jge	short loc_DD61
		add	[bp+var_2], 10h
		add	di, 10h

loc_DDB1:
		mov	ax, [si+4]
		cmp	ax, [bp+var_2]
		jge	short loc_DD5A
		jmp	loc_DE6C
; ---------------------------------------------------------------------------

loc_DDBC:
		cmp	word_11848, 3
		jg	short loc_DE01
		inc	word_151C6
		mov	ax, word_151C6
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DDD8
		dec	word_151C4

loc_DDD8:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C4
		push	1
		call	sub_DBE6
		cmp	al, 1
		jnz	short loc_DE6C
		inc	word_11848
		mov	word_151C4, 0
		mov	word_151C6, 0
		jmp	short loc_DE6C
; ---------------------------------------------------------------------------

loc_DE01:
		mov	ax, measure_151E0
		cmp	ax, [bp+@@measure]
		jl	short loc_DE6C
		cmp	[bp+@@measure], 3996
		jz	short loc_DE6C
		cmp	word_11848, 4
		jnz	short loc_DE49
		inc	word_151C6
		mov	ax, word_151C6
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DE2C
		inc	word_151C4

loc_DE2C:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C4
		push	0FFFFh
		call	sub_DBE6
		cmp	al, 2
		jnz	short loc_DE6C
		inc	word_11848
		jmp	short loc_DE6C
; ---------------------------------------------------------------------------

loc_DE49:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	80FFFFh
		call	sub_DBE6
		mov	word_11848, 0
		mov	byte_11846, 1
		mov	ax, 1
		jmp	short loc_DE6E
; ---------------------------------------------------------------------------

loc_DE6C:
		xor	ax, ax

loc_DE6E:
		pop	di
		pop	si
		leave
		retn	8
sub_DCFC	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DE74	proc near

var_4     	= word ptr -4
var_2     	= word ptr -2
@@measure     	= word ptr  4
@@slot    	= word ptr  6
@@y_center	= word ptr  8
@@x_center	= word ptr  0Ah

		enter	4, 0
		push	si
		push	di
		mov	di, [bp+@@y_center]

		cdg_slot_offset	ax, [bp+@@slot]

		mov	si, ax
		mov	ax, [si+cdg_t.pixel_w]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	[bp+@@x_center], ax
		mov	ax, [si+cdg_t.pixel_h]
		cwd
		sub	ax, dx
		sar	ax, 1
		sub	di, ax
		cmp	word_1184A, 1
		jg	loc_DF34
		mov	ax, [si+cdg_t.pixel_w]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, 7
		mov	word_151C8, ax
		mov	word_151CA, 0
		inc	word_1184A
		call	cdg_put_noalpha_8 pascal, [bp+@@x_center], di, [bp+@@slot]
		mov	[bp+var_2], 0
		jmp	short loc_DF29
; ---------------------------------------------------------------------------

loc_DED2:
		mov	[bp+var_4], 0
		jmp	short loc_DF1A
; ---------------------------------------------------------------------------

loc_DED9:
		mov	ax, [bp+@@x_center]
		mov	bx, 8
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		cmp	dx, 50h	; 'P'
		jge	short loc_DF16
		mov	ax, [bp+@@x_center]
		cwd
		idiv	bx
		push	ax
		mov	ax, [bp+var_4]
		cwd
		idiv	bx
		pop	dx
		add	dx, ax
		push	dx
		mov	ax, di
		mov	bx, 16
		cwd
		idiv	bx
		push	ax
		push	ds
		push	offset unk_1184F
		push	TX_BLACK + TX_REVERSE
		call	text_putsa

loc_DF16:
		add	[bp+var_4], 10h

loc_DF1A:
		mov	ax, [si+cdg_t.pixel_w]
		cmp	ax, [bp+var_4]
		jge	short loc_DED9
		add	[bp+var_2], 10h
		add	di, 10h

loc_DF29:
		mov	ax, [si+cdg_t.pixel_h]
		cmp	ax, [bp+var_2]
		jge	short loc_DED2
		jmp	loc_DFE4
; ---------------------------------------------------------------------------

loc_DF34:
		cmp	word_1184A, 3
		jg	short loc_DF79
		inc	word_151CA
		mov	ax, word_151CA
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DF50
		dec	word_151C8

loc_DF50:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C8
		push	1
		call	sub_DBE6
		cmp	al, 1
		jnz	short loc_DFE4
		inc	word_1184A
		mov	word_151C8, 0
		mov	word_151CA, 0
		jmp	short loc_DFE4
; ---------------------------------------------------------------------------

loc_DF79:
		mov	ax, measure_151E0
		cmp	ax, [bp+@@measure]
		jl	short loc_DFE4
		cmp	[bp+@@measure], 3996
		jz	short loc_DFE4
		cmp	word_1184A, 4
		jnz	short loc_DFC1
		inc	word_151CA
		mov	ax, word_151CA
		mov	bx, 4
		cwd
		idiv	bx
		or	dx, dx
		jnz	short loc_DFA4
		inc	word_151C8

loc_DFA4:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	word_151C8
		push	0FFFFh
		call	sub_DBE6
		cmp	al, 2
		jnz	short loc_DFE4
		inc	word_1184A
		jmp	short loc_DFE4
; ---------------------------------------------------------------------------

loc_DFC1:
		push	[bp+@@x_center]
		push	di
		push	[si+cdg_t.pixel_w]
		push	[si+cdg_t.pixel_h]
		push	80FFFFh
		call	sub_DBE6
		mov	word_1184A, 0
		mov	byte_11846, 1
		mov	ax, 1
		jmp	short loc_DFE6
; ---------------------------------------------------------------------------

loc_DFE4:
		xor	ax, ax

loc_DFE6:
		pop	di
		pop	si
		leave
		retn	8
sub_DE74	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_DFEC	proc near

@@star_center		= word ptr -0Ah
@@trail_center		= word ptr -8
@@trail_col		= word ptr -6
@@y		= word ptr -4
@@x		= word ptr -2

		enter	0Ah, 0
		push	si
		push	di
		mov	si, offset orb
		mov	[bp+@@trail_center], offset _orb_trails_center[(ORB_TRAIL_COUNT - 1) * size Point]
		mov	[bp+@@star_center], offset _stars_center
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 0
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		dec	ax
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		dec	ax
		push	ax
		call	grcg_boxfill
		GRCG_OFF_CLOBBERING dx
		xor	di, di
		jmp	short loc_E098
; ---------------------------------------------------------------------------

loc_E053:
		mov	bx, [bp+@@star_center]
		mov	ax, [bx+Point.x]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.x
		add	ax, -4
		mov	[bp+@@x], ax
		mov	bx, [bp+@@star_center]
		mov	ax, [bx+Point.y]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.y
		add	ax, -4
		mov	[bp+@@y], ax
		push	[bp+@@x]	; x
		push	ax	; y
		mov	ax, di
		mov	bx, 2
		cwd
		idiv	bx
		add	dx, PAT_STAR_BIG
		push	dx	; num
		call	super_put_tiny_small
		inc	di
		add	[bp+@@star_center], size Point

loc_E098:
		cmp	di, STAR_COUNT
		jl	short loc_E053
		xor	di, di
		mov	[bp+@@trail_col], 6
		jmp	short loc_E0FB
; ---------------------------------------------------------------------------

loc_E0A6:
		mov	bx, [bp+@@trail_center]
		cmp	[bx+Point.x], SUBPIXEL_NONE
		jz	short loc_E0F6
		mov	bx, [bp+@@trail_center]
		mov	ax, [bx+Point.x]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.x
		mov	[bp+@@x], ax
		mov	bx, [bp+@@trail_center]
		mov	ax, [bx+Point.y]
		mov	bx, 16
		cwd
		idiv	bx
		add	ax, _space_window_center.y
		mov	[bp+@@y], ax
		push	GC_RMW
		mov	ax, [bp+@@trail_col]
		inc	[bp+@@trail_col]
		push	ax
		call	grcg_setcolor
		call	grcg_circlefill pascal, [bp+@@x], [bp+@@y], ORB_RADIUS_FULL
		GRCG_OFF_CLOBBERING dx

loc_E0F6:
		inc	di
		sub	[bp+@@trail_center], size Point

loc_E0FB:
		cmp	di, ORB_TRAIL_COUNT
		jl	short loc_E0A6
		cmp	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jz	loc_E18B
		mov	eax, [si+orb_particle_t.OP_center_x]
		mov	ebx, 16
		cdq
		idiv	ebx
		add	ax, _space_window_center.x
		add	ax, -(ORB_W / 2)
		mov	[bp+@@x], ax
		mov	eax, [si+orb_particle_t.OP_center_y]
		cdq
		idiv	ebx
		add	ax, _space_window_center.y
		add	ax, -(ORB_H / 2)
		mov	[bp+@@y], ax
		cmp	[si+orb_particle_t.OP_al_radius], ORB_RADIUS_FULL
		jb	short loc_E161
		mov	al, byte_151CC
		mov	ah, 0
		mov	bx, 4
		cwd
		idiv	bx
		cwd
		idiv	bx
		add	dx, 8
		mov	di, dx
		call	super_put_rect pascal, [bp+@@x], [bp+@@y], dx
		inc	byte_151CC
		jmp	short loc_E18B
; ---------------------------------------------------------------------------

loc_E161:
		call	grcg_setcolor pascal, (GC_RMW shl 16) + V_WHITE
		mov	ax, [bp+@@x]
		add	ax, (ORB_W / 2)
		push	ax
		mov	ax, [bp+@@y]
		add	ax, (ORB_H / 2)
		push	ax
		mov	al, [si+orb_particle_t.OP_al_radius]
		mov	ah, 0
		push	ax
		call	grcg_circlefill
		GRCG_OFF_CLOBBERING dx

loc_E18B:
		sub	si, size orb_particle_t
		; ; si == particles[ORB_PARTICLE_COUNT - 1]
		xor	di, di
		jmp	loc_E21D
; ---------------------------------------------------------------------------

loc_E193:
		cmp	[si+orb_particle_t.OP_center_x], SUBPIXEL_NONE
		jz	short loc_E219
		mov	ax, _space_window_w
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_x]
		jge	short loc_E219
		mov	ax, _space_window_w
		shl	ax, 3
		add	ax, (4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_x]
		jle	short loc_E219
		mov	ax, _space_window_h
		neg	ax
		shl	ax, 3
		add	ax, (-4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_y]
		jge	short loc_E219
		mov	ax, _space_window_h
		shl	ax, 3
		add	ax, (4 shl 4)
		cwde
		cmp	eax, [si+orb_particle_t.OP_center_y]
		jle	short loc_E219
		mov	eax, [si+orb_particle_t.OP_center_x]
		mov	ebx, 16
		cdq
		idiv	ebx
		add	ax, _space_window_center.x
		add	ax, -4
		mov	[bp+@@x], ax
		mov	eax, [si+orb_particle_t.OP_center_y]
		cdq
		idiv	ebx
		add	ax, _space_window_center.y
		add	ax, -4
		mov	[bp+@@y], ax
		call	super_put_tiny_small pascal, [bp+@@x], ax, [si+orb_particle_t.OP_patnum_tiny]

loc_E219:
		inc	di
		sub	si, size orb_particle_t

loc_E21D:
		cmp	di, ORB_PARTICLE_COUNT
		jl	loc_E193
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		dec	dx
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		dec	ax
		push	ax
		call	grcg_boxfill
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		add	ax, 7
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		dec	ax
		push	ax
		call	grcg_boxfill
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		add	ax, 7
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.y
		sub	dx, ax
		dec	dx
		push	dx
		call	grcg_boxfill
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		mov	dx, _space_window_center.x
		sub	dx, ax
		add	dx, -8
		push	dx
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		push	ax
		mov	ax, _space_window_w
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.x
		add	ax, 7
		push	ax
		mov	ax, _space_window_h
		cwd
		sub	ax, dx
		sar	ax, 1
		add	ax, _space_window_center.y
		add	ax, 7
		push	ax
		call	grcg_boxfill
		GRCG_OFF_CLOBBERING dx
		pop	di
		pop	si
		leave
		retn
sub_DFEC	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

sub_E349	proc near
		push	bp
		mov	bp, sp
		call	sub_D5E1
		call	sub_DFEC
		call	@frame_delay$qi pascal, 1
		graph_accesspage byte_1183A
		mov	al, 1
		sub	al, byte_1183A
		mov	byte_1183A, al
		graph_showpage al
		cmp	byte_11846, 0
		jz	short loc_E37E
		call	text_clear
		mov	byte_11846, 0

loc_E37E:
		inc	word_151E2
		call	_snd_bgm_measure
		mov	measure_151E0, ax
		cmp	measure_151E0, 0
		jge	short loc_E39D
		mov	ax, word_151E2
		mov	bx, 22
		cwd
		idiv	bx
		mov	measure_151E0, ax

loc_E39D:
		pop	bp
		retn
sub_E349	endp

include th05/end/verdict_bitmap.asm

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame
public @staffroll_animate$qv
@staffroll_animate$qv proc near

var_4		= word ptr -4
@@verdict_bitmap_offset		= word ptr -2

		enter	4, 0
		push	si
		push	di
		mov	x_116E2, 32
		mov	col_116E4, 13
		mov	word_116E6, 0Dh
		mov	y_116E8, 16
		mov	PaletteTone, 0
		call	far ptr	palette_show
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		graph_accesspage 0
		call	grcg_byteboxfill_x pascal, large 0, (((RES_X - 1) / 8) shl 16) or (RES_Y - 1)
		GRCG_OFF_CLOBBERING dx
		call	@verdict_stage_scores_put$qv
		call	verdict_bitmap_snap pascal, (1 * VERDICT_SCREEN_SIZE)
		call	grcg_setcolor pascal, (GC_RMW shl 16) + 1
		call	grcg_byteboxfill_x pascal, large 0, (((RES_X - 1) / 8) shl 16) or (RES_Y - 1)
		graph_accesspage 1
		call	grcg_byteboxfill_x pascal, large 0, (((RES_X - 1) / 8) shl 16) or (RES_Y - 1)
		GRCG_OFF_CLOBBERING dx
		call	snd_load pascal, ds, offset aStaff, SND_LOAD_SONG
		kajacall	KAJA_SONG_PLAY
		call	cdg_load_all_noalpha pascal,  0, ds, offset aStf00_cdg
		call	cdg_load_all_noalpha pascal,  1, ds, offset aStf01_cdg
		call	cdg_load_all_noalpha pascal,  2, ds, offset aStf02_cdg
		call	cdg_load_all_noalpha pascal,  3, ds, offset aStf03_cdg
		call	cdg_load_all_noalpha pascal,  4, ds, offset aStf04_cdg
		call	cdg_load_all_noalpha pascal,  5, ds, offset aStf05_cdg
		call	cdg_load_all_noalpha pascal,  6, ds, offset aStf06_cdg
		call	cdg_load_all_noalpha pascal,  7, ds, offset aStf07_cdg
		call	cdg_load_all_noalpha pascal,  8, ds, offset aStf08_cdg
		call	cdg_load_all_noalpha pascal,  9, ds, offset aStf09_cdg
		call	cdg_load_all_noalpha pascal, 10, ds, offset aStf10_cdg
		call	super_entry_bfnt pascal, ds, offset aStf01_bft ; "stf01.bft"
		call	super_entry_bfnt pascal, ds, offset aStf00_bft ; "stf00.bft"
		xor	si, si
		jmp	short loc_E550
; ---------------------------------------------------------------------------

loc_E549:
		call	super_convert_tiny pascal, si
		inc	si

loc_E550:
		cmp	si, 8
		jl	short loc_E549
		mov	Palettes[0 * size rgb_t].b, 48
		call	sub_D387
		xor	si, si
		mov	word_151E2, 0

loc_E565:
		cmp	si, 100
		jg	short loc_E573
		mov	PaletteTone, si
		call	far ptr	palette_show

loc_E573:
		call	sub_E349
		inc	si
		cmp	measure_151E0, 30
		jl	short loc_E565
		call	sub_D49D
		xor	si, si
		jmp	short loc_E58C
; ---------------------------------------------------------------------------

loc_E585:
		call	sub_D8F5
		call	sub_E349
		inc	si

loc_E58C:
		cmp	si, 32
		jl	short loc_E585
		call	sub_D509

loc_E594:
		call	sub_D931
		mov	si, ax
		call	sub_E349
		or	si, si
		jz	short loc_E594
		cmp	measure_151E0, 48
		jl	short loc_E594
		xor	si, si
		xor	di, di

loc_E5AB:
		call	sub_D931
		cmp	si, 128
		jle	short loc_E5C9
		push	(528 shl 16) or 240
		push	(1 shl 16) or 76
		call	sub_DE74
		or	ax, ax
		jz	short loc_E5C9
		xor	si, si

loc_E5C9:
		push	(464 shl 16) or 192
		pushd	(0 shl 16) or 76
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		inc	si
		or	di, di
		jz	short loc_E5AB
		xor	di, di

loc_E5E1:
		call	sub_D931
		push	(464 shl 16) or 200
		push	(2 shl 16) or 92
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E5E1
		xor	si, si
		xor	di, di

loc_E600:
		call	sub_D931
		cmp	si, 256
		jle	short loc_E61E
		push	(464 shl 16) or 224
		push	(4 shl 16) or 120
		call	sub_DE74
		or	ax, ax
		jz	short loc_E61E
		xor	si, si

loc_E61E:
		push	(464 shl 16) or 176
		push	(3 shl 16) or 120
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		inc	si
		or	di, di
		jz	short loc_E600
		call	sub_D531

loc_E63A:
		call	sub_DAD7
		mov	si, ax
		call	sub_E349
		or	si, si
		jz	short loc_E63A
		xor	di, di

loc_E648:
		call	sub_DAD7
		push	(176 shl 16) or 200
		push	(5 shl 16) or 172
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E648

loc_E663:
		call	sub_DAD7
		push	(176 shl 16) or 200
		push	(6 shl 16) or 188
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E663

loc_E67E:
		call	sub_DAD7
		push	(176 shl 16) or 200
		push	(7 shl 16) or 204
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E67E

loc_E699:
		call	sub_DAD7
		push	(176 shl 16) or 200
		push	(8 shl 16) or 220
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E699

loc_E6B4:
		call	sub_DAD7
		push	(176 shl 16) or 200
		push	(9 shl 16) or 236
		call	sub_DCFC
		mov	di, ax
		call	sub_E349
		or	di, di
		jz	short loc_E6B4
		xor	si, si
		mov	[bp+@@verdict_bitmap_offset], 0
		mov	[bp+var_4], 0

loc_E6DB:
		call	@input_reset_sense_held$qv
		cmp	si, 256
		jz	short loc_E6EC
		cmp	si, 257
		jnz	short loc_E6F1

loc_E6EC:
		call	sub_CA9B
		jmp	short loc_E70D
; ---------------------------------------------------------------------------

loc_E6F1:
		cmp	si, 320
		jz	short loc_E6FD
		cmp	si, 321
		jnz	short loc_E702

loc_E6FD:
		call	sub_D16F
		jmp	short loc_E70D
; ---------------------------------------------------------------------------

loc_E702:
		cmp	si, 350
		jnz	short loc_E70D
		call	verdict_bitmap_snap pascal, 0

loc_E70D:
		call	sub_DAD7
		push	(176 shl 16) or 368
		push	(10 shl 16) or 3996
		call	sub_DCFC
		inc	si
		cmp	si, 400
		; Hack (jl	loc_E7BB)
		; No idea why TASM can't assemble this properly after script_op() was
		; decompiled. Seems to be related to the size of this segment; it works
		; when removing some instructions further above.
		; It still doesn't after decompiling cutscene_animate() though?
		db	0Fh, 8Ch, 93h, 00h
		test	_key_det.hi, high INPUT_CANCEL
		jnz	short loc_E757
		test	_key_det.lo, low INPUT_BOMB
		jnz	short loc_E757
		cmp	[bp+var_4], 0
		jnz	short loc_E781
		test	_key_det.lo, low INPUT_SHOT
		jnz	short loc_E74A
		test	_key_det.hi, high INPUT_OK
		jz	short loc_E75C

loc_E74A:
		cmp	[bp+@@verdict_bitmap_offset], 0
		jnz	short loc_E757
		mov	[bp+var_4], 1
		jmp	short loc_E75C
; ---------------------------------------------------------------------------

loc_E757:
		call	sub_E349
		jmp	short loc_E7C1
; ---------------------------------------------------------------------------

loc_E75C:
		test	_key_det.lo, low INPUT_DOWN
		jz	short loc_E76E
		cmp	[bp+@@verdict_bitmap_offset], 0
		jnz	short loc_E76E
		mov	[bp+var_4], 1

loc_E76E:
		test	_key_det.lo, low INPUT_UP
		jz	short loc_E781
		cmp	[bp+@@verdict_bitmap_offset], VERDICT_SCREEN_SIZE
		jnz	short loc_E781
		mov	[bp+var_4], 2

loc_E781:
		cmp	[bp+var_4], 1
		jnz	short loc_E79A
		add	[bp+@@verdict_bitmap_offset], (8 * VERDICT_BITMAP_VRAM_W)
		cmp	[bp+@@verdict_bitmap_offset], VERDICT_SCREEN_SIZE
		jbe	short loc_E7B5
		mov	[bp+@@verdict_bitmap_offset], VERDICT_SCREEN_SIZE
		jmp	short loc_E7B0
; ---------------------------------------------------------------------------

loc_E79A:
		cmp	[bp+var_4], 2
		jnz	short loc_E7BB
		sub	[bp+@@verdict_bitmap_offset], (8 * VERDICT_BITMAP_VRAM_W)
		cmp	[bp+@@verdict_bitmap_offset], 0
		jge	short loc_E7B5
		mov	[bp+@@verdict_bitmap_offset], 0

loc_E7B0:
		mov	[bp+var_4], 0

loc_E7B5:
		call	verdict_bitmap_put pascal, [bp+@@verdict_bitmap_offset]

loc_E7BB:
		call	sub_E349
		jmp	loc_E6DB
; ---------------------------------------------------------------------------

loc_E7C1:
		kajacall	KAJA_SONG_FADE, 4
		mov	si, 100

loc_E7CC:
		mov	PaletteTone, si
		call	far ptr	palette_show
		call	sub_DAD7
		call	sub_E349
		dec	si
		or	si, si
		jg	short loc_E7CC
		call	cdg_free_all
		call	super_free
		call	grc_setclip pascal, large 0, ((RES_X - 1) shl 16) or (RES_Y - 1)
		pop	di
		pop	si
		leave
		retn
@staffroll_animate$qv endp

maine_01__TEXT	ends

; ---------------------------------------------------------------------------
; ===========================================================================

; Segment type:	Pure code
SHARED segment byte public 'CODE' use16
include th02/snd/snd.inc
	extern GRAPH_PUTSA_FX:proc
	extern CDG_PUT_NOALPHA_8:proc
	extern SND_SE_PLAY:proc
	extern _snd_se_update:proc
	extern _bgimage_snap:proc
	extern _bgimage_free:proc
	extern VECTOR2_AT:proc
	extern BGIMAGE_PUT_RECT_16:proc
	extern SND_LOAD:proc
	extern SND_KAJA_INTERRUPT:proc
	extern @PI_LOAD$QINXC:proc
	extern @PI_PUT_8$QIII:proc
	extern @PI_PALETTE_APPLY$QI:proc
	extern @PI_FREE$QI:proc
	extern @input_reset_sense_held$qv:proc
	extern @INPUT_WAIT_FOR_CHANGE$QI:proc
	extern _snd_bgm_measure:proc
	extern @FRAME_DELAY$QI:proc
	extern CDG_LOAD_ALL_NOALPHA:proc
	extern CDG_FREE_ALL:proc
SHARED ends

	.data

	; libs/master/pal[data].asm
	extern PaletteTone:word

	; libs/master/rand[data].asm
	extern random_seed:dword

	; th04/hardware/grppsafx.asm
	extern _graph_putsa_fx_func:word

include th03/snd/se_state[data].asm
include th04/hardware/bgimage[data].asm
include th05/mem[data].asm
include th05/snd/load[data].asm
include th04/snd/snd[data].asm
include th03/formats/pi_put_masked[data].asm
include th05/formats/pi_buffers[bss].asm
include th05/hardware/vram_planes[data].asm
include th03/formats/cdg[data].asm
include th03/cutscene/cutscene[data].asm
public _page_shown
_page_shown	db 0
	evendata
public _BG_FN
_BG_FN	label dword
		dd aExed01_pi		; "EXED01.pi"
		dd aExed07_pi		; "EXED07.pi"
		dd aExed08_pi		; "EXED08.pi"
		dd aExed09_pi		; "EXED09.pi"
		dd aExed10_pi		; "EXED10.pi"
		dd aExed16_pi		; "EXED16.pi"
		dd aExed15_pi		; "EXED15.pi"
		dd 0
		dd aExed01_pi_0		; "EXED01.pi"
		dd aExed11_pi		; "EXED11.pi"
		dd aExed11_pi_0		; "EXED11.pi"
		dd aExed11_pi_1		; "EXED11.pi"
		dd aExed03_pi		; "EXED03.pi"
		dd aExed16_pi_0		; "EXED16.pi"
		dd aExed15_pi_0		; "EXED15.pi"
		dd 0
		dd aExed01_pi_1		; "EXED01.pi"
		dd aExed12_pi		; "EXED12.pi"
		dd aExed12_pi_0		; "EXED12.pi"
		dd aExed13_pi		; "EXED13.pi"
		dd aExed04_pi		; "EXED04.pi"
		dd aExed16_pi_1		; "EXED16.pi"
		dd aExed15_pi_1		; "EXED15.pi"
		dd 0
		dd aExed01_pi_2		; "EXED01.pi"
		dd aExed14_pi		; "EXED14.pi"
		dd aExed05_pi		; "EXED05.pi"
		dd aExed14_pi_0		; "EXED14.pi"
		dd aExed06_pi		; "EXED06.pi"
		dd aExed16_pi_2		; "EXED16.pi"
		dd aExed15_pi_2		; "EXED15.pi"
		dd 0
public _BG_QUARTER
_BG_QUARTER	label word
		dw 1, 0, 1, 3, 0, 0, 0, 0
		dw 1, 0, 1, 2, 1, 1, 1, 0
		dw 1, 2, 0, 1, 0, 2, 2, 0
		dw 1, 0, 0, 2, 0, 3, 3, 0
public _LINES
_LINES	dd aProjectOfTouho
		dd aNo_1Buumx		; "		     Project of	TOUHOU	  "...
		dd aReimuHakureiSh
		dd aNo_2Buumx
		dd aReimuHakurei_0
		dd aRikaEngineer
		dd aMeiraSamurai
		dd aMarisaKirisame
		dd aMimaGhost
		dd aNo_3Buumx
		dd aReimuHakurei_1
		dd aMarisaKirisa_0
		dd aMimaGhost_0
		dd aEllenWitch
		dd aKotohimePrince
		dd aKanaAnaberalPo
		dd aRikakoAsakuraS
		dd aTiyuriKitashir
		dd aYumemiOkazakiP
		dd aNo_4Buumx
		dd aReimuHakurei_2
		dd aMarisaKirisa_1
		dd aOrangeOriental
		dd aKurumiVampire
		dd aElliyGateKeepe
		dd aYukaOrientalDe
		dd aMugetuMaid
		dd aGengetuDemon
		dd aNo_5Buumx
		dd aReimuHakurei_3
		dd aMarisaKirisa_2
		dd aMimaGhost_1
		dd aYukaOriental_0
		dd aSaraGateKeeper
		dd aLuizeDemon
		dd aAliceWitchOfDe
		dd aYukiBlackWitch
		dd aMaiWhiteWitch
		dd aYumekoMaid
		dd aShinkiGoddessO
		dd aProgramerZunJu
		dd aGraphicsZunJun
		dd aMusicComposeZu
		dd aP_m_d_ProgramM
		dd aSpecialThanksA
		dd aAmusementMaker
		dd aAndAllTestPlay
public _LINES_PER_SCREEN, _line_id_on_screen
_LINES_PER_SCREEN	equ $-2
		dw 1, 2, 6, 10, 9, 12, 7
		db    0
		db    0
_line_id_on_screen	dw 0
aExed01_pi	db 'EXED01.pi',0
aExed07_pi	db 'EXED07.pi',0
aExed08_pi	db 'EXED08.pi',0
aExed09_pi	db 'EXED09.pi',0
aExed10_pi	db 'EXED10.pi',0
aExed16_pi	db 'EXED16.pi',0
aExed15_pi	db 'EXED15.pi',0
aExed01_pi_0	db 'EXED01.pi',0
aExed11_pi	db 'EXED11.pi',0
aExed11_pi_0	db 'EXED11.pi',0
aExed11_pi_1	db 'EXED11.pi',0
aExed03_pi	db 'EXED03.pi',0
aExed16_pi_0	db 'EXED16.pi',0
aExed15_pi_0	db 'EXED15.pi',0
aExed01_pi_1	db 'EXED01.pi',0
aExed12_pi	db 'EXED12.pi',0
aExed12_pi_0	db 'EXED12.pi',0
aExed13_pi	db 'EXED13.pi',0
aExed04_pi	db 'EXED04.pi',0
aExed16_pi_1	db 'EXED16.pi',0
aExed15_pi_1	db 'EXED15.pi',0
aExed01_pi_2	db 'EXED01.pi',0
aExed14_pi	db 'EXED14.pi',0
aExed05_pi	db 'EXED05.pi',0
aExed14_pi_0	db 'EXED14.pi',0
aExed06_pi	db 'EXED06.pi',0
aExed16_pi_2	db 'EXED16.pi',0
aExed15_pi_2	db 'EXED15.pi',0
aProjectOfTouho	db '                  Project of TOUHOU    All Cast',0
aNo_1Buumx	db 'No.1 「東方靈異伝」 ～ Highly Responsive to Prayers    1996,1997',0
aReimuHakureiSh	db '      Reimu Hakurei                           ( Shaman )',0
aNo_2Buumx	db 'No.2 「東方封魔録」 ～ The story of eastern wonderland 1997',0
aReimuHakurei_0	db '      Reimu Hakurei                           ( Shaman )',0
aRikaEngineer	db '         Rika                                ( Engineer )',0
aMeiraSamurai	db '         Meira                                ( Samurai )',0
aMarisaKirisame	db '     Marisa Kirisame                         ( Sorceress )',0
aMimaGhost	db '         Mima                                 ( Ghost )',0
aNo_3Buumx	db 'No.3 「東方夢時空」 ～ The Phantasmagoria of Dim.Dream... 1997',0
aReimuHakurei_1	db '      Reimu Hakurei                           ( Shaman )',0
aMarisaKirisa_0	db '     Marisa Kirisame                         ( Sorceress )',0
aMimaGhost_0	db '         Mima                                  ( Ghost )',0
aEllenWitch	db '        Ellen                                  ( Witch )',0
aKotohimePrince	db '       Kotohime                               ( Princess )',0
aKanaAnaberalPo	db '     Kana Anaberal                           ( Poltergeist )',0
aRikakoAsakuraS	db '     Rikako Asakura                          ( Scientist )',0
aTiyuriKitashir	db '   Tiyuri Kitashirakawa                  ( Assistant professor )',0
aYumemiOkazakiP	db '     Yumemi Okazaki                          ( Professor )',0
aNo_4Buumx	db 'No.4 「東方幻想郷」 ～ Lotus Land Story                  1998',0
aReimuHakurei_2	db '      Reimu Hakurei                           ( Shaman )',0
aMarisaKirisa_1	db '     Marisa Kirisame                         ( Sorceress )',0
aOrangeOriental	db '        Orange                             ( Oriental demon )',0
aKurumiVampire	db '        Kurumi                                ( Vampire )',0
aElliyGateKeepe	db '        Elliy                                ( Gate keeper )',0
aYukaOrientalDe	db '         Yuka                              ( Oriental demon )',0
aMugetuMaid	db '        Mugetu                                 ( Maid )',0
aGengetuDemon	db '        Gengetu                                ( Demon )',0
aNo_5Buumx	db 'No.5 「東方怪綺談」 ～ Mystic Square                    1998',0
aReimuHakurei_3	db '      Reimu Hakurei                           ( Shaman )',0
aMarisaKirisa_2	db '     Marisa Kirisame                         ( Sorceress )',0
aMimaGhost_1	db '         Mima                                  ( Ghost )',0
aYukaOriental_0	db '         Yuka                              ( Oriental demon )',0
aSaraGateKeeper	db '         Sara                                ( Gate keeper )',0
aLuizeDemon	db '        Luize                                  ( Demon )',0
aAliceWitchOfDe	db '        Alice                              ( Witch of death )',0
aYukiBlackWitch	db '         Yuki                                ( Black witch )',0
aMaiWhiteWitch	db '         Mai                                 ( White witch )',0
aYumekoMaid	db '        Yumeko                                 ( Maid )',0
aShinkiGoddessO	db '        Shinki                         ( Goddess of devil',27h,'s world )',0
aProgramerZunJu	db '      Programer                                ZUN (Junya Ota)',0
aGraphicsZunJun	db '      Graphics                                 ZUN (Junya Ota)',0
aMusicComposeZu	db '    Music Compose                              ZUN (Junya Ota)',0
aP_m_d_ProgramM	db '    P.M.D. Program                             M.Kajihara(KAJA)',0
aSpecialThanksA	db '    Special Thanks                             Aotaka',0
aAmusementMaker	db '                                               Amusement Makers',0
aAndAllTestPlay	db '             and all test player and you ... ',0
public _EXED
_EXED db 'EXED',0
include th04/hiscore/alphabet[data].asm
public _regist_page_shown
_regist_page_shown	db 0
public _entered_name_cursor
_entered_name_cursor	dw 0
public _SCOREDAT_FN, _SCOREDAT_FN_2
_SCOREDAT_FN	db 'GENSOU.SCR',0
include th05/formats/scoredat_load_for[data].asm
_SCOREDAT_FN_2	db 'GENSOU.SCR',0
public _hi01_pi, _scnum_bft, _sctm0_bft, _sctm1_bft
public _SLOW_MODE_MSG_SHADOW, _SLOW_MODE_MSG, _BGM_NAME_FN
public _STAGE_1_MSG, _STAGE_2_MSG, _STAGE_3_MSG, _STAGE_4_MSG
public _STAGE_5_MSG, _STAGE_6_MSG, _FINAL_SCORE_MSG_0
_hi01_pi	db 'hi01.pi',0
_scnum_bft	db 'scnum.bft',0
_sctm0_bft	db 'sctm0.bft',0
_sctm1_bft	db 'sctm1.bft',0
_SLOW_MODE_MSG_SHADOW	db 'スローモードでのプレイでは、スコアは記録されません',0
_SLOW_MODE_MSG	db 'スローモードでのプレイでは、スコアは記録されません',0
_BGM_NAME_FN	db 'name',0
		db 0
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_scores.cpp can
; read this. `label` emits nothing, so every following offset is
; unchanged, and this block's own references keep the original spelling.
public _verdict_left
_verdict_left	label word
x_116E2	dw 336
; kb/codegen/0123: a zero-byte alias so th04/end/verdict_digits.cpp can read
; this. `label` emits nothing, so every following offset is unchanged, and
; this block's own thirty-odd references keep the original spelling.
public _verdict_col
_verdict_col	label word
col_116E4	dw 2
word_116E6	dw 6
; kb/codegen/0123: a zero-byte alias so th05/end/verdict_scores.cpp can
; read this. `label` emits nothing, so every following offset is
; unchanged, and this block's own references keep the original spelling.
public _verdict_top
_verdict_top	label word
y_116E8	dw 48
include th04/gaiji/verdict[data].asm
public _POINT_MSG
_POINT_MSG	label byte
aU__0		db '点',0
public _DOT_MSG
_DOT_MSG	label byte
aBd		db '．',0
public _PERCENT_MSG
_PERCENT_MSG	label byte
aBu		db '％',0
public _DOT_MSG_0
_DOT_MSG_0	label byte
aBd_0		db '．',0
aBu_0		db '％',0
aB@b@b@b@b@b@b@	db '　　　　　　　 腕前判定',0
aUqiUx		db '難易度',0
aNPiuU_		db '最終得点',0
aGGxi		db 'ミス回数',0
aGGaogcpi	db 'ボム使用回数',0
aGqbGatbrmcj	db 'ゲーム達成率',0
aIlcSObcj	db '悪霊退治率',0
aGagcgegai	db 'アイテム回収率',0
aUU_gagcgeganNv	db '得点アイテム最高点率',0
aLcnzvv		db '気合い',0
aPicacovCj	db '処理落ち率',0
aVavVVSrso	db 'あなたの腕前',0
aI		db '回',0
aI_0		db '回',0
aU_		db '点',0
a_ude_txt	db '_ude.txt',0
aBhbhbhbhbhbhu_	db '？？？？？？点',0
aPicacovVVcvsfT	db '処理落ちによる判定不可',0
aUde_pi		db 'ude.pi',0
_STAGE_1_MSG	db '　１面　',0
_STAGE_2_MSG	db '　２面　',0
_STAGE_3_MSG	db '　３面　',0
_STAGE_4_MSG	db '　４面　',0
_STAGE_5_MSG	db '　５面　',0
_STAGE_6_MSG	db '　６面　',0
_FINAL_SCORE_MSG_0	db '最終得点',0
byte_1183A	db 0
		db 0
particle_i_1183C	dw 0
word_1183E	dw 0
byte_11840	db 0
		db 0
word_11842	dw 0
word_11844	dw 0
byte_11846	db 0
		db 0
word_11848	dw 0
word_1184A	dw 0
unk_1184C	db  20h
		db  20h
		db    0
unk_1184F	db  20h
		db  20h
		db    0
aStaff		db 'staff',0
aStf00_cdg	db 'stf00.cdg',0
aStf01_cdg	db 'stf01.cdg',0
aStf02_cdg	db 'stf02.cdg',0
aStf03_cdg	db 'stf03.cdg',0
aStf04_cdg	db 'stf04.cdg',0
aStf05_cdg	db 'stf05.cdg',0
aStf06_cdg	db 'stf06.cdg',0
aStf07_cdg	db 'stf07.cdg',0
aStf08_cdg	db 'stf08.cdg',0
aStf09_cdg	db 'stf09.cdg',0
aStf10_cdg	db 'stf10.cdg',0
aStf01_bft	db 'stf01.bft',0
aStf00_bft	db 'stf00.bft',0

	.data?

	extern _resident:dword

	; libs/master.lib/pal[bss].asm
	extern Palettes:byte:48

	; th04/hardware/input[bss].asm
	extern _key_det:word

	; th03/formats/cdg[bss].asm
	extern _cdg_slots:cdg_t:CDG_SLOT_COUNT

	; th05/allcast.cpp
	extern _loaded_screen_id:word
	extern _line_id_total:word

include th04/formats/scoredat[bss].asm
public _glyphballs
_glyphballs	glyphball_t	(SCOREDAT_NAME_LEN + 1) dup (<?>)
include th03/hiscore/regist[bss].asm
public _rank, _playchar
_rank	db ?
_playchar	db ?
		db 3 dup(?)
public _skill
; kb/codegen/0123: zero-byte aliases so th04/end/verdict_digits.cpp can
; reach these two. `label` emits nothing.
public _skill_stash_quarter
_skill_stash_quarter	label byte
byte_1517C	db ?
		db ?
_skill	dd ?
public _skill_quarter
_skill_quarter	label dword
dword_15182	dd ?
_verdict_rank	db ?
byte_15187	db ?
		db 27 dup(?)
byte_151A3	db ?
		db    ?	;
byte_151A5	db ?
		db 27 dup(?)
byte_151C1	db ?
		db 2 dup(?)
word_151C4	dw ?
word_151C6	dw ?
word_151C8	dw ?
word_151CA	dw ?
byte_151CC	db ?
		db ?
public _space_window_center, _space_window_w, _space_window_h
public _space_window_w, _space_window_h
_space_window_w	dw ?
_space_window_h	dw ?
point_151D2	Point <?>
_space_window_center	Point <?>
public _space_camera_velocity
_space_camera_velocity	Point <?>
word_151DE	dw ?
measure_151E0	dw ?
word_151E2	dw ?
	extern _particles:orb_particle_t:ORB_PARTICLE_COUNT
	extern _orb_trails_center:Point:ORB_TRAIL_COUNT
	extern _stars_center:Point:STAR_COUNT
	extern _verdict_bitmap:word:(VERDICT_SCREEN_H * 2 * (VERDICT_BITMAP_W / 16))

		end
