; No-byte declarations for data moved to th03/mainl/rsedat[data].asm.
extern _REGIST_PLAYCHARS:dword
extern _REGI_PLAYCHAR:byte
extern _SCOREDAT_FN_PTR:word
extern _rank_image_fn:word
extern _REGIST_INPUT_HOLD_INIT:word:4
extern _regib_pi:byte
extern _regi2_bft:byte
extern _regi1_bft:byte
extern _score_m:byte
extern _conti_pi:byte
extern _conti_cd2:byte
extern _GAMEOVER_BG_FN:byte
extern _gameover_bgm_fn:byte
extern _ending_script_fn:dword
