#ifndef TH03_REPLAY_BUILD_HPP
#define TH03_REPLAY_BUILD_HPP

#if defined(TH03_REPLAY_DEVTOOLS)
#define TH03_REPLAY_DEV_OVERLAY
#define TH03_REPLAY_DEV_STAGE_SELECT
#endif

#endif /* TH03_REPLAY_BUILD_HPP */
