#ifndef TH03_REPLAY_HANDOFF_HPP
#define TH03_REPLAY_HANDOFF_HPP

#define T3_REPLAY_RES_MAGIC_0 'T'
#define T3_REPLAY_RES_MAGIC_1 '3'
#define T3_REPLAY_RES_MAGIC_2 'R'
#define T3_REPLAY_RES_MAGIC_3 '1'
#define T3_REPLAY_RES_MODE_INDEX 4
#define T3_REPLAY_RES_SLOT_INDEX 5
#define T3_REPLAY_RES_SAMPLE_COUNT_INDEX 6
#define T3_REPLAY_RES_GLOBAL_FRAME_INDEX 10
#define T3_REPLAY_RES_INPUT_SIZE_INDEX 14
#define T3_REPLAY_RES_COMMITTED_SIZE_INDEX 18
#define T3_REPLAY_RES_PROTECT_FLAGS_INDEX 22
#define T3_REPLAY_RES_GUARD_SECTOR_INDEX 23
#define T3_REPLAY_RES_GUARD_OFFSET_INDEX 27
#define T3_REPLAY_RES_PROTECT_BUF_SEG_INDEX 29
#define T3R_DIAG_CODE_INDEX 31
#define T3R_DIAG_DRIVE_INDEX 32
#define T3R_DIAG_DOS_AX_INDEX 33
#define T3R_DIAG_BYTES_SECTOR_INDEX 35
#define T3R_DIAG_ROOT_ENTRIES_INDEX 37
#define T3R_DIAG_ROOT_START_INDEX 39
#define T3R_DIAG_ROOT_SECTORS_INDEX 43
#define T3R_DIAG_SECTOR_INDEX 45
#define T3R_DIAG_OFFSET_INDEX 49
#define T3R_DIAG_EXPECTED_INDEX 51
#define T3R_DIAG_ACTUAL_INDEX 55
#define T3R_DIAG_END_INDEX 59
#define T3_REPLAY_RES_CURSOR_END_INDEX T3R_DIAG_END_INDEX
#define T3_REPLAY_RES_PROTECT_INVALID 0x01
#define T3_REPLAY_RES_PROTECT_LOCATED 0x02
#define T3_REPLAY_RES_MODE_RECORD 'r'
#define T3_REPLAY_RES_MODE_PLAYBACK 'p'
#define T3_REPLAY_RES_MODE_USER_RECORD 'u'
#define T3_REPLAY_RES_MODE_USER_PLAYBACK 'v'

#endif /* TH03_REPLAY_HANDOFF_HPP */
