#ifndef TH03_REPLAY_HANDOFF_HPP
#define TH03_REPLAY_HANDOFF_HPP

#define T3_REPLAY_RES_MAGIC_0 'T'
#define T3_REPLAY_RES_MAGIC_1 '3'
#define T3_REPLAY_RES_MAGIC_2 'R'
#define T3_REPLAY_RES_MAGIC_3 '1'
#define T3_REPLAY_RES_MODE_INDEX 4
#define T3_REPLAY_RES_SLOT_INDEX 5
#define T3_REPLAY_RES_MODE_RECORD 'r'
#define T3_REPLAY_RES_MODE_PLAYBACK 'p'
#define T3_REPLAY_RES_MODE_USER_RECORD 'u'
#define T3_REPLAY_RES_MODE_USER_PLAYBACK 'v'

#endif /* TH03_REPLAY_HANDOFF_HPP */
