#ifndef TH03_REPLAY_HANDOFF_HPP
#define TH03_REPLAY_HANDOFF_HPP

#define T3_REPLAY_RES_MAGIC_0 'T'
#define T3_REPLAY_RES_MAGIC_1 '3'
#define T3_REPLAY_RES_MAGIC_2 'R'
#define T3_REPLAY_RES_MAGIC_3 '1'
#define T3_REPLAY_RES_MODE_INDEX 4
#define T3_REPLAY_RES_SLOT_INDEX 5
#define T3_REPLAY_RES_SAMPLE_COUNT_INDEX 6
#define T3_REPLAY_RES_GLOBAL_FRAME_INDEX 10
#define T3_REPLAY_RES_INPUT_SIZE_INDEX 14
#define T3_REPLAY_RES_COMMITTED_SIZE_INDEX 18
#define T3_REPLAY_RES_PLAYBACK_CHECKPOINT_INDEX \
	T3_REPLAY_RES_COMMITTED_SIZE_INDEX
#define T3_REPLAY_RES_PLAYBACK_STAGE_INDEX \
	T3_REPLAY_RES_PLAYBACK_CHECKPOINT_INDEX
#define T3_REPLAY_RES_PREROLL_TARGET_INDEX \
	(T3_REPLAY_RES_PLAYBACK_CHECKPOINT_INDEX + 1)
#define T3_REPLAY_SND_SE_UPDATE_INT_OFFSET 26
#define T3_REPLAY_RES_PROTECT_FLAGS_INDEX 22
#define T3_REPLAY_RES_GUARD_SECTOR_INDEX 23
#define T3_REPLAY_RES_GUARD_OFFSET_INDEX 27
#define T3_REPLAY_RES_PROTECT_BUF_SEG_INDEX 29
#define T3R_DIAG_CODE_INDEX 31
#define T3R_DIAG_DRIVE_INDEX 32
#define T3R_DIAG_DOS_AX_INDEX 33
#define T3R_DIAG_BYTES_SECTOR_INDEX 35
#define T3R_DIAG_ROOT_ENTRIES_INDEX 37
#define T3R_DIAG_ROOT_START_INDEX 39
#define T3R_DIAG_ROOT_SECTORS_INDEX 43
#define T3R_DIAG_SECTOR_INDEX 45
#define T3R_DIAG_OFFSET_INDEX 49
#define T3R_DIAG_EXPECTED_INDEX 51
#define T3R_DIAG_ACTUAL_INDEX 55
#define T3R_DIAG_INT25_FLAGS_INDEX 59
#define T3R_DIAG_INT25_STACK_FLAGS_INDEX 61
#define T3R_DIAG_END_INDEX 63
#define T3_REPLAY_RES_CURSOR_END_INDEX T3R_DIAG_END_INDEX
#define T3_REPLAY_RES_MAINL_CONTROL_INDEX T3R_DIAG_END_INDEX
#define T3_REPLAY_RES_DEBUG_STAGE_START_INDEX (T3R_DIAG_END_INDEX + 1)
#define T3_REPLAY_RES_PAUSE_CANCEL_LATCH_INDEX (T3R_DIAG_END_INDEX + 2)
#define T3_REPLAY_RES_GUARD_FRESH_INDEX (T3R_DIAG_END_INDEX + 3)
#define T3_REPLAY_RES_MAINL_VSYNC_INDEX (T3R_DIAG_END_INDEX + 4)
#define T3R_RES_PREROLL_FORCE_INDEX (T3R_DIAG_END_INDEX + 5)
// Transient MAIN timing state. Keeping this in the resident avoids shifting
// replay BSS while still carrying one outer-frame pause decision to the
// end-of-frame slowdown sampler.
#define T3_REPLAY_RES_TIMING_FLAGS_INDEX 186
#define T3_REPLAY_RES_TIMING_BASELINE_INDEX 187
#define T3_REPLAY_RES_TIMING_END_INDEX 189
#define T3_REPLAY_TIMING_SAMPLE_PENDING 0x01
#define T3_REPLAY_TIMING_PAUSE_OPENED 0x02
#define T3_REPLAY_TIMING_BASELINE_PENDING 0x04
#if (T3_REPLAY_RES_TIMING_END_INDEX > 198)
#error Replay timing state exceeds resident->unused_3
#endif
#define T3_REPLAY_RES_PROTECT_INVALID 0x01
#define T3_REPLAY_RES_PROTECT_LOCATED 0x02
#define T3_REPLAY_RES_PROTECT_ERROR 0x04
#define T3_REPLAY_RES_MODE_RECORD 'r'
#define T3_REPLAY_RES_MODE_PLAYBACK 'p'
#define T3_REPLAY_RES_MODE_USER_RECORD 'u'
#define T3_REPLAY_RES_MODE_USER_PLAYBACK 'v'
// Keep this name distinct from T3_REPLAY_RES_MODE_USER_PLAYBACK within the
// identifier-prefix limit of Turbo C++ 4.0J's preprocessor.
#define T3R_RES_MODE_USER_GAME_OVER 'V'
#if (T3_REPLAY_RES_MODE_USER_PLAYBACK != 'v') || \
	(T3R_RES_MODE_USER_GAME_OVER != 'V')
#error Replay handoff modes collide in the Turbo C++ preprocessor
#endif
#define T3_REPLAY_RES_MODE_RESTART 's'
#define T3_REPLAY_RES_MODE_SAVE_PROMPT 'n'
#define T3_REPLAY_RES_MODE_SAVE_DIRECT 'w'
#define T3_REPLAY_RES_MODE_SAVE_PROMPT_GAME_OVER 'g'
#define T3_REPLAY_RES_MODE_SAVE_PROMPT_CLEAR 'c'
#define T3_REPLAY_RES_MODE_RESUME_GAME_OVER 'G'
#define T3_REPLAY_RES_MODE_RESUME_CLEAR 'C'
#define T3_REPLAY_RES_MODE_ACCEL_CLEANUP 'x'

#endif /* TH03_REPLAY_HANDOFF_HPP */
